### ISSUE TITLE
Bug: DayZ standalone does not resize properly (75%)

### ISSUE THREAD

**Issue by dats3xykid** [Codeusa/Borderless-Gaming#102]
Whenever I open dayz in windowed mode then go to borderless, my resolution changes to a 75% resolution rather than maintaining 1080p which is 1920x1080. Anyone have an idea on why it keeps changing whenever I go borderless. It's not too much of a hassle to change the resolution after, but it would be nice to not have to do it everytime.

**Comment by psouza4** [comment]
Turn off auto-maximize in your favorites for Day-Z.

**Comment by dats3xykid** [comment]
The issue s still persisting, I open dayz then I turn on borderless with automaximize off and the resolution changes to 75% rather than adjusting to 100%

**Comment by psouza4** [comment]
Borderless Gaming is depending on each game's handling of its windows being forcibly resized. To that end, not all games are compatible. Some will render oddly, some will have mouse positioning issues as they are programmed to believe the screen is still in a specific resolution, some will not scale to fill the new window size, some will simply revert to their original window size, and so on. Unfortunately, there's nothing Borderless Gaming can do in these situations.  I just can't verify that there's anything we can fix in this situation.
