### ISSUE TITLE
Minimizing to the Taskbar

### ISSUE THREAD

**Issue by IamNotKyle** [Codeusa/Borderless-Gaming#103]
I can't minimize borderless programs to the taskbar, I'm not sure if that's a bug or somthing that has yet to be implemented. Right now when I use Win+DownArrow the program does not minimize and when I use Win+D and reopen another window, the borderless window comes back up as well. I understand why Win+DownArrow doesn't work but why does the window come back up?

**Comment by psouza4** [comment]
That's correct -- any windows where the caption has been removed will no longer be minimizable.  One of the window styles that has to be removed is WS_MINIMIZE, or there will still be a caption/frame.  Removing this style also prevents the window from being minimized.

You can choose to pause processing (menu option), then click the game from the applications list and choose to un-borderless the game.  Then you can minimize it again.  It's a multi-step process, but if you have to minimize and absolutely want to remove the borders, this is your only option.

**Comment by IamNotKyle** [comment]
Oh, okay. Very informative. Thanks for the help.
