### ISSUE TITLE
The application does not find any process at all, even with Admin rights.

### ISSUE THREAD

**Issue by nversluis** [Codeusa/Borderless-Gaming#104]
The application does not find any processes. In the bottom left, the text "Loading..." remains. 

Specs:
i5 3570k, GTX770 (latest drivers), 8GB RAM, Win7 HP x64

Also, clicking view full process details crashes the program.

It's such a shame. I really want to be able to Alt + Tab in CodWaW and this program seemed perfect for the job.

**Comment by nversluis** [comment]
Never mind. However, what you should probably do is also link to the installer in ver 7.9 as I simply tried to run the .exe due to the absence of a link to the installer.

**Comment by Codeusa** [comment]
This has been fixed
