### ISSUE TITLE
Everquest Titanium client (used by EQEmu) no longer maximising as expected since 7.5 build

### ISSUE THREAD

**Issue by AnthonyHJ** [Codeusa/Borderless-Gaming#106]
When the program starts, the game gets maximised as intended. After server selection, the game will close and reopen the window and this is where it goes wrong.

In the 6.5 build, the window would maximise again, but since the 7.5 build, it has needed to be manually maximised after the window reopens. This affects every build since then, but reinstalling 6.5 will fix the issue.

**Comment by psouza4** [comment]
6.5 would constantly try to re-borderless applications in your favorites over and over, causing havoc with several games.  This behavior was removed, however, Borderless Gaming should attempt to re-borderless an application if the primary window handle changes.  This change was made to maximize compatibility across the most games, but it sounds like "Everquest Titanium" may not be one of them.
