### ISSUE TITLE
Bug: dual screen supersize isn't working as intended

### ISSUE THREAD

**Issue by liquidmetal17** [Codeusa/Borderless-Gaming#107]
Version 7.9

I use borderless gaming with World of Warcraft to create a borderless window that spans across two monitors.  If I simply hit supersize, WoW becomes maximized on my primary monitor.  If I hit supersize again, it spans both screens, but my secondary screen is black.  In order to correctly supersize, I have to maximize it to my secondary monitor, and then supersize it.

I have tried adding it to favorites and defining specific origins and window sizes, but I still end up with a monitor that has either a black screen or a frozen image of the first frame that was rendered.  If it makes a difference, my primary monitor is on the right.  For the sake of bug testing, I just switched my primary monitor to the left screen.  The result was the same.  Version 6.5 did not have the supersize issue; I did not use any of the versions in between.

Regardless of the version, making the process a favorite always results in the window being maximized to one monitor.

Thank you very much for creating this application and for continuing to put hard work into improving it.  I really appreciate it!

**Comment by Jademalo** [comment]
I know this is the necro of the century, but I'm having this same issue.

As the OP states, maximising the window on my left hand monitor and then supersizing across all three works. Trying to Supersize it in any other way just results in it going full screen on the primary monitor.
