### ISSUE TITLE
Not working with NBA 2k15

### ISSUE THREAD

**Issue by addicted2karma** [Codeusa/Borderless-Gaming#109]
Seems to be a bug. At first borderless window works during the opening scenes with the publisher and company pages, but once it gets to the actual game menu, it reverts from a borderless window mode to window mode.

I've tried running normally as well as an administrator.

**Comment by psouza4** [comment]
If it's an Unreal 3 game, it can't be avoided.  You can try waiting until the game is fully loaded and into the game before activating Borderless Gaming, but if it still fails, then it's the game's behavior that's overriding (and nothing we can do).

**Comment by addicted2karma** [comment]
Ah i see. Thanks!
