### ISSUE TITLE
Nuclear Throne does not work!

### ISSUE THREAD

**Issue by thro1** [Codeusa/Borderless-Gaming#110]
Hi!

Nuclear Throne ( http://store.steampowered.com/app/242680/ ) does not work in borderless fullscreen with this program but it (sort of) works with a program called Shift Window.

Here's what happens when I do it with only one monitor enabled:
Start the game, switch off Fullscreen, game turns to Windowed. Switch to Borderless Gaming 7.9 and enable it for Nuclear Throne. Game then tries to go into borderless but just ends up attempting to maximize the window (or appearing to).

Here's what happens when I do the above with two monitors enabled:
The game starts to stretch itself from my main monitor over to the other monitor until it reaches the end of the second monitor and it never goes into borderless either.

BUT the game does work in Borderless Windowed mode if you use a program called Shift Window. The issue with that method however is that while the game is borderless, the Windows Taskbar stays above the game so it's not ideal as you have to hide the taskbar for it to work and I'd rather use Borderless Gaming since it's a true blessing of a software!
( This is Shift Window http://grismar.net/shiftwindow/ )

**Comment by psouza4** [comment]
Turn off the option to auto-maximize, so that it only removes the border.

**Comment by thro1** [comment]
That did indeed work. Thanks a lot!

**Comment by psouza4** [comment]
Glad to hear it.  :)

**Comment by hauzer** [comment]
This isn't ideal. NT doesn't seem to register being resized by BG, so it never scales its graphics accordingly, staying at 320x240 even in fullscreen.

![2016-01-06 21_49_37-greenshot](https://cloud.githubusercontent.com/assets/2883385/12154443/c6811fa6-b4bf-11e5-9a0a-9b2f7b1874fc.png)

You can see that the image above is in 1280x1024, but still very muddy. A tedious workaround is to resize the window to an acceptable size before letting BG do its magic.
