### ISSUE TITLE
Request: portable version

### ISSUE THREAD

**Issue by DAOWAce** [Codeusa/Borderless-Gaming#111]
Well, I see Borderless Gaming finally got updated after a long period of inactivity.

Unfortunately, it's now in an installer and saves its settings to the registry and appdata (though it saved to appdata already if enabling any options, I never needed them and the new version has a lot more options).

I've been running BG all this time from a big tools folder on a RAID array which is shared across multiple OS installs.  All this time it's been a simple extract and run from directory, saving its settings in said directory; basically portable.  Now, to continue using later versions, I need to install it on every single OS, copy folders and export/import registry settings; a lot of work involved.

So, I must now request a portable (zip) version for people like me or those that just want to have portable versions of tools for whatever reason.

Could this please be done?

Alternatively, if someone could give me pointers as to where in the source files the code for saving settings is I could try to change it myself, but as I lack programming knowledge I doubt it I will be successful in my attempt.

**Comment by Kein** [comment]
I support this

**Comment by SwinglesMan** [comment]
Me too. I prefer settings in the app's folder for easier access and reconfiguring. Would be nice to have that option by the program checking to see if it's in the system directory or not before writing to the folder.

**Comment by lainverse** [comment]
Came to open a feature request like this, but it was already opened. ^_^
I'd like to have a portable version too.

**Comment by RaTcHeT302** [comment]
I remember the older BG versions being portable originally.

**Comment by mediocrenoob** [comment]
Is it any closer to being fully portable?

**Comment by notnsane** [comment]
Please don't force installers on users. A portable or zipped version is always better.

**Comment by SiTWulf** [comment]
I want it too!!!
Any New about this?

**Comment by mediocrenoob** [comment]
Any possibility of this still happening?

**Comment by crazy-max** [comment]
I have created a portable version of Borderless Gaming if you want to try : https://portapps.io/app/borderless-gaming-portable/

**Comment by TheMercenary333** [comment]
> I have created a portable version of Borderless Gaming if you want to try : https://portapps.io/app/borderless-gaming-portable/

Link gives error while try to download portable version.

**Comment by crazy-max** [comment]
> > I have created a portable version of Borderless Gaming if you want to try : https://portapps.io/app/borderless-gaming-portable/
> 
> Link gives error while try to download portable version.

Hum indeed there's an issue. Here is the direct download link: https://github.com/portapps/borderless-gaming-portable/releases/download/9.5.6-3/borderless-gaming-portable-win32-9.5.6-3-setup.exe
