### ISSUE TITLE
Not starting with Windows

### ISSUE THREAD

**Issue by jimieo** [Codeusa/Borderless-Gaming#112]
I've got the app set to run at windows startup, but it doesn't seem to want to. I manually put a shortcut in my startup folder and still haven't had it load.

I've edited my shortcut to run as admin as well.

using Windows 8.1

**Comment by psouza4** [comment]
You can't put run-as-administrator (elevated) applications in Startup.  Install the non-administrative version and un-check the shortcut to run as administrator.  There's no workaround for this in Windows 8 or later versions of Windows.
