### ISSUE TITLE
Not working with AI War

### ISSUE THREAD

**Issue by taltamir** [Codeusa/Borderless-Gaming#113]
http://store.steampowered.com/app/40400/
The game, by default, sizes correctly but is off center and does not cover the taskbar.
Borderless gaming actually breaks its sizing, making it a regular maximized window with a border (that flickers every time borderless gaming refreshes)

**Comment by psouza4** [comment]
It sounds like you may be using version 6.5 of Borderless Gaming, which tries to persistently updated borders on targeted windows.  Current versions don't do that and shouldn't constantly flash.

The current version of Borderless Gaming also has options to adjust bounding sizes, auto-max (or not auto-max), etc. so you can make fine-adjustments to location and size.

**Comment by taltamir** [comment]
I am not using 6.5, I am using 7.9
