### ISSUE TITLE
Issue with app that has different window title each launch

### ISSUE THREAD

**Issue by Peppe-KSP** [Codeusa/Borderless-Gaming#114]
Terraria has a random window title each launch -- like:
Terraria:  XXXX
Terraria:  YYYY
Terraria:  ZZZZ

I was using borderless gaming 6.5 and it would work with one favorite entry.  Updated to latest version and it looks like the method to match favorites changed to be window specific rather than process/exe or whatever was used before.
Anyway to have a wildcard search for a title?  Like Terraria* or option to match by the old method?

**Comment by psouza4** [comment]
Right-click the program from the left list and choose to Add to Favorites -> By Process (not window title).

**Comment by Peppe-KSP** [comment]
Thank you that does it!

**Comment by psouza4** [comment]
Glad to hear it. :)
