### ISSUE TITLE
Not working with Test Drive Unlimited 2

### ISSUE THREAD

**Issue by lonerunner** [Codeusa/Borderless-Gaming#115]
It doesn't make it borderless. I tried few variations, exiting the game than start it again, start application after the game, restarting computer after app install, etc... but none of them worked.

I am also using windows 8.1 64bit.

**Comment by psouza4** [comment]
Not all games are compatible.  Is Test Drive Unlimited 2 using Unreal Engine?

**Comment by lonerunner** [comment]
It's custom built engine by Atari or Eden games, the game doesn't support actually fullscreen or window mode option in the game, but you can hit Alt+Enter to switch between fullscreen and window mode.

**Comment by madpew** [comment]
I can confirm this working with an earlier version of BG (around 6.5?). I used it to span TDU2 across 3 screens. Can't test current version as I don't have TDU2 installed at the moment and I'm not really using BG anymore.

**Comment by lonerunner** [comment]
That's the similar reason i want to play the game in borderless windowed mode, so i can switch the game window to my tv as window don't allow fullscreen on second tv.

Maybe it is not working because i am on windows 8, or because i am runing a game through a steam i forgot to mention that. I will test with a few older installations later as i am not on the pc where i have the game installed now.

**Comment by lonerunner** [comment]
I can confirm, it works with version 6.5, i tried other versions from newest and down, and 6.5 version is the first one where it worked. So basically since version 7 it doesn't work anymore.

But anyway since it works with version 6.5 now i can move the game to my TV and enjoy playing it borderless. Thanks for the app :)

**Comment by psouza4** [comment]
Turn off auto-maximize in your favorites (7.x).  Some games auto-switch to
full screen with that toggle on.

On Sun, Mar 22, 2015 at 8:07 PM, lonerunner <notifications@github.com>
wrote:

> I can confirm, it works with version 6.5, i tried other versions from
> newest and down, and 6.5 version is the first one where it worked. So
> basically since version 7 it doesn't work anymore.
>
> But anyway since it works with version 6.5 now i can move the game to my
> TV and enjoy playing it borderless. Thanks for the app :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Codeusa/Borderless-Gaming/issues/115#issuecomment-84750275>
> .
>



-- 
-Pete
