### ISSUE TITLE
Not Working Properly in Crysis 2

### ISSUE THREAD

**Issue by skycyclepilot** [Codeusa/Borderless-Gaming#116]
Perhaps this has something to do with the fact that I'm running a Samsung UHD monitor - 3840 X 2160 monitor...  The program works, but the mouse calibration is about 2" off.  The pointer is 2" above where it should be.

**Comment by Maistho** [comment]
I had this problem whem I didn't run the game at the native resolution. If you can make sure to select the correct resolution for your screen in the game, you should be fine.

**Comment by skycyclepilot** [comment]
My monitor's native resolution is 2160p.  My video card is a GTX970, which
doesn't have the horsepower to play modern games at that resolution.  I
have to change the Windows resolution to 1080p or 1440p, then launch the
game at the same resolution - a pain, but Borderless Gaming does work if I
do that.

Thanks for the reply.

On Thursday, July 9, 2015, Gustav Bylund <notifications@github.com> wrote:

> I had this problem whem I didn't run the game at the native resolution. If
> you can make sure to select the correct resolution for your screen in the
> game, you should be fine.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Codeusa/Borderless-Gaming/issues/116#issuecomment-119822271>
> .
>


-- 
*"Nothing Is Enough for the Man to Whom Enough Is Too Little" - Epicurus*
