### ISSUE TITLE
Request: render black background behind game window

### ISSUE THREAD

**Issue by Keith94** [Codeusa/Borderless-Gaming#117]
It would be useful to have when playing games at custom resolutions and such, so it looks more fullscreen-like.

**Comment by Keith94** [comment]
Found a little [workaround](http://steamcommunity.com/groups/WindowedBorderlessGaming/discussions/0/613939841534076028/) for this purpose. Not ideal for task switching though.
Still, it would be nice if Borderless Gaming had this as a per-game option or something.

**Comment by Codeusa** [comment]
So you want the ability to the game to have a black window around it?

**Comment by Keith94** [comment]
Yeah, so the desktop is blacked out behind the game. Mainly for 4:3 games, so it looks like fullscreen mode while playing.

**Comment by Codeusa** [comment]
I can do this, but won't be aware of how it will deal with offsets. I'll
post a test version here soonish

**Comment by hauzer** [comment]
This would be great.

**Comment by psouza4** [comment]
Working on implementing a solution for this currently.

**Comment by SalamiArmy** [comment]
I'd like this feature too, please advise when you need beta testers :D

**Comment by Jiia** [comment]
A workaround would be to do this when launching a game:
- Minimize all other windows
- Set taskbar to autohide
- Set windows wallpaper to black

And then revert the changes after the game closes.

**Comment by Xemiru** [comment]
Anything on this?

**Comment by SalamiArmy** [comment]
I'm checking in after a year. Still nothing hey...

**Comment by Keith94** [comment]
I don't know if this helps, but this open-source program can add black bars around a window: https://sourceforge.net/p/mrhyde/code/ci/master/tree/

**Comment by Kangaroux** [comment]
Any updates on this? It would be great to have for older games.

**Comment by Keith94** [comment]
Nope. There hasn't been any interest since the _three years ago_ that I posted this.

**Comment by diegoesp** [comment]
+1 :)

**Comment by SalamiArmy** [comment]
I, for one, am interested in this.

**Comment by eturquin** [comment]
+1

**Comment by Xevion** [comment]
Just found a game I wanted to play with a small window and 4:3 aspect ratio. Borderless Gaming failed here, +1!

**Comment by Geniusssmit** [comment]
> Just found a game I wanted to play with a small window and 4:3 aspect ratio. Borderless Gaming failed here, +1!

+1, any solutions yet?

**Comment by SzieberthAdam** [comment]
+1

**Comment by Keith94** [comment]
I recommend anyone looking for this behavior to try out [IntergerScaler](https://tanalin.com/en/projects/integer-scaler/)

>Features
>**Ability to use custom background color instead of black (the -bg option).**

**Comment by Keith94** [comment]
You're right! Edited by comment 😄

**Comment by genderneutralnoun** [comment]
IntegerScaler doesn't work for my purposes since alt-tabbing out of a scaled game keeps the scaling. The whole reason I use Borderless Gaming is to get around games that bug out or cause issues when you alt-tab out of the native fullscreen... plus other games that don't even have a native fullscreen. Please continue working on this.

**Comment by BjornTjockPals** [comment]
It would be really useful if finally implemented

**Comment by zidokobik** [comment]
any updates ?

**Comment by genderneutralnoun** [comment]
This is not completed. Regardless of whether the original commenter found a solution that works for them, the function still is not in Borderless Gaming itself (that I am aware of). Please reopen.

**Comment by BadisG** [comment]
I'm upping this thread, there should be a feature to get black borders I agree with that
