### ISSUE TITLE
Request: match window class as well to avoid resizing splash screens

### ISSUE THREAD

**Issue by akumenon** [Codeusa/Borderless-Gaming#118]
Hello, 

First of all, thank you for this great application!
I'm facing as issue where Borderless Gaming resizes splash screens of games rather than the actual game window (which always shows up after the splash screen). There is currently no way for it distinguish between various window classes of an application. I'm testing this on Super Smash Land (a free game with a splash screen) Maybe when the application matches a window to resize, it should also match window class. Just my two cents on this. 

Thank you for your hard work!

**Comment by psouza4** [comment]
Trying to consider the best way to do this as matching by class seems like one of those things that few users will understand and know hot to work with.  Does the window caption/title not change between splash and game windows?

**Comment by akumenon** [comment]
I agree, it may be hard to understand for a layman, but unfortunately the titles don't always change and there seems to be no other way to differentiate between the 2 windows (unless I'm missing something)

I tried it with another game called Altitude, where the situation is the same i.e. the splash screen and the main game window have the same title but in this case, the splash screen changes position to (0,0) but without expanding, and when the main window loads, it repositions and stretches out fine. I'm inclined to think that this is because it loaded quickly enough to still be within the time duration during which Borderless Gaming tries to process the application. While I'm glad it worked, but I don't think it would have if the load time was longer.
