### ISSUE TITLE
"[No Size]" as default option

### ISSUE THREAD

**Issue by OSV96** [Codeusa/Borderless-Gaming#120]
Hi,

First of thanks for making this program and sharing it. It really is very useful.
But I was wondering if there is any chance of you adding the ability to set either "[No Size]" or "[Max]" as default option.

The reason I'm asking is because I play a game where I only want the border removed but not the window resized. 

But the Game opens a new process for every new map you choose, because of this B-G does not remove the border anymore once I'm playing.
And when I try to use the Global-Hotkey the window gets maxed.

There are literally thousands of maps for this game and you only play a couple minutes on each, so adding them all to the favorites is impossible and turning of automatic processing every time to prevent the resizing takes a to much time.

I'd really appreciate it if you considered this. If its not too bothersome :D 

Thanks a Lot

**Comment by psouza4** [comment]
Try setting your favorite by process name, not window title

**Comment by OSV96** [comment]
Wow... I feel pretty stupid for missing that option.

Thanks A Lot and sorry about wasting your time.

**Comment by psouza4** [comment]
No worries -- glad that worked out for you

On Fri, May 1, 2015 at 3:50 PM, OSV96 <notifications@github.com> wrote:

> Wow... I feel pretty stupid for missing that option.
>
> Thanks A Lot and sorry about wasting your time.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Codeusa/Borderless-Gaming/issues/120#issuecomment-98248641>
> .
>



-- 
-Pete
