### ISSUE TITLE
Crash on Start 7.9 & 7.9 Admin

### ISSUE THREAD

**Issue by reikonyx** [Codeusa/Borderless-Gaming#121]
It just stop responding when i start it. Older versions still work though. IDK whats up.

Windows 8.1
i5 4690k
250 ssd
16gb ram
gtx 980

**Comment by psouza4** [comment]
Try running it elevated (admin) vs. non-elevated, etc.  Sorry, but a
"doesn't work" report out of many thousands of users isn't very helpful ;)

On Fri, May 8, 2015 at 6:18 PM, reikonyx <notifications@github.com> wrote:

> It just stop responding when i start it. Older versions still work though.
> IDK whats up.
>
> Windows 8.1
> i5 4690k
> 250 ssd
> 16gb ram
> gtx 980
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Codeusa/Borderless-Gaming/issues/121>.
>



-- 
-Pete

**Comment by reikonyx** [comment]
I understand, but it gives no error message just stops responding. Ive
tried elivated non elivated admin non admin and all combinations therin.
6.5 works fine but 7.5 and up always stops responding. Is there a log i can
look for anywhere?

**Comment by psouza4** [comment]
Abandoning this issue with the assumption that this is an odd environmental issue with @reikonyx 's system.  Wish it weren't the case, but nobody else reporting an issue and no reproducible data makes it impossible to debug anyway.
