### ISSUE TITLE
Hangs upon startup

### ISSUE THREAD

**Issue by dijicaek** [Codeusa/Borderless-Gaming#122]
After launching (elevated or not), the application hangs and Windows reports it as Not Responding.

Happens with 7.5 through 7.9. 6.5 works, though.
OS is Windows 8.1 64-bit.

**Comment by psouza4** [comment]
I last compiled 7.9 on Win 8.1 x64 Pro.  OS isn't the issue, for sure.

May be an application in the background that hangs it.  If you're a
developer, debug the source with Visual Studio and find out what it's doing
by pausing execution once it hangs.

On Sat, May 9, 2015 at 12:11 AM, dijicaek <notifications@github.com> wrote:

> After launching (elevated or not), the application hangs and Windows
> reports it as Not Responding.
>
> Happens with 7.5 through 7.9. 6.5 works, though.
> OS is Windows 8.1 64-bit.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Codeusa/Borderless-Gaming/issues/122>.
>



-- 
-Pete

**Comment by Codeusa** [comment]
I need to buy you a coffee @psouza4 for all this maintaining you do.

**Comment by dijicaek** [comment]
Yeah I'll try closing things and seeing if it starts working.
Oh and this is where it pauses at in VS:
    BorderlessGaming.exe!BorderlessGaming.WindowsAPI.Native.GetWindowTitle(System.IntPtr hWnd) Line 168	C#
Relevant line: ```int length = (int)Native.SendMessage(hWnd, Native.WM_GETTEXTLENGTH, IntPtr.Zero, IntPtr.Zero);```

**Comment by psouza4** [comment]
That's good!

If you can identify the process (by hWND -- there's some native methods
available in the source for that), you can find out which process is
hanging when the Win32 API asks for its title text!

On Sat, May 9, 2015 at 1:34 AM, dijicaek <notifications@github.com> wrote:

> Yeah I'll try closing things and seeing if it starts working.
> Oh and this is where it pauses at in VS:
> BorderlessGaming.exe!BorderlessGaming.WindowsAPI.Native.GetWindowTitle(System.IntPtr
> hWnd) Line 168 C#
> Relevant line: int length = (int)Native.SendMessage(hWnd,
> Native.WM_GETTEXTLENGTH, IntPtr.Zero, IntPtr.Zero);
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Codeusa/Borderless-Gaming/issues/122#issuecomment-100441144>
> .
>



-- 
-Pete

**Comment by dijicaek** [comment]
Sorry for the lack of response, been super busy.
Anyhows, I had to reboot for a Windows update and the problem stopped so I have no idea what application was causing it.

If it crops up again I'll be sure to look into it further though!
