### ISSUE TITLE
Not working with Counter-Strike: Global Offensive

### ISSUE THREAD

**Issue by RixzZ** [Codeusa/Borderless-Gaming#123]
I'm trying to use 7.9 version (both non-admin & admin) but it is not working. CSGO also has it's own borderless mode, but I'm trying to use it with this program because maybe I could still use Shadowplay (which only works in fullscreen games) to record it.

I tried adding the game by name and by process but nothing happens. If I press the "Make borderless" button nothing happens. If I close the game after adding it to favorites, game is still in fullscreen in the next start.

I alse tried with the shortcut Win+F6 from inside the game, same result.

Is this because CSGO has it's own borderless or I'm doing something wrong?

Thanks in advance.

**Comment by Synopis** [comment]
CS:GO has it's own borderless option. There's no need to use BG with it.

**Comment by RixzZ** [comment]
I already said that in my post and I explained why I'm trying to use BG with it.

**Comment by RixzZ** [comment]
It tried with some other games (Dragon Ball Xenoverse, Dying Light) but doesn't work with them. It doesn't work at all with anything.

**Comment by psouza4** [comment]
Try using the admin version.  Depending on your OS or UAC settings,
Borderless Gaming may not be allowed to touch other processes, especially
if they themselves are elevated.

On Sat, May 9, 2015 at 7:29 AM, Rubén Pérez <notifications@github.com>
wrote:

> It tried with some other games (Dragon Ball Xenoverse, Dying Light) but
> doesn't work with them. It doesn't work at all with anything.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Codeusa/Borderless-Gaming/issues/123#issuecomment-100484690>
> .
>



-- 
-Pete

**Comment by madpew** [comment]
Since the question is about using shadowplay it is worth noting that you can enable "Allow Desktop Capture" in the shadowplay-options to allow capturing non-fullscreen/borderless games.
