### ISSUE TITLE
Unverified Problem: not working with Metal Gear Solid 2: Substance

### ISSUE THREAD

**Issue by Tmplt** [Codeusa/Borderless-Gaming#124]
Using Borderless-Gaming with `mgs2_sse.exe` or `mgs2.exe` does not work. While the game's sound can still be heard, its window turns black and programs floating above it have the following effect:

![Result](https://i.imgur.com/W7PnizQ.png)

**Comment by psouza4** [comment]
Did you try disabling auto-maximize for that Favorite?

**Comment by psouza4** [comment]
No reply in four days -- assuming this answer resolved your issue.
