### ISSUE TITLE
Endless space not working

### ISSUE THREAD

**Issue by taltamir** [Codeusa/Borderless-Gaming#126]
Endless space doesn't work with borderless-gaming 7.9... usually
What happens with the endless games (endless legend, endless space, and endless dungeon) is that after borderless gaming makes it borderless, the game itself tries to reset the window size. this continues back and forth a couple of times in quick succession until the game gives up and you get a proper borderless window.
In endless legend you have to quickly skip the cutscenes at the begining to make sure its the game that gives up. or you might need to remove and then readd it to the list in the borderless gaming interface.
for endless space the borderless gaming app always gives up first

**Comment by psouza4** [comment]
Sorry, but no Unreal Engine 3 games are compatible.  As you've observed, games using Unreal Engine 3 will persistently reset border and size properties.

**Comment by taltamir** [comment]
But it is not actually persistent, UE3 gives up on resetting it eventually. The issue is that on this one game borderless gaming gives up before the engine does, while on its brother title the UE3 engine gives up first and lets me play in borderless glory

**Comment by psouza4** [comment]
How many tries does it take?

**Comment by taltamir** [comment]
In the game called "endless legends" it takes 4 attempts (3 failures followed by 1 success), during the initial ads showed on game run it will reset the attempt count after every one, so you have to click through them rapidly to get it to succeed, but if you do then it will reliably do the 4 attempts to succeed thing.

In endless space, it fails 4 times and then borderless gaming stops trying, I don't know how many times the game would have tried if borderless gaming didn't stop trying.
