### ISSUE TITLE
Automatic startup for admin version

### ISSUE THREAD

**Issue by mirhl** [Codeusa/Borderless-Gaming#127]
Yes, I know it has been asked before. 

But have you ever tried to make use of a [windows service](http://stackoverflow.com/questions/5427673/how-to-run-a-program-automatically-as-admin-on-windows-startup#answer-5427742) or the [task scheduler](https://msdn.microsoft.com/en-us/library/bb530410.aspx#vistauac_topic6c)?

**Comment by psouza4** [comment]
In general, those types of services do not have Interact-With-Desktop
permissions, which is required.

On Sun, Jun 14, 2015 at 4:05 AM, mirhl <notifications@github.com> wrote:

> Yes, I know it has been asked before.
>
> But have you ever tried to make use of a windows service
> <http://stackoverflow.com/questions/5427673/how-to-run-a-program-automatically-as-admin-on-windows-startup#answer-5427742>
> or the task scheduler
> <https://msdn.microsoft.com/en-us/library/bb530410.aspx#vistauac_topic6c>?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Codeusa/Borderless-Gaming/issues/127>.
>



-- 
-Pete

**Comment by mirhl** [comment]
I guess it should be possible to [separate](https://msdn.microsoft.com/en-us/library/windows/desktop/ms683502%28v=vs.85%29.aspx#interacting_with_a_user_from_a_service_indirectly) the service from the "frontend"

Otherwise [this](http://asprosys.blogspot.com/2009/03/allow-service-to-interact-with-desktop.html) may be another option

**Comment by psouza4** [comment]
You can, but then what would be the point of having a service at all? ;)

On Sun, Jun 14, 2015 at 10:47 AM, mirhl <notifications@github.com> wrote:

> I guess it should be possible to separate
> <https://msdn.microsoft.com/en-us/library/windows/desktop/ms683502%28v=vs.85%29.aspx#interacting_with_a_user_from_a_service_indirectly>
> the service from the "frontend"
>
> Otherwise this
> <http://asprosys.blogspot.com/2009/03/allow-service-to-interact-with-desktop.html>
> may be another option
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Codeusa/Borderless-Gaming/issues/127#issuecomment-111848860>
> .
>



-- 
-Pete

**Comment by mirhl** [comment]
Well, I don't actually know how bg infrastructure work. :p
Still, the idea I had in mind was something like Firefox auto-updater. 

After reading something about security concerns, I guess that the point of having a service is it doing the work in background (which wouldn't be bad considering many time I forgot to start it)
