### ISSUE TITLE
[Bug] Aspect Ratio does not stick to 16:9

### ISSUE THREAD

**Issue by wilflare** [Codeusa/Borderless-Gaming#128]
I'm using a 16:10 monitor.
When using Borderless-Gaming, the 16:9 game (Legend of Korra) gets stretched to fit the 16:10 screen.
Is there any way to use 16:10 with Black Bars?

**Comment by psouza4** [comment]
There's no way that Borderless Gaming can or will modify games' behavior to
add black bars.  That falls under an entirely new type of program that
overrides graphical rendering, etc.

You can, however, remove the border and keep a fixed size (no
auto-maximize), instead and simply use a black background behind the
program to have a similar effect.

On Sun, Jun 14, 2015 at 10:09 AM, wilflare <notifications@github.com> wrote:

> I'm using a 16:10 monitor.
> When using Borderless-Gaming, the 16:9 game (Legend of Korra) gets
> stretched to fit the 16:10 screen.
> Is there any way to use 16:10 with Black Bars?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Codeusa/Borderless-Gaming/issues/128>.
>



-- 
-Pete

**Comment by wilflare** [comment]
thanks for the clarification! hmm how do I do what you suggested using Borderless gaming?

**Comment by psouza4** [comment]
There's probably quite a few easy ways to get a black screen behind your
game.  The way I do it is by using IrfanView, an image viewing program.

Create a 1x1 pixel image in MS Paint (or any other photo editing program)
of your preferred color and save it somewhere.  Open IrfanView, hit [P] to
go to properties/preferences, click on Full screen/slideshow, click to turn
off "Show text" (at the bottom) and click OK.  Open your 1x1 pixel image,
then hit ENTER to view it full screen.  Play your windowed game on top of
that full screen image to have it act as black bars.

On Sun, Jun 14, 2015 at 10:27 AM, wilflare <notifications@github.com> wrote:

> thanks for the clarification! hmm how do I do what you suggested using
> Borderless gaming?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Codeusa/Borderless-Gaming/issues/128#issuecomment-111845754>
> .
>



-- 
-Pete

**Comment by wilflare** [comment]
I see! thanks :D 
sorry for this very noob question - but I can't seem to reposition my Windowed game :/

**Comment by psouza4** [comment]
Do it in Borderless Gaming.  After adding to your favorites, right-click
the favorite entry for that game and you can adjust the offsets.

On Sun, Jun 14, 2015 at 11:16 AM, wilflare <notifications@github.com> wrote:

> I see! thanks :D
> sorry for this very noob question - but I can't seem to reposition my
> Windowed game :/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Codeusa/Borderless-Gaming/issues/128#issuecomment-111852159>
> .
>



-- 
-Pete

**Comment by wilflare** [comment]
thanks! changed from GeDoSaTo to Borderless-Gaming (GeDoSaTo does it as well... no black bars but I cannot adjust the offset)

any reason why Borderless-Gaming says 0x60-1920x1140 instead of 1920x1080?

and for Borderless-Gaming to work, I need to ensure my game is in Windowed Mode right?
GeDoSaTo says to choose Fullscreen

**Comment by wilflare** [comment]
hi @psouza4 I just tried what you recommended
can I check with you - for Irfanview, does the fullscreen do borderless windowed fullscreen? my taskbar disappears when it's fullscreen

**Comment by psouza4** [comment]
We're working on a built-in solution to adding black bars for cases like these.

See https://github.com/Codeusa/Borderless-Gaming/issues/117

Going to close this one since it's basically a duplicate at this point :)
