### ISSUE TITLE
[Help] Explaining Options

### ISSUE THREAD

**Issue by wilflare** [Codeusa/Borderless-Gaming#129]
Can I just clarify what the following under Tools do?
- Pause Automatic Processing
- Toggle Mouse Cursor Visibility
- Toggle Windows Taskbar Visibility
(at least what's the purpose for them?)

- Add to Favorites via Window Title Text vs Process Binary Name (why?)
- Remove Menus

**Comment by Codeusa** [comment]
- Pauses Automatic processing of favorites 
- Show or hide the mouse cursor 
- Hide the taskbar or show it
- Because some applications don't have a window title (Killing floor)
- Remove menus of an application
