### ISSUE TITLE
Terraria Changes its Title Every Time so Putting it in Favorites Doesn't Work Well

### ISSUE THREAD

**Issue by throwaway1012** [Codeusa/Borderless-Gaming#131]
The Program works for putting Terraria in borderless mode manually, but as Terraria's title changes every time it is opened, fails to automatically put the game in borderless mode when the game is put in favorites

**Comment by Codeusa** [comment]
Use the executable name.

**Comment by psouza4** [comment]
Right-click option to add to favorites by process name, instead of
application title.

On Sat, Jul 11, 2015 at 8:32 PM, Andrew Sampson <notifications@github.com>
wrote:

> Use the executable name.
>
> On Sat, Jul 11, 2015 at 5:48 PM, throwaway1012 <notifications@github.com>
> wrote:
>
> > The Program works for putting Terraria in borderless mode manually, but
> as
> > Terraria's title changes every time it is opened, fails to automatically
> > put the game in borderless mode when the game is put in favorites
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/Codeusa/Borderless-Gaming/issues/131>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Codeusa/Borderless-Gaming/issues/131#issuecomment-120680625>
> .
>



-- 
-Pete
