### ISSUE TITLE
Exception Error When Opening BG

### ISSUE THREAD

**Issue by siirus09** [Codeusa/Borderless-Gaming#132]
Windows 10, Build 10166
GTX 970, Latest Nvidia Drivers

Now I know Windows 10 may or may not be supported fully yet, but I used to be able to run Borderless Gaming without issue but on one fine day when I tried to open BG again, I got the following error dialog:
http://www.evernote.com/shard/s335/sh/1c5f1e8a-cf35-415c-b5e1-32a9f6f8db97/72cca18abbc7c2f14f55eb452008bc21

This was back since Windows 10 Build 10142 and since then I still cant get it to run even after uninstalling it, cleaning out every registry and file I found, then reinstalling. Here is the full error message that it is logging:

http://pastebin.com/RvEDv5b9

**Comment by psouza4** [comment]
Sounds like you have a favorites file from an incompatible version of BG
still.  Delete it.

**Comment by siirus09** [comment]
That worked. I can't imagine how I missed deleting that file. Thank you.

**Comment by psouza4** [comment]
No problem!

On Sun, Jul 19, 2015 at 12:33 PM, siirus09 <notifications@github.com> wrote:

> That worked. I can't imagine how I missed deleting that file. Thank you.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Codeusa/Borderless-Gaming/issues/132#issuecomment-122693241>
> .
>



-- 
-Pete
