### ISSUE TITLE
Not working with Unreal Engine 3 games

### ISSUE THREAD

**Issue by navihawk** [Codeusa/Borderless-Gaming#135]
For a fair part of my unreal engine 3 based games, BG 8.1 currently doesn't make them borderless fullscreen, and leaves them in a maximized regular window. This includes Primal Carnage and another game

**Comment by psouza4** [comment]
This is a known issue that can't be resolved specifically because of how
Unreal 3 is designed.

**Comment by psouza4** [comment]
Also: be sure to report incompatible games here:

https://steamcommunity.com/app/388080/discussions/2/
