### ISSUE TITLE
Request: add automatic mouse lock during game focus

### ISSUE THREAD

**Issue by Caesim** [Codeusa/Borderless-Gaming#137]
Some games like Mount&Blade don't capture the mouse correctly when in windowed mode, so the mouse sometimes moves out to my secondary monitor and I can accidentally do something to other programs or I can lose focus on the game window. 

It would be great, if  this program had an option to capture the mouse until alt+tab, so I wouldn't have to use another program to do it.

**Comment by madpew** [comment]
You can activate the Mouse-Lock hotkey in the menu (options -> Use MouseLock Hotkey) and press scrolllock to enable/disable it.

**Comment by martinsstikuts** [comment]
Oh, didn't notice that, but regardless it would be great, if it was automated and I wouldn't have to think about doing it manually every time (that's the whole reason I use this program - automation). Also for some reason the hotkeys for these background programs stop working after it has been running for a while.

**Comment by psouza4** [comment]
Automatic mouse-lock can be added to a game's options.  We'll look into adding that!

**Comment by sneaky4oe** [comment]
Still need this. Now even admin permission won't allow me to lock my cursor inside a game!11

**Comment by sneaky4oe** [comment]
http://www.snakebytestudios.com/projects/apps/cursor-lock/
THIS is a temporary solution for us, guys, till they don't fix lock back.

**Comment by FoldZero** [comment]
This would be a great addition. I keep forgeting to lock the cursor and end up clicking in a seperate window to the one i have borderless.
