### ISSUE TITLE
Notification icon not changed with ver. 8.1

### ISSUE THREAD

**Issue by sloshy** [Codeusa/Borderless-Gaming#138]
After reading the release notes I noticed there was a new program icon, but it does not appear to be changed for me in the notification area. Not sure if this is a bug for me or for the program.

As the below image shows, the image for the notification area hasn't changed. This is after performing an icon cache refresh just to be safe via this method: http://superuser.com/a/499083

![6yprkri](https://cloud.githubusercontent.com/assets/427237/8874349/a83906c0-31d5-11e5-8f5d-e2b6aef6f8a5.png)

**Comment by psbj** [comment]
The icon in the "about" window is not changed either.

To be honest I don't like the new icon though.

**Comment by psouza4** [comment]
The icon being consistent should be fixed, but perhaps @dmxt could look at 64 and 128-pixel versions of the icon that are more consistent with the new theme, adding a window frame to the icon and arrows like in the Steam promo art.
