### ISSUE TITLE
No Minecraft Support

### ISSUE THREAD

**Issue by OMGHannahMontana** [Codeusa/Borderless-Gaming#140]
I hope I'm in the right place for this. I bought this off steam since nothing beats borderless gaming. I was disappointed that MC is an application that won't go borderless. Just wanted to bring awareness in case this issue hasn't been brought up before.

**Comment by Bjarno** [comment]
I tried it yesterday on the latest vanilla Minecraft and had no problems. You should select the game itself, NOT the launcher. Furthermore, you should disable fullscreen in Minecraft itself before starting it with Borderless Gaming. After loading, it should automatically switch to borderless fullscreen.

**Comment by psouza4** [comment]
There are lots, and lots, and lots of launchers for Minecraft including
Curse, ATL, FTB, etc.  But they all essentially launch the game via Java
binaries and should thus all work.  I've tested several myself and they all
work fine here, so I would advise you take a look at Andrew's suggestion
and make sure you are trying to use it on the correct game window.

On Fri, Jul 24, 2015 at 9:36 AM, OMGHannahMontana <notifications@github.com>
wrote:

> I hope I'm in the right place for this. I bought this off steam since
> nothing beats borderless gaming. I was disappointed that MC is an
> application that won't go borderless. Just wanted to bring awareness in
> case this issue hasn't been brought up before.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Codeusa/Borderless-Gaming/issues/140>.
>



-- 
-Pete

**Comment by chitown3** [comment]
This Does work for Minecraft, problem is whenever I use this app to run MC borderless windowed my game lags a bit. Not sure if lag is the correct term for this but lets just say it's not buttery smooth. It seems to work ok for other games. When I play MC I have to resort to using another borderless windowed app that works perfect.

**Comment by Berttholio** [comment]
chitown3 I have the same issue, I love this application but something strange happens to it when running minecraft. And as you said using a different borderless app the problem is not there.

**Comment by psouza4** [comment]
Try disabling auto-maximize for Minecraft in your Borderless Gaming
Favorites list and then try launching Minecraft again.

On Fri, Jul 24, 2015 at 6:26 PM, Berttholio <notifications@github.com>
wrote:

> chitown3 I have the same issue, I love this application but something
> strange happens to it when running minecraft. And as you said using a
> different borderless app the problem is not there.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Codeusa/Borderless-Gaming/issues/140#issuecomment-124776089>
> .
>



-- 
-Pete

**Comment by Berttholio** [comment]
That actually seemed to do it, by using my hotkey and not auto maximize it seems to run smooth,  Thanks!

**Comment by psouza4** [comment]
Fantastic to hear!

On Sat, Jul 25, 2015 at 7:43 AM, Berttholio <notifications@github.com>
wrote:

> That actually seemed to do it, by using my hotkey and not auto maximize it
> seems to run smooth, Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Codeusa/Borderless-Gaming/issues/140#issuecomment-124847850>
> .
>



-- 
-Pete

**Comment by chitown3** [comment]
That seemed to help, Thanks psouza4!
