### ISSUE TITLE
Version 8.1 Problem

### ISSUE THREAD

**Issue by DustInLint** [Codeusa/Borderless-Gaming#141]
I'm not sure if it's something that I'm doing wrong, or maybe just the compatibility with the games that I'm using, but whenever I try to make one of my bordered games into borderless windowed games, it always tries to stretch the game across all three of my monitors, instead of the one that I want it to be on.  The games that I have tried thus far are Nuclear Throne in windowed mode, as well as Dungeon Souls in windowed mode.

**Comment by psouza4** [comment]
Turn off automatic processing (temporarily) and add the game to your
favorites list if you haven't already.

Now right-click on the favorite and turn off the maximize feature.  You may
need to set bounds manually so it knows which monitor to fill to instead of
the entire available surface.

On Fri, Jul 24, 2015 at 2:15 PM, DustInLint <notifications@github.com>
wrote:

> I'm not sure if it's something that I'm doing wrong, or maybe just the
> compatibility with the games that I'm using, but whenever I try to make one
> of my bordered games into borderless windowed games, it always tries to
> stretch the game across all three of my monitors, instead of the one that I
> want it to be on. The games that I have tried thus far are Nuclear Throne
> in windowed mode, as well as Dungeon Souls in windowed mode.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Codeusa/Borderless-Gaming/issues/141>.
>



-- 
-Pete

**Comment by DustInLint** [comment]
Thanks @psouza4! I'll try that and update whether this fixes my problem or not.

**Comment by DustInLint** [comment]
How do I set up the bounds manually for the monitor that I want to use?  I'm not sure if it'll help, but it's the left monitor of three, and the resolution is set for 1920x1080.

**Comment by psouza4** [comment]
Right-click the favorite and choose to set bounds.  You'll be prompted if you want to enter numbers manually or if you want to draw on the screen to select an area.  Choose to select an area and draw it wherever you want it to be.  Don't forget when you're all done to turn back on automatic favorite processing.

**Comment by DustInLint** [comment]
@psouza4 Unfortunately, it still seems to be wanting to stretch across all three of the screens, even after setting the bounds.  Is it possible that it simply is just a compatibility issue with that game that I'm trying, or that it is something that I'm doing wrong on my end still?

**Comment by psouza4** [comment]
Likely a setting you still have wrong.  Did you take off auto maximize?  Or
perhaps have multiple favorites that could be affecting the game?

**Comment by DustInLint** [comment]
@psouza4 I took off auto maximize, and I tried both games separately, as being the only only favorite listed.

**Comment by psouza4** [comment]
Try something simple like Notepad or something in case those games are
oddly incompatible.

**Comment by DustInLint** [comment]
@psouza4 It must be a compatibility issue with those games, as like you said, when I tried doing that with notepad, it worked.

**Comment by psouza4** [comment]
Okay so that gets us a step further.  I would check some other games and
see what games do work and don't.  I know that basically all Unreal Engine
3 games don't work.

**Comment by DustInLint** [comment]
@psouza4  A few other games that I have tried this with with both success and failure: Binding of Isaac: Rebirth (success), Crawl (success), Dungeon of the Endless (success), Chasm (failure), Darkest Dungeon (failure).  As you can see, I do have a theme for games I enjoy playing as well. :p
