### ISSUE TITLE
Terraria not working

### ISSUE THREAD

**Issue by TM0NEY46** [Codeusa/Borderless-Gaming#142]
The program sees Terraria as an application.  When I submit the program as a favorite it goes full screen but when I alt-tab or click off the game it minimizes to taskbar immediately. I have tried adding the game by process and it does the same thing.  The add program by window title will not work as window title is random each launch.  Additionally I am using Borderless gaming app on Windows 10 preview 64 bit through the Steam client.  Let me know if you need any more information.  Thanks for this awesome program and for your support.

**Comment by psouza4** [comment]
Have you tried changing the properties of Terraria in Borderless Gaming to
remove Auto-Maximize?  That may help.

On Fri, Jul 24, 2015 at 7:04 PM, Jonathan Tanner Bradshaw <
notifications@github.com> wrote:

> The program sees Terraria as an application. When I submit the program as
> a favorite it goes full screen but when I alt-tab or click off the game it
> minimizes to taskbar immediately. I have tried adding the game by process
> and it does the same thing. The add program by window title will not work
> as window title is random each launch. Additionally I am using Borderless
> gaming app on Windows 10 preview 64 bit through the Steam client. Let me
> know if you need any more information. Thanks for this awesome program and
> for your support.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Codeusa/Borderless-Gaming/issues/142>.
>



-- 
-Pete

**Comment by TM0NEY46** [comment]
Hmm just tried it still minimizes the same when I click off or alt out of game, but I do think it does make the game work more efficiently even if it does minimize window.  It may be due to Terraria's recent update more than your program though as Terraria just had a major update a few weeks ago that may have lingering glitches.

**Comment by psouza4** [comment]
Yeah, unfortunately it's not the design or intent of Borderless Gaming to
control other application's behaviors.  If they choose to minimize
automatically when they lose focus, we can't capture and block that event
(and doing so would cause all kids of VAC secure issues anyway).  You might
want to reach out to the Terraria development team about the game's
behavior when tabbing away in windowed mode.

On Fri, Jul 24, 2015 at 8:02 PM, Jonathan Tanner Bradshaw <
notifications@github.com> wrote:

> Hmm just tried it still minimizes the same when I click off or alt out of
> game, but I do think it does make the game work more efficiently even if it
> does minimize window. It may be due to Terraria's recent update more than
> your program though as Terraria just had a major update a few weeks ago
> that may have lingering glitches.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Codeusa/Borderless-Gaming/issues/142#issuecomment-124787386>
> .
>



-- 
-Pete

**Comment by TM0NEY46** [comment]
Thanks for the general feedback and quick responses.  Your program is awesome regardless and I appreciate your work.  This issue is closed as I believe you are right and it is more on game developers side than yours.
