### ISSUE TITLE
Tabletop Simulator

### ISSUE THREAD

**Issue by Putm20** [Codeusa/Borderless-Gaming#143]
Running Tabletop Simulator, I can tell it's trying so very hard to get rid of the borders for me, but no luck yet.

I'd love support for Tabletop Simulator, so I just thought I'd throw that out there. As it doesn't work yet.
Great program by the way, absolutely love it!

(Running Version 8.1)

**Comment by psouza4** [comment]
If Tabletop Simulator is using the newest Unreal Engine (v3), then it won't
be compatible.  Games built with the recent version of the Unreal Engine
prevent window border and size modification outside of the application by
persistently monitoring for and managing their window properties.  It's not
something Borderless Gaming can be compatible with without modifying and/or
blocking application behavior, which would be in violation of VAC for Steam
(not to mention a nightmare to implement and support).

Let us know if Tabletop Simulator is not an Unreal Engine game.

On Sat, Jul 25, 2015 at 12:29 AM, Putm20 <notifications@github.com> wrote:

> Running Tabletop Simulator, I can tell it's trying so very hard to get rid
> of the borders for me, but no luck yet.
>
> I'd love support for Tabletop Simulator, so I just thought I'd throw that
> out there. As it doesn't work yet.
> Great program by the way, absolutely love it!
>
> (Running Version 8.1)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Codeusa/Borderless-Gaming/issues/143>.
>



-- 
-Pete

**Comment by psouza4** [comment]
Also: be sure to report incompatible games here:

https://steamcommunity.com/app/388080/discussions/2/
