### ISSUE TITLE
Remove my name and link from the about-info

### ISSUE THREAD

**Issue by madpew** [Codeusa/Borderless-Gaming#144]
Hello Andy,

Since you are now selling this software on steam, and deleting comments when someone points out that you are not the only developer behind this I don't want to be affiliated with this anymore.

It's not a problem that you ARE getting money from this, but it's only fair to point out that there are other contributers as well. Removing such comments (twice!) is a very dickish move.

![comment2](https://cloud.githubusercontent.com/assets/527850/8890117/f4834d9a-32f4-11e5-84e7-0389754cea64.jpg)

**Comment by Codeusa** [comment]
I'm deleting comments because they're uninformed and off topic. Currently me and mostly @psouza4 are the primary maintainers of this project and I offered him money for his support long ago and now that its being sold on Steam I planned fully to reimburse him for his contributions.

**Comment by madpew** [comment]
Offtopic? You can see the quoted post in the image.
So I'm uninformed? Let me clarify:

Did I contribute to Borderless Gaming? yes
Did other people besides you and @psouza4 contribute to Borderless Gaming? yes

Fact is, BG is open source and accepting contributions. So I see nothing wrong about pointing out that you're not the only developer behind this. But it seems you're the one to judge who is a developer and who isn't.
 As I already made clear it's not about the money (noone should expect money when contributing to a free product). Not sure why you wanna try so hard to hide that fact.

Anyways, not much sense arguing with you.
So as requested: Please remove my name and link from the about-info
Thanks

**Comment by Codeusa** [comment]
"Actually you only support one of the devs"

An untrue statement. So yes, uninformed, Borderless Gaming has always had a support button, this is just a more direct method of doing so.

Posting false information such as that detours sales. So yeah, I deleted it.

**Comment by madpew** [comment]
Having a "support us"-button isn't equal to denying other people worked on your project.
Also stating that you offered someone a share doesn't really change the fact that you are getting the revenue. So "actually, you only support one of the devs".

Thank you very much in advance for removing my name and link from the about-info.
