### ISSUE TITLE
Restoring to bordered state requires cascading windows to restore fully

### ISSUE THREAD

**Issue by angryhussord** [Codeusa/Borderless-Gaming#145]
I installed this for the first time today (via the reddit complaint response thread) and tried making something borderless as a test. I tried it first on the Transmission-qt client and it went borderless, it's awesome, I love it! Then I tried to switch it back by clicking the "Attempts to restore a window back to its borderless state" button. It didn't seem to do anything. After a bit more playing around, I left-clicked the taskbar, chose "Cascade Windows" and that got it out of borderless mode. Since I know it'll help, I'm running Windows 10 build 10240 with the security updates and hotfixes as of 7/25/2015 which is reportedly going to be the RTM version.

**Comment by psouza4** [comment]
The restore button isn't a fool-proof method as it's simply trying to take
a before-snapshot of the window properties.  I'd try it out on a few other
windows and see if you experience the same issue.  I haven't had this issue
with my testing (I'm one of the developers and have tested a lot of games
and applications), but I also haven't tested using non-retail versions of
Windows either.  I plan on making a switch to Windows once it is fully
released on retail channels (you never know).  :D

On Sat, Jul 25, 2015 at 10:39 AM, Patrick Hufford <notifications@github.com>
wrote:

> I installed this for the first time today (via the reddit complaint
> response thread) and tried making something borderless as a test. I tried
> it first on the Transmission-qt client and it went borderless, it's
> awesome, I love it! Then I tried to switch it back by clicking the
> "Attempts to restore a window back to its borderless state" button. It
> didn't seem to do anything. After a bit more playing around, I left-clicked
> the taskbar, chose "Cascade Windows" and that got it out of borderless
> mode. Since I know it'll help, I'm running Windows 10 build 10240 with the
> security updates and hotfixes as of 7/25/2015 which is reportedly going to
> be the RTM version.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Codeusa/Borderless-Gaming/issues/145>.
>



-- 
-Pete

**Comment by angryhussord** [comment]
Hey Pete,

I tried with a couple of different games, and I especially like the mouse-lock feature. I suspect the problem is with the Java-qt based Transmission client doing something differently than other native Windows apps and I wasn't finding much out there with the Google-fu. It's working with just about everything else.

**Comment by psouza4** [comment]
It's possible.  Try another Java-based application with menus, like Eclipse
IDE or something perhaps?

On Sat, Jul 25, 2015 at 10:53 AM, Patrick Hufford <notifications@github.com>
wrote:

> Hey Pete,
>
> I tried with a couple of different games, and I especially like the
> mouse-lock feature. I suspect the problem is with the Java-qt based
> Transmission client doing something differently than other native Windows
> apps and I wasn't finding much out there with the Google-fu. It's working
> with just about everything else.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Codeusa/Borderless-Gaming/issues/145#issuecomment-124861662>
> .
>



-- 
-Pete

**Comment by madpew** [comment]
Tested with Eclipse Kepler, working as intended.

**Comment by psouza4** [comment]
Sounds like just an odd quirk with Transmission then.  That's a relief.  Thanks for the update, madpew!
