### ISSUE TITLE
Doesn't work with Unreal Tournament

### ISSUE THREAD

**Issue by soulhunter123** [Codeusa/Borderless-Gaming#146]
(Windows 7)

Alt-tabbing after starting Unreal Tournament results in no mouse pointer being visible and no control over any desktop elements. Sounds etc. from the game are also still active.

**Comment by psouza4** [comment]
Borderless Gaming isn't compatible with Unreal Engine games in general and
the behavior your're describing isn't something Borderless Gaming has
control or influence over, unfortunately.

On Sat, Jul 25, 2015 at 11:05 AM, soulhunter123 <notifications@github.com>
wrote:

> (Windows 7)
>
> Alt-tabbing after starting Unreal Tournament results in no mouse pointer
> being visible and no control over any desktop elements. Sounds etc. from
> the game are also still active.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Codeusa/Borderless-Gaming/issues/146>.
>



-- 
-Pete

**Comment by psouza4** [comment]
Also: be sure to report incompatible games here:

https://steamcommunity.com/app/388080/discussions/2/
