### ISSUE TITLE
Does BG preserve desktop color profile?

### ISSUE THREAD

**Issue by Dol-phin** [Codeusa/Borderless-Gaming#147]
Windows uses the default color profile in fullscreen applications . Many monitors look absolutely terrible right out of the box and I definitely want to use my calibrated settings with games.
More information regarding the subject: https://forums.geforce.com/default/topic/501853/geforce-drivers/nvidia-forever-ignoring-custom-color-profile-support-in-full-screen-games-collaboration-thread-/1/

When running the game in a borderless window using this application, are my calibrated settings in use or reverted back to defaults?

**Comment by psouza4** [comment]
Borderless Gaming has nothing to do with the rendering or graphical layer in applications -- it only adjusts the window properties of applications' windows, including caption and border visibility and window size.  It sounds like the game you were testing with did not like to be modified in that way.

**Comment by Stanzilla** [comment]
Some games adjust gamma when launched in Fullscreen mode, this could be why colors look different to you while using BG.

**Comment by Dol-phin** [comment]
I haven't noticed any issues with the program, this is more of a general question. Does Windows consider the games Borderless Gaming is running in borderless windows as fullscreen or windowed applications? Should the calibrated color profile be in use?

**Comment by psouza4** [comment]
It will still be a windowed application most of the time.  Some games decide to go into full screen mode when forced into a maximized borderless window, but this is rare.  Expect that most of the time, Windows will not adjust your color profile because there should be no resolution change.

**Comment by Dol-phin** [comment]
Ive found at least one incompatible game: Doom 3 with the Absolute HD mod http://www.moddb.com/mods/absolutehd
I can alt+tab to confirm that the color profile is much more brighter.
