### ISSUE TITLE
Conflicts with TeamViewer

### ISSUE THREAD

**Issue by Luxab** [Codeusa/Borderless-Gaming#150]
When TeamViewer is running BG doesn't work with applications.

**Comment by psouza4** [comment]
I use TeamViewer on all my systems and have never had a conflict, so you'll have to be more specific about your issue.

**Comment by Luxab** [comment]
Ok perhaps I was mistaken then, was just having trouble getting it to work with TF2, and once I closed TeamViewer it worked again. Sorry for jumping to conclusions.

**Comment by psouza4** [comment]
Well if you find out anything and have more details, let us know.
