### ISSUE TITLE
Disable Steam Hook (Steam version 8.2) doesn't seem to work on Windows 10

### ISSUE THREAD

**Issue by corrosivefrost** [Codeusa/Borderless-Gaming#151]
Borderless Gaming 8.2 isn't disabling the steam hook properly on win10 (x64).
Even with the Tools > Disable Steam Hook checked, when I start the software, Steam shows me as in application Borderless Gaming.

**Comment by psouza4** [comment]
There isn't an 8.2 release for Steam yet, we know.  Once we release 8.2 for use with the Steam platform, we'll push it to the steam distribution network so it will automatically update.

**Comment by corrosivefrost** [comment]
Steam version: 8.2.20715.805

**Comment by Codeusa** [comment]
It works fun, stop launching it through Steam and launch it directly from the folder.
