### ISSUE TITLE
Possible incompatibility with game Orion:Prelude?

### ISSUE THREAD

**Issue by BoahEy** [Codeusa/Borderless-Gaming#155]
I installed the free version of Borderless Gaming today. Ever since, when I try to host a game of Orion:Prelude, the word "Saved" appears on the screen, but otherwise nothing happens. The developers of the game know about the issue (as others reported it, too), but seemingly have not been able to resolve it.
It may just be that those others reporting this problem are also Borderless Gaming Users, but did never have the before/after situation, as they had the program installed before installing the game.
I will now try to uninstall Borderless Gaming, and see whether that gets me back to where I was before..

**Comment by psouza4** [comment]
Simply close Borderless Gaming or turn off automatic favorites processing -- there's nothing persistent about what Borderless Gaming does that should affect your games.

**Comment by psouza4** [comment]
No reply in 3 days -- assuming this answer resolved your question.
