### ISSUE TITLE
Bug: Windows 10 incompatibility

### ISSUE THREAD

**Issue by chrisestep** [Codeusa/Borderless-Gaming#157]
BorderlessGaming works great on 7.0 for Everquest Titanium (Project 1999) but upon upgrading to Windows 10, 1) it gives a UAC prompt on load, 2) makes the game all black screen when maximized via the app.

**Comment by chrisestep** [comment]
The first problem was obviously my fault. Damn Win10 re-enabled UAC which I've had disabled.  Bonehead maneuver on my part.  Interestingly, it's now working fine.  We'll see if it continues or was just coincidence. Don't close this yet, I'll keep testing.

**Comment by psouza4** [comment]
Yeah, we hadn't commented yet because we know Windows 10 compatibility is pretty solid with Borderless Gaming and was hoping this would work itself out.  I am going to close it for now, but we can always re-open it if there's something we're not aware of that we need to account for.

**Comment by Dol-phin** [comment]
I actually had the same issue, some games have partially white screen after updating to Windows 10.
I tried to disable all UAC-related settings, let's hope the issue doesn't appear again.
