### ISSUE TITLE
Request: Add to favorites by window title regex match

### ISSUE THREAD

**Issue by SecretOnline** [Codeusa/Borderless-Gaming#159]
Best way to introduce this is to give an example.

Minecraft's window titles are "Minecraft <version string>". I don't wish to add by process, as there are other things that use `javaw`. 

In this case, you want something a bit less strict than the entire window title, but more strict than process name.

Of course, this would be useful for any games that put a version number/string in the window title, not just Minecraft.

(As a side note, the regex string `Minecraft (\d+\.\d+\.\d+|\d+w\d+\w)` should match all recent versions of the game (including snapshots))

I've forked and made changes, should have a PR coming in soon.

**Comment by SecretOnline** [comment]
Due to some strange issues I'm getting in Visual Studio, this may be a little while.

**Comment by psouza4** [comment]
Merge completed!
