### ISSUE TITLE
Dishonored unable to go fullscreen on Windows 10

### ISSUE THREAD

**Issue by JustDenDimi** [Codeusa/Borderless-Gaming#162]
Dishonored set to windowed
Added dishonored to Borderless Gaming list
Right and bottom side expand and retract repeatedly

**Comment by psouza4** [comment]
Dishonored is an Unreal Engine 3 game:

https://en.wikipedia.org/wiki/List_of_Unreal_Engine_games#Unreal_Engine_3

It's been discussed many times why Unreal Engine 3 games aren't and can't be supported.  Hopefully they do better in UE4.

**Comment by JustDenDimi** [comment]
Thank you for responding, I should've done some research. ^^
