### ISSUE TITLE
Request: Power Management Options

### ISSUE THREAD

**Issue by SwinglesMan** [Codeusa/Borderless-Gaming#163]
Can you add for right click on a game to choose whether or not the screensaver, screen dimming, sleep, and hibernation mode will initiate after a user defined amount of inactivity? It would be nice to keep them separate too because some may want one on but not the other. For instance: Screensaver, Screen Dimming to be separate but Sleep and Hibernation can be in one option since they do the same things. Say like, I'd want screensaver, sleep, hibernation off while I play the game but would like to keep screen dimming on. Then I'd be able to do that. And most of the time, games crash when resuming from hibernation anyway so, ya know.

**Comment by psouza4** [comment]
Windows does a fine job on its own of making sure it does not sleep or hibernate during gameplay.  I don't know why we'd need to micro-manage Windows' power options at all.  After reviewing all of your other requests, it sounds very much like you'd like Borderless Gaming to evolve into an automated solution for all things gaming, which could be a large undertaking and not necessarily a vision we share.  I'll let Andrew, the project founder, share his insight though.

**Comment by SwinglesMan** [comment]
Windows doesn't decide this. It's game specific. Some games have this. Some games don't. No game has allowing screen dimming to happen (xbmc has this feature though). Most of the time when games do have it, it's all or nothing. You can't choose which power saving feature you can keep or not. It'll just disable them all. I do have another program that can do this, but it is great if it is consolidated. That program doesn't have the option to allow screen dimming though. That program too is all or nothing. Thanks for listening.

**Comment by psouza4** [comment]
Ultimately, this is outside of the scope of what Borderless Gaming does and isn't something we'll add to the main project.  You're welcome to fork the project and twist it to other needs, but we didn't feel that many users would benefit from this kind of addition.
