### ISSUE TITLE
Request: Window Mode Options

### ISSUE THREAD

**Issue by SwinglesMan** [Codeusa/Borderless-Gaming#164]
We need a way to be able to press a hotkey to put it in a small window mode for when we need to look online at guides and such. Like making fullscreen mode borderless and having window mode stay the same but allow us to custom define how big the window in window mode will be while still using the same alt+enter hotkey.

**Comment by psouza4** [comment]
It doesn't sound like you understand how to use borderless windowed mode, which is the intended core purpose of Borderless Gaming.  Full screen gaming is not something we're supporting at this time (nor any odd interactions with swapping between full screen and borderless windowed full screen).

Feel free to comment if I misunderstand your request, but it doesn't make sense for the scope of Borderless Gaming as the request stands.

**Comment by SwinglesMan** [comment]
This is what I mean (think of the game being fullscreen already):


-Pressing alt+enter once will make the game borderless windowed that will fill your entire screen.

-Pressing alt+enter twice will make the game a regular window with the user defined size of how big you want the window to be (because some games wont let you choose the windowed mode size).

-Pressing alt+enter once more will return it to normal fullscreen mode.

**Comment by psouza4** [comment]
Sorry, but we can't really do this... for so, so many technical reasons.  You're asking to hook into games control of input processing, interact with games at a rendering level by hooking DirectX to force games in and out of full screen, etc.

Andrew has indicated his interest in hooking DirectX to force games without a windowed mode to run in a window anyway, but we're not at a point where we can launch such a feature and even if we do, it's very unlikely that this is something we can implement without stomping all over the operating behavior of other applications, which is not our aim.

**Comment by SwinglesMan** [comment]
So give me insight on what I can do when I want to look at guides online a play the game at the same time while looking since there are now 2 modes with this program that covers the whole screen with the game? I can make an autohotkey script to achieve this but is this program always forcing it or does it do it just once? Will autohotkey be able to shrink the window if I tell it to with a different hotkey while this program is still on and active on said game?

**Comment by psouza4** [comment]
Sure, you can write a script or macro that simulates keystrokes being sent to an application and hope that the game supports and interacts with that keystroke, such as Alt+Enter, which is supported in many games.  And many more that it's not supported in.  We're not discussing adding an option that asks the game to do something by simulating a keystroke because the compatibility rate would be absurdly low.

**Comment by SwinglesMan** [comment]
No, not that part. I want to know if autohotkey can put the window at a smaller size while this program has access to it already or if this program will force the game back to covering the whole screen when I do this?

**Comment by psouza4** [comment]
They will fight for control over window properties for a short time, but Borderless Gaming is designed to give up after a few attempts (because of problems with games using the Unreal Engine v3).  After it gives up, Borderless Gaming won't attempt to resize that window again automatically until the process has been restarted.

**Comment by SwinglesMan** [comment]
Okay cool, that's exactly what I wanted to know. Every hotkey combo works when the game is in borderless window mode because, well, it's window mode. Fullscreen mode wouldn't need a hotkey because it will already have one to be able to go into window mode which is usually still alt+enter. Thanks for the insight of how it will react with something that wants to make the window smaller.
