### ISSUE TITLE
Request: controller mode for mouse cursor hiding

### ISSUE THREAD

**Issue by SwinglesMan** [Codeusa/Borderless-Gaming#166]
Can you add the ability for the mouse cursor to disappear after 2 seconds of inactivity also instead of just hide it forever completely? I would like the indefinite one to stay as well as have this one too. However many seconds would be editable if other users need it be.

**Comment by psouza4** [comment]
I don't understand how this enhancement would improve Borderless Gaming's intended use.  Are you regularly idle while actively playing games?

**Comment by SwinglesMan** [comment]
I play with a controller. When Idle, I meant when not touching the keyboard or mouse. Sometimes it can be difficult to locate the mouse when it is completely inviso and sometimes this can make you rush and click the [x] on a windowed game by accident. When I'm playing a game, I want the cursor to be gone. When I want to move the window, I want the cursor to show so that I can see what I'm doing. It's just an automated process rather than pressing a hotkey to enable reenable every time. I have an autohotkey script to do this but I prefer to  consolidate to not have so many tools open and this seemed like the perfect program to ask for this for. Some pc games do this by default but not alot.

I find the indefinite option you already have to be useful with wiimote type games since most of the time, it envolves moving the mouse. I would like this option for controller type games.

**Comment by psouza4** [comment]
I'm updating the request to clarify its intended purpose.
