### ISSUE TITLE
Request: Controller Initiation Options

### ISSUE THREAD

**Issue by SwinglesMan** [Codeusa/Borderless-Gaming#168]
Afterplugging and hotplugging are big issues in most poorly ported games. I know it is not window related, but, can you include in this program whether a game will seek the controller if it's plugged in after it is started or whether the game will read the controller after it has been disconnected and reconnected? Would be a nice feature to have as a right click menu option for each game (with afterplugging and hotplugging being separate entries) to be able to give these abilities to games that do not have them

Sorry, I don't know how to add labels. They are greyed out on my end.

**Comment by psouza4** [comment]
Borderless Gaming can't modify the behavior of other applications like this.  You're asking for us to hook into how a program behaves, which is not the intent of Borderless Gaming.  Our intent is to instruct Windows to adjust the size and caption/border properties of other application's windows.

**Comment by SwinglesMan** [comment]
Okay, I wasn't sure. That's why I put 'I know it is not windows related'. Thanks anyway.
