### ISSUE TITLE
Request: Store Updates in Program's Folder [Up to 5]

### ISSUE THREAD

**Issue by SwinglesMan** [Codeusa/Borderless-Gaming#169]
I would like for the program to save the update in this program's folder and delete old updates. If you have more than 5 update exes, it would delete the oldest exes and keep 5 updates only at a time. This would be for to keep backups just in case something happens in an update in which one has to go back to an old version for.

**Comment by psouza4** [comment]
You haven't really explained what's wrong with the current automatic update checker built into Borderless Gaming.

**Comment by SwinglesMan** [comment]
Ohhh, I didn't even know it was already included. I'll change this to storing the updates in the program's folder only then.

**Comment by psouza4** [comment]
Why?  What can be benefited from archiving past updates to the software?  I can't imagine hardly anyone would want this feature, so give us some understanding of why we would spend time developing an unpopular feature?

Bear in mind that the more an application grows in complexity and scope, the larger the chances of incompatibility and error with so many moving parts.

**Comment by SwinglesMan** [comment]
Having backups for the program. It doesn't have to be 5, it can be one only if you want. Say like you are moving to a new machine and you have all of your programs on an hdd but your system stuff on a separate ssd. What's faster? Plugging in the hdd and installing the program from the program's folder or going online to download again and then installing? And what if you don't have the net at the time? Then one would have to hold off in using this program because they never had a backup. I do know of one program that does this and it's the game frontend called Launch-Box. I thought that was a very cool feature because it reduced the user in having to do the backing up themselves. It is also useful to have users help this program by pinpointing problems that may be in one but not the other and it could help the user help the dev to pinpoint when the problem first started.

**Comment by psouza4** [comment]
The proposed feature request is very uncommon (I can't even think of any software out there that actually does this, offhand) and would save a user almost no time since all older builds are available right here at Github at the same release page, making them easy and convenient to find.

**Comment by SwinglesMan** [comment]
Who cares if it is not common. Gedosato and launchbox do this. I requested a feature to make things easier for the user. That's what programs are all about. You said on your steam page to let ppl know if you want more features and yet you deny everyone every feature they propose. Are you even going to fix the mouse cursor bug? Probably not since you have some dumb reason not too or are just lazy. When you decide to jump ship and the github page eventually goes to shit, how would we find it then? Exactly. Your kind of attitude is that of those programmers who WILL abandon their project. This program even borderlesses windows that you dont even tell it to and it becomes difficult to even add games to the list without minimizing your game (assuming you can). Will you even fix that!? Or will you just keep closing everyone's threads of not fixing ANYTHING? Geez, you guys are worthless. Fuck all your future 'get back' comments. Throwing this shit in the recycling bin.
