### ISSUE TITLE
Makes screen flash on KOTOR II

### ISSUE THREAD

**Issue by aav7fl** [Codeusa/Borderless-Gaming#172]
Whenever I enable borderless gaming 8.2 with Star Wars Knights the Old Republic II and Knights of the Old Republic I on steam,the screen flickers as the window becomes repeatedly detected and undetected when it switches it to borderless window mode, fails, and then goes back.

**Comment by psouza4** [comment]
Borderless Gaming is depending on each game's handling of its windows being forcibly resized. To that end, not all games are compatible. Some will render oddly, some will have mouse positioning issues as they are programmed to believe the screen is still in a specific resolution, some will not scale to fill the new window size, some will simply revert to their original window size, and so on. Unfortunately, there's nothing Borderless Gaming can do in these situations.
