### ISSUE TITLE
Need help (if possible) for two old games !

### ISSUE THREAD

**Issue by Acehole** [Codeusa/Borderless-Gaming#173]
After i go to windows 10 (!) i find two "old games" that doesn't function properly ( they do in win 8.1) Ghost Recon and A-10 Cuba (yes,old games) .By chance , i discover "borderless-gaming" in review in the french magazine "Canard PC" and , phew, allow the games to run again !!! So , the problems that remains:The start menu of Ghost recon (windowed by modify the options.xml file) appear in small windows upper left on screen ( could be moved by alt -tab) , switch by your soft in full screen , playing game also in full-screen but when i end the game (mission) it go back to the first small window ..and return to full screen when i launch an other mission .After i have the pleasure of the big screen it is painful to go back , even in the menu , on this small (very ) window with hard to read buttons!!!! For A-10 Cuba , it is more complicated (to me) the game is launched on a "splash screen " perfectly centered but the game has two black borders ....if i try "borderless gaming" , i have two splash screen (only one functional) and no change for the black borders . Thanks for your work and to have read this and for your help !

**Comment by psouza4** [comment]
Borderless Gaming is depending on each game's handling of its windows being forcibly resized.  To that end, not all games are compatible.  Some will render oddly, some will have mouse positioning issues as they are programmed to believe the screen is still in a specific resolution, some will not scale to fill the new window size, some will simply revert to their original window size (almost all modern Unreal Engine-based games), and so on.  Unfortunately, there's nothing Borderless Gaming can do in these situations.
