### ISSUE TITLE
Cannot disable Steam Hook (in-app on steam)

### ISSUE THREAD

**Issue by highdroid** [Codeusa/Borderless-Gaming#174]
The function Disable Steam Hook does not work for me. The chat in Steam always says that Im in-game Borderless Gaming :-1:

**Comment by Codeusa** [comment]
Did you try following the instructions provided? Disable the hook and run the program from the direct executable, not through steam, we can't control what steam says if you run something through it.

**Comment by xxcbzxx** [comment]
Thanks Codeusa..

its worked....

the location to the file is at 

<drive_letter>:\SteamLibrary\steamapps\common\Borderless Gaming

the executable is BorderlessGaming.exe

But run that as Administrator should be fine
