### ISSUE TITLE
Mouse cursor not going all the way to the screen edge

### ISSUE THREAD

**Issue by Muyfa666** [Codeusa/Borderless-Gaming#175]
Hi there.

Using v8.2 on Win 10 Pro.

The app "fullscreens" the game as intended. but the mouse cursor will stop about a decimeter from the right egde and will not go to the edge of the screen. Any idea why?

**Comment by robiwobi** [comment]
This is an issue with me as well and it affects MOBA games a lot. I am playing Heroes of Newerth in particular. The edges of the top and left screen are okay, but I can't reach the bottom and right most screen.

I am using windows 10 Pro as well.

**Comment by psouza4** [comment]
Borderless Gaming is depending on each game's handling of its windows being forcibly resized. To that end, not all games are compatible. Some will render oddly, some will have mouse positioning issues as they are programmed to believe the screen is still in a specific resolution, some will not scale to fill the new window size, some will simply revert to their original window size, and so on. Unfortunately, there's nothing Borderless Gaming can do in these situations.
