### ISSUE TITLE
Request: Disable tray notifications in Windows 10

### ISSUE THREAD

**Issue by vaindil** [Codeusa/Borderless-Gaming#176]
I don't know if this is a Windows 10-specific problem, but I get a built-in notification from the OS whenever BG is minimized to the tray. This includes when I open it, since I have it set to minimize on opening. A way to disable this would be great; the notification every single time gets irritating.

**Comment by psouza4** [comment]
You can easily disable this in Windows itself.  Without dismissing the
message, click on the Notification Icon in the system tray to go to your
Windows notification center.  Right-click the notification from Borderless
Gaming and choose to suppress future notifications from Borderless Gaming.

On Sat, Aug 8, 2015 at 3:40 PM, Steven Hall <notifications@github.com>
wrote:

> I don't know if this is a Windows 10-specific problem, but I get a
> built-in notification from the OS whenever BG is minimized to the tray.
> This includes when I open it, since I have it set to minimize on opening. A
> way to disable this would be great; the notification every single time gets
> irritating.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Codeusa/Borderless-Gaming/issues/176>.
>



-- 
-Pete

**Comment by LavenderMoon** [comment]
If you don't have a Notification Icon in the system tray, you can right-click on the clock and click "Customize notification icons."
