### ISSUE TITLE
Green screen

### ISSUE THREAD

**Issue by bovrilfreeman** [Codeusa/Borderless-Gaming#178]
On certain games like gmod its just gives me a green screen if i try to alt tab then i have to reboot

**Comment by psouza4** [comment]
Borderless Gaming is depending on each game's handling of its windows being forcibly resized.  To that end, not all games are compatible.  Some will render oddly, some will have mouse positioning issues as they are programmed to believe the screen is still in a specific resolution, some will not scale to fill the new window size, some will simply revert to their original window size (almost all modern Unreal Engine-based games), and so on.  Unfortunately, there's nothing Borderless Gaming can do in these situations.
