### ISSUE TITLE
FIFA Manager 13 Incompatability Issue

### ISSUE THREAD

**Issue by NexxusDrako** [Codeusa/Borderless-Gaming#179]
FIFA Manager 13 will not work with Borderless Fullscreen.

The reason for this is that the mouse cursor will freeze in the centre of screen when alt+tab is engaged and lock there, it will move rapidly but will remain anchored to the centre of screen. When alt tab is used again, it may or may not remain so unless you alt+tab into the game, it depends on whether you have other windows open.

When in game, the mouse cursor works as intended, but the game will take longer to shut down, causing a black screen with no cursor for ~5 seconds.

The main reason I wanted to make this game borderless is that the game suspends when not focussed, and as it is a sports title, I do wish to simulate a few years ahead sometimes without having my computer locked down. The suspension also occurs while saving and loading, though there are no ill effects unless you actually shut it down by mistake.

I know you cannot fix the problems with the game itself, but hopefully you can get Borderless Fullscreen working with it.

**Comment by psouza4** [comment]
Borderless Gaming is depending on each game's handling of its windows being forcibly resized.  To that end, not all games are compatible.  Some will render oddly, some will have mouse positioning issues as they are programmed to believe the screen is still in a specific resolution, some will not scale to fill the new window size, some will simply revert to their original window size (almost all modern Unreal Engine-based games), and so on.  Unfortunately, there's nothing Borderless Gaming can do in these situations.
