### ISSUE TITLE
Terraria's title bugging favorites (automatic)

### ISSUE THREAD

**Issue by the1gamerdude** [Codeusa/Borderless-Gaming#183]
due to terraria using multiple titles in windows (ie with a suffix of Now in 1D, and Can you Re-Dig-It?) the program thinks they are separate programs. I don't see a easy fix in options though I am guessing I'm not the first one to report this. It is very easy to just add all of the suffixes on my side just wanted to make sure you were aware of this

**Comment by Codeusa** [comment]
You can add it as a process name rather than the window title, right click.
