### ISSUE TITLE
Bug: option "Run on Windows startup" is ineffective

### ISSUE THREAD

**Issue by ronjouch** [Codeusa/Borderless-Gaming#184]
Hi.

When using this option, BG does correctly create a `.lnk` shortcut in `C:\Users\USERNAME\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup`, but:

* For some reason, the app doesn't run at startup (app is neither visible in the tray, nor in the task manager).
* Yes, running the shortcut manually from the explorer works.
* Running programs at startup using this path usually works (I have other `.lnk` shortcuts here, they do correctly launch at startup).
* I tried using a registry key instead (e.g. `HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Run`), it doesn't work either.

Machine: Windows 10 x64, WindowsUpdate-d, BG 8.2admin.

**Comment by LavenderMoon** [comment]
Same here, including Windows 10, and it didn't work months ago when I first started using it, back when I was still using Windows 7.

**Comment by psouza4** [comment]
I assume you are running the elevated version of Borderless Gaming.  If so, this has been discussed already:

https://github.com/Codeusa/Borderless-Gaming/issues/69
https://github.com/Codeusa/Borderless-Gaming/issues/112

**Comment by ronjouch** [comment]
> I assume you are running the elevated version of Borderless Gaming. If so, this has been discussed already: #69 #112

Correct :+1: , thanks for pointing me to this! Maybe it would be nice to have the entry deactivated / greyed out in this case, then? (for greater visibility, coupled with appending some warning string like ` (disabled due to running as Admin)` to the menu entry text. Anyway, closing, and I'm giving a try to the workaround proposed by @karasuhebi in https://github.com/Codeusa/Borderless-Gaming/issues/100#issuecomment-111003786 :

> @psouza4 & @Codeusa: There's multiple workarounds for being able to autostart on Windows 8/8.1 with elevated privileges. Check out what programs like Fraps do. Basically what you do is have Borderless Gaming install on C:\ instead of C:\Program Files\ and then schedule a task that runs at log on of any user. I tried it myself with the admin Borderless Gaming and it works fine.

**Comment by karasuhebi** [comment]
@ronjouch Let me know if it worked for you, as it's working fine for me. I'd be glad to help!
