### ISSUE TITLE
Request: Minimize on lost focus

### ISSUE THREAD

**Issue by martind0** [Codeusa/Borderless-Gaming#187]
Please add option to minimize the game whenever we alt-tab. Because sometimes when I have game on background and I alt tab back in, there is just black screen. I fixed this by manually minimizing the game in task manager. For me it's also a wanted behavior, because the game is mostly just obstructing when working with other windows.

**Comment by mugsy8** [comment]
this is a great idea.
but it needs to be a toggle option because i already know a few games that crap themselves if i minimise the window.
