### ISSUE TITLE
Project Cars Menu Issues

### ISSUE THREAD

**Issue by Aaeon** [Codeusa/Borderless-Gaming#188]
I'm telling the game 1920x1200 windowed mode, then letting BG remove the border making it full screen.  Everything works as far as I can tell except I'm noticing when I try to navigate menu's I'm having to click above where I'd normally click otherwise it's not registering. Is there a way to fix this?

**Comment by psouza4** [comment]
Borderless Gaming is depending on each game's handling of its windows being forcibly resized.  To that end, not all games are compatible.  Some will render oddly, some will have mouse positioning issues as they are programmed to believe the screen is still in a specific resolution, some will not scale to fill the new window size, some will simply revert to their original window size (almost all modern Unreal Engine-based games), and so on.  Unfortunately, there's nothing Borderless Gaming can do in these situations.
