### ISSUE TITLE
H1Z1 does not work with borderless gaming

### ISSUE THREAD

**Issue by LieutenantLZ** [Codeusa/Borderless-Gaming#189]
Tried everything. When I launched the game it first has a launcher so I didn't make that borderless. Then when the actual game was running, I tried putting that in borderless (it has a super weird window name), but it continued to be the annoying full screen that it is.

**Comment by psouza4** [comment]
Borderless Gaming works by resizing a window to borderless-fullscreened-window.  The game must be running in a window first, not be in a hard fullscreen mode.
