### ISSUE TITLE
Tony Hawk Pro Skater 2

### ISSUE THREAD

**Issue by Catarax** [Codeusa/Borderless-Gaming#190]
Hello,
When THPS2 is launched, unpossible to go back to Bordeless-Gaming with the windows shortcuts in order to fix the game.

Any idea on how to do it ?

**Comment by psouza4** [comment]
Your problem doesn't make sense and more information is required.  Why can't you go back to Borderless Gaming?

**Comment by psouza4** [comment]
Closed as abandoned.
