### ISSUE TITLE
Inviting Friends to play Borderless

### ISSUE THREAD

**Issue by AngryItalian** [Codeusa/Borderless-Gaming#193]
In Pay Day 2, it invites my friend to play Borderless Gaming instead of Pay Day. It tells him I'm playing a different game, and when he accepts the invite from desktop, it takes him to this app. Is there a way to fix this, or did I actually find a bug?

**Comment by psouza4** [comment]
Run the standalone version of Borderless Gaming so that it's not hooked by Steam.  This will prevent sharing, streaming, usage tracking, etc. issues with the Steam platform.
