### ISSUE TITLE
FINAL FANTASY TYPE-0 HD: enlagres to fullscreen both game launcher and actual game

### ISSUE THREAD

**Issue by lainverse** [Codeusa/Borderless-Gaming#194]
This game have two executables:
fftype0hdlauncher.exe - in the game root golder
fftype0hd.exe - in the WIN subfolder

As I understand both windows have the same title and as result BG detects and enlarges to the fullscreen them both. Another side-effect: Hide Mouse Cursor mode applied to both windows as well and mouse is really needed in the game launcher.

I'd recommend to store process name and path alongside with the window title and use them to detect windows to enlarge. Also, there should be options to ignore process name, path or windows title for the backward compatibility and ability to enlarge all windows of specific application. Last proposed otion would be useful if game will display version number in the title.

**Comment by psouza4** [comment]
Borderless Gaming can favorite a process by process name (the binary/filename).  Sounds like you aren't taking advantage of this option.

**Comment by lainverse** [comment]
True, haven't noticed there was such an option. Sorry for asking a dumb question from the user guide.

**Comment by psouza4** [comment]
Glad that works for you. :+1:

**Comment by lainverse** [comment]
It's just not intuitive that there are two ways of adding games to the list on the right. I think there should be either second button or some first-run guide. I've encountered such functionality in a few programs already. Maybe I've missed something, but I haven't found anything in the interface that indicated existence of the right-click menu in the panels. I think the biggest problem here actually a 'Help' menu which contains everything, but an actual help or a user guide.

**Comment by psouza4** [comment]
You're welcome to add some help documentation.  I contribute to the project with code changes, support, etc., but Boderless Gaming is not my project and I haven't found/made the time to write up help docs, guides, etc. myself.

**Comment by psouza4** [comment]
Additionally, I am adding a "Right-click for more options" message in the status area before the last updated timestamp and a link in the Help menu to the guide Andrew wrote up at Steam in response to your suggestions.
