### ISSUE TITLE
Make use of virtual desktops in Windows 10

### ISSUE THREAD

**Issue by undu** [Codeusa/Borderless-Gaming#196]
Virtual desktops were introduced in Windows 10, this allows to have a virtual desktop exclusively for full-screen games while having others for web browsing, chatting etc.

Right now Borderless Gaming doesn't make use of virtual desktops, for example whenever the Windows taskbar is hidden, it's hidden in all the monitors, making it a bit inconvenient in some cases.
It'd be really nice if Borderless Gaming could send game windows to a virtual desktop (like it now does with multiple monitor setups) and disable mouse cursor and windows taskbar only in the desktop where a game screen is.

Micrososft provides and [API](https://msdn.microsoft.com/en-us/library/windows/desktop/mt186440%28v=vs.85%29.aspx) to interact with virtual desktops, I'm not sure how easy would it be to add these functionalities using those 3 methods.
Here's a little program that moves itself to the active virtual desktop, for reference: http://blogs.msdn.com/b/winsdk/archive/2015/09/10/virtual-desktop-switching-in-windows-10.aspx

**Comment by Megasware128** [comment]
I got one other problem with Borderless Gaming and virtual desktops. While this is not the fault of Borderless Gaming, some games disable the start button which I use to do CTRL+Start+Left/Right. Is it possible to add functionality to Borderless Gaming to reactivate the start button?

**Comment by bb010g** [comment]
Alternatively, I *think* you can hook into a semi-hidden API and give a new binding to switch. http://www.cyberforum.ru/blogs/105416/blog3671.html
