### ISSUE TITLE
Using it w/ Pokemon Reborn just puts the game in the corner of a black screen

### ISSUE THREAD

**Issue by SilverClock** [Codeusa/Borderless-Gaming#198]
http://www.pokemonreborn.com/game/
![untitled-2](https://cloud.githubusercontent.com/assets/14909350/10197848/19189428-675f-11e5-843e-c5fbc66bf9fe.jpg)
Currently trying for 1920x1080 on my TV.

**Comment by SilverClock** [comment]
The game doesn't get any bigger at all. If it were possible to just enlarge it and center it..

**Comment by psouza4** [comment]
Borderless Gaming is depending on each game's handling of its windows being forcibly resized.  To that end, not all games are compatible.  Some will render oddly, some will have mouse positioning issues as they are programmed to believe the screen is still in a specific resolution, some will not scale to fill the new window size, some will simply revert to their original window size (almost all modern Unreal Engine-based games), and so on.  Unfortunately, there's nothing Borderless Gaming can do in these situations.
