### ISSUE TITLE
Diadra Empty: Image doesn't scale, can't detect window for a while

### ISSUE THREAD

**Issue by lainverse** [Codeusa/Borderless-Gaming#199]
Game: DIadra Empty
Steam ID: 284220
Image remains small and just displayed in the corner of the window. Windo remains small until FPS counter in the teatle hits maximum. It have a title "Diadra Empty (N FPS)" where N is a number and it stays at 1 for a few seconds at start. During this period BG doesn't see DE window and does not attepmts to resize it.

**Comment by psouza4** [comment]
Borderless Gaming is depending on each game's handling of its windows being forcibly resized.  To that end, not all games are compatible.  Some will render oddly, some will have mouse positioning issues as they are programmed to believe the screen is still in a specific resolution, some will not scale to fill the new window size, some will simply revert to their original window size (almost all modern Unreal Engine-based games), and so on.  Unfortunately, there's nothing Borderless Gaming can do in these situations.
