### ISSUE TITLE
Window not detected in processes.

### ISSUE THREAD

**Issue by mugsy8** [Codeusa/Borderless-Gaming#200]
Hi there,

loving the program. I use it for many things recently and most of my games that will support it.
Works freaking fantastic with elite:dangerous on my TV or on my triplewide setup and for anyone who actively plays league of legends with more than a passing interest... this program will set free your soul, best thing since sliced bread!

Anyway,
I have stumbled across an oddity that I hope is able to be resolved easily, though it might be impossible depending on how the window detection works or if its solely windows process driven.

The issue;
Recently with the birth of my son I have needed to switch prominently to games that i can pause and come back to, with my wish to be constantly challenged... enter Dwarf Fortress.

When running the game I use the 'Lazy Newb Pack' where I believe the game itself runs as a child window from DFHack which is used to inject commands, settings and inputs from 3rd party utilities that are pretty much essential to not failing miserably unless you have an inexhaustible supply of patience and know the in-game interface VERY well.

Your program, however awesome... fails to detect the child window that contains the game and instead only detects the command prompt window run by DFHack which is unfortunately is completely useless :)  This by no means prevents me from playing the game, nor from getting fullscreen as you can simply press F11 but the simplicity and convenience of your program is something that i like very much and i want it to work :'(

In the windows 10 task manager it come up as (2) process/windows and I know that means that it should be possible, but i can work out how to tweak it.

cheers,
mugz

**Comment by psouza4** [comment]
Did you try the slow-window detection option in Borderless Gaming to try and find that window?

**Comment by mugsy8** [comment]
This feature does not appear to do anything on my system. 
--
Sent from myMail app for Android Thursday, 26 November 2015, 03:44am +10:00 from Peter Souza < notifications@github.com> :

**Comment by undu** [comment]
I have the same issue since I updated to version 8.3.

I also get an IO exception whenever I try to force the scan because it couldn't find a library, it got fixed for me re-downloading the installer. Most probably it has the same cause as https://github.com/Codeusa/Borderless-Gaming/issues/209 and https://github.com/Codeusa/Borderless-Gaming/issues/210.

**Comment by psouza4** [comment]
@undu his issue predates the release of version 8.3, so it can't be related

**Comment by mugsy8** [comment]
Yes, my issue has nothing to do with 8.3
Since 8.3 appears to not run on my computers.
I had to spent a few minutes getting 8.3 deleted properly so I could go back to 8.2 Saturday, 28 November 2015, 02:01am +10:00 from Peter Souza < notifications@github.com> :
