### ISSUE TITLE
Hotkeys doesn't work.

### ISSUE THREAD

**Issue by sneaky4oe** [Codeusa/Borderless-Gaming#201]
Hi, I'm trying to lock the mouse cursor inside any window, but it doesn't work. It used to, but suddenly stopped.
I'm also unable to switch fullscreen apps to windowed by a hotkey.
Win8.1 64x.

**Comment by psouza4** [comment]
Sounds like maybe a permissions issue.  Are you running Borderless Gaming as an Administrator (right-click option that elevates an application, not passively from an administrative account).

**Comment by sneaky4oe** [comment]
Yes, this fixes the issue most of the time, but not always.

**Comment by psouza4** [comment]
Unfortunately, there's no middle road for Borderless Gaming when it comes to processing hotkey logic.  If it's working "most of the time", then something is interfering with hotkey processing in other applications.  For example, AutoHotKey scripts, video driver tools, the screen recorder oCam, and other applications will interfere with global hotkeys depending on the software load order.  You'll need to experiment with what other software is running and the order that you started those programs.
