### ISSUE TITLE
Automatically lock mouse option

### ISSUE THREAD

**Issue by sneaky4oe** [Codeusa/Borderless-Gaming#202]
An option for favorites to automatically lock mouse in them while they're in focus would be really usefull.Can't fix it all the time for CSGO and spect Dota.

**Comment by Driphter** [comment]
Intuitively, hiding the cursor should work similarly. :)

**Comment by sneaky4oe** [comment]
But will it hide cursor in strageties or moba? Or in main menu of shooters?..

**Comment by Driphter** [comment]
I meant it would be nice if you were able to have the cursor hidden automatically in certain games. Same as you suggested for locking cursors. Its a feature currently supported that is useful for games in which the cursor should probably be hidden but isn't.

**Comment by psouza4** [comment]
Duplicate of issue #137
