### ISSUE TITLE
[8.2] Doesn't work with Starmade, makes an invisible overlay fullscreen instead

### ISSUE THREAD

**Issue by RadGH** [Codeusa/Borderless-Gaming#204]
The game StarMade running in 1920x1080 with fullscreen disabled, it's in a window. There is a launcher called "StarMade Connection Setup [javaw]" which opens the game. The game itself is in a window named "StarMade alpha v0.19xxxx (xxxxxxx) [SANDBOX]; 64bit".

The second name doesn't appear in the list of applications. If you make the first one always on top (which is hidden while the game is running), an invisible window goes on top which you can't click through.

So this is effectively two problems in one:

1) It doesn't make the game borderless
2) It makes the launcher interfere with the screen, which you have to restart the game to fix

**Comment by psouza4** [comment]
Borderless Gaming is depending on each game's handling of its windows being forcibly resized.  To that end, not all games are compatible.  Some will render oddly, some will have mouse positioning issues as they are programmed to believe the screen is still in a specific resolution, some will not scale to fill the new window size, some will simply revert to their original window size, and so on.  Unfortunately, there's nothing Borderless Gaming can do in these situations.
