### ISSUE TITLE
Mass Effect 1

### ISSUE THREAD

**Issue by KarpyDiem** [Codeusa/Borderless-Gaming#205]
I have Borderless Gaming running, launch the application I wish to make full screen (Mass Effect 1), and refresh the application list.  Mass Effect comes up, but has an error tag attached to it:

Mass Effect [<error>]

Even if added to favorites, nothing happens.  I currently have the game running in windowed mode at 1920x1080.

**Comment by psouza4** [comment]
This sounds like a permissions problem.  Try running Borderless Gaming as an Administrator.

**Comment by psouza4** [comment]
Closed as abandoned.
