### ISSUE TITLE
Mousegrid error in World of WarShips 5.1.1

### ISSUE THREAD

**Issue by Loeffelmaster** [Codeusa/Borderless-Gaming#206]
Hi,
BorderlessGaming was running fine. With the update to World of WarShips 5.1.1 I have a strange issue. Perhaps it isn't a program error and there is a method to reset it.
The window is maximized as before, but now the Y-resolution for mouse clicks doesn't seem to be scaled too. Everything must be clicked a little bit higher than it is. The more you come to the top, the smaller the correction.
But it would be to easy, if it would be just that way. When I switch the game to fullscreen and back to windowed mode, everything is fine again. This must be done after every program start. So it seems to be a problem with recognition at program start. Not a problem with the program at all.

So perhaps when I reset everything. Would it be enough to delete WoWs from Borderless-Gaming and add it again?

Yours

Loeffel

**Comment by psouza4** [comment]
Borderless Gaming is depending on each game's handling of its windows being forcibly resized.  To that end, not all games are compatible.  Some will render oddly, some will have mouse positioning issues as they are programmed to believe the screen is still in a specific resolution, some will not scale to fill the new window size, some will simply revert to their original window size, and so on.  Unfortunately, there's nothing Borderless Gaming can do in these situations.
