### ISSUE TITLE
Loading...

### ISSUE THREAD

**Issue by GPParm** [Codeusa/Borderless-Gaming#209]
I open the program and it says loading... in the bottom and NEVER goes away.

**Comment by GK-GAMES** [comment]
it happens to me as well

**Comment by GPParm** [comment]
Yeah my friend also has this problem.

**Comment by Player808** [comment]
same here

**Comment by Kratzwurst** [comment]
@ the same here, i deinstall the old version 8.2 and install than the new version and runs as the administrator

Than i go to tools and make full aplication refresh, and becomes this issue:

Thread Exception Caught an unhandled thread exception was caught and logged to c:\.......appdata......


[ThreadException_26.11.2015.txt](https://github.com/Codeusa/Borderless-Gaming/files/44972/ThreadException_26.11.2015.txt)

Greets Kratzwurst

**Comment by Codeusa** [comment]
In away on Holiday so I haven't even had a chance to look at 8.3 however tagging @psouza4

**Comment by psouza4** [comment]
Please go back to the 8.3 release and grab version 8.3.33015.555, released this morning.
