### ISSUE TITLE
After updating to 8.3, thread crash on startup

### ISSUE THREAD

**Issue by ripdog** [Codeusa/Borderless-Gaming#210]
I've included my settings and log file. I'm running Win 10 and the admin version of borderless gaming.

Renamed from json to txt so github will accept them.
[ThreadException_26-11-2015.txt](https://github.com/Codeusa/Borderless-Gaming/files/44607/ThreadException_26-11-2015.txt)
[Favorites.txt](https://github.com/Codeusa/Borderless-Gaming/files/44608/Favorites.txt)
 Cheers!

**Comment by ZereoX** [comment]
I can confirm this is happening to me as well. Windows 10 with BG 8.3.


[ThreadException_11-26-2015.txt](https://github.com/Codeusa/Borderless-Gaming/files/44808/ThreadException_11-26-2015.txt)

**Comment by cech12** [comment]
The same!
[ThreadException_26.11.2015.txt](https://github.com/Codeusa/Borderless-Gaming/files/45057/ThreadException_26.11.2015.txt)

**Comment by dannythegreat** [comment]
Confirm


[ThreadException_26-11-2015.txt](https://github.com/Codeusa/Borderless-Gaming/files/45059/ThreadException_26-11-2015.txt)

**Comment by rpr13** [comment]
Here. Have my log for reference. Just hide exception if it is not needed for users to see. ;-)
[ThreadException_26.11.2015.txt](https://github.com/Codeusa/Borderless-Gaming/files/45087/ThreadException_26.11.2015.txt)

**Comment by psouza4** [comment]
Please go back to the 8.3 release and grab version 8.3.33015.555, released this morning.

**Comment by rpr13** [comment]
Well. Now I even cannot start installer.

**Comment by psouza4** [comment]
The installer was simply missing a .dll file from Google's NuGet packages.  It includes it now but doesn't require it to start the installer itself.  If you can't start the installer, there's a problem on your end for sure.

**Comment by rpr13** [comment]
It's not helping. :-)
![itworksforme](https://cloud.githubusercontent.com/assets/899792/11428045/d6748d9e-9467-11e5-84b7-6c2d65625596.gif)

**Comment by Acecool** [comment]
So the favorites file is favorites.json and goes into the appdata folder? Going to try that to see if it fixes my problem.
