### ISSUE TITLE
Stuck on loading.  Version 8.3

### ISSUE THREAD

**Issue by Qwerty-Space** [Codeusa/Borderless-Gaming#211]
<img>http://i.imgur.com/kxt8u8P.png</img>
I'm running Windows 10 Pro, and BG has been working fine for me up until today.
Running the full application refresh option returns this:
<img>http://i.imgur.com/RE7srZr.png</img>

[Log here](https://dl.dropboxusercontent.com/u/47538466/ShareX/2015/11/ThreadException_27-11-2015.json)

**Comment by psouza4** [comment]
You are using an outdated version (8.3.32915.682) and should upgrade (8.3.33015.555) which resolves this, as mentioned in issues #209 and #210.

**Comment by Qwerty-Space** [comment]
Thank you!  It didn't tell me there was an update, like usual.
