### ISSUE TITLE
ThreadException

### ISSUE THREAD

**Issue by modioperandus** [Codeusa/Borderless-Gaming#212]
BG opens and just says Loading. Eventually gets threadexception with the following log:

{
  "ClassName": "System.IO.FileNotFoundException",
  "Message": "Could not load file or assembly 'System.Threading.Tasks, Version=2.6.8.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.",
  "Data": null,
  "InnerException": null,
  "HelpURL": null,
  "StackTraceString": "   at BorderlessGaming.Forms.MainWindow.fullApplicationRefreshToolStripMenuItem_Click(Object sender, EventArgs e)\r\n   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)\r\n   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)\r\n   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)\r\n   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)\r\n   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)\r\n   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)\r\n   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)\r\n   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)\r\n   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)\r\n   at System.Windows.Forms.Control.WndProc(Message& m)\r\n   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)\r\n   at System.Windows.Forms.ToolStrip.WndProc(Message& m)\r\n   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)\r\n   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)\r\n   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)\r\n   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)",
  "RemoteStackTraceString": null,
  "RemoteStackIndex": 0,
  "ExceptionMethod": "8\nfullApplicationRefreshToolStripMenuItem_Click\nBorderlessGaming, Version=8.3.33015.555, Culture=neutral, PublicKeyToken=null\nBorderlessGaming.Forms.MainWindow\nVoid fullApplicationRefreshToolStripMenuItem_Click(System.Object, System.EventArgs)",
  "HResult": -2147024894,
  "Source": "BorderlessGaming",
  "WatsonBuckets": null,
  "FileNotFound_FileName": "System.Threading.Tasks, Version=2.6.8.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a",
  "FileNotFound_FusionLog": "WRN: Assembly binding logging is turned OFF.\r\nTo enable assembly bind failure logging, set the registry value [HKLM\\Software\\Microsoft\\Fusion!EnableLog] (DWORD) to 1.\r\nNote: There is some performance penalty associated with assembly bind failure logging.\r\nTo turn this feature off, remove the registry value [HKLM\\Software\\Microsoft\\Fusion!EnableLog].\r\n"
}

{
  "ClassName": "System.IO.FileNotFoundException",
  "Message": "Could not load file or assembly 'Interop.IWshRuntimeLibrary, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.",
  "Data": null,
  "InnerException": null,
  "HelpURL": null,
  "StackTraceString": "   at BorderlessGaming.Utilities.AutoStart.Create(String shortcutPath, String targetPath, String arguments)\r\n   at BorderlessGaming.Forms.MainWindow.toolStripRunOnStartup_CheckChanged(Object sender, EventArgs e)\r\n   at System.Windows.Forms.ToolStripMenuItem.set_CheckState(CheckState value)\r\n   at System.Windows.Forms.ToolStripMenuItem.set_Checked(Boolean value)\r\n   at BorderlessGaming.Forms.MainWindow.MainWindow_Load(Object sender, EventArgs e)\r\n   at System.Windows.Forms.Form.OnLoad(EventArgs e)\r\n   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)\r\n   at System.Windows.Forms.Control.CreateControl()\r\n   at System.Windows.Forms.Control.WmShowWindow(Message& m)\r\n   at System.Windows.Forms.Control.WndProc(Message& m)\r\n   at System.Windows.Forms.Form.WmShowWindow(Message& m)\r\n   at System.Windows.Forms.Form.WndProc(Message& m)\r\n   at BorderlessGaming.Forms.MainWindow.WndProc(Message& m)\r\n   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)",
  "RemoteStackTraceString": null,
  "RemoteStackIndex": 0,
  "ExceptionMethod": "8\nCreate\nBorderlessGaming, Version=8.2.20715.805, Culture=neutral, PublicKeyToken=null\nBorderlessGaming.Utilities.AutoStart\nBoolean Create(System.String, System.String, System.String)",
  "HResult": -2147024894,
  "Source": "BorderlessGaming",
  "WatsonBuckets": null,
  "FileNotFound_FileName": "Interop.IWshRuntimeLibrary, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null",
  "FileNotFound_FusionLog": "WRN: Assembly binding logging is turned OFF.\r\nTo enable assembly bind failure logging, set the registry value [HKLM\\Software\\Microsoft\\Fusion!EnableLog] (DWORD) to 1.\r\nNote: There is some performance penalty associated with assembly bind failure logging.\r\nTo turn this feature off, remove the registry value [HKLM\\Software\\Microsoft\\Fusion!EnableLog].\r\n"
}

{
  "ClassName": "System.IO.FileNotFoundException",
  "Message": "Could not load file or assembly 'System.Threading.Tasks, Version=2.6.8.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.",
  "Data": null,
  "InnerException": null,
  "HelpURL": null,
  "StackTraceString": "   at BorderlessGaming.Forms.MainWindow.viewFullProcessDetailsToolStripMenuItem_CheckedChanged(Object sender, EventArgs e)\r\n   at System.Windows.Forms.ToolStripMenuItem.OnCheckedChanged(EventArgs e)\r\n   at System.Windows.Forms.ToolStripMenuItem.set_CheckState(CheckState value)\r\n   at System.Windows.Forms.ToolStripMenuItem.set_Checked(Boolean value)\r\n   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)\r\n   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)\r\n   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)\r\n   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)\r\n   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)\r\n   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)\r\n   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)\r\n   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)\r\n   at System.Windows.Forms.Control.WndProc(Message& m)\r\n   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)\r\n   at System.Windows.Forms.ToolStrip.WndProc(Message& m)\r\n   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)\r\n   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)\r\n   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)\r\n   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)",
  "RemoteStackTraceString": null,
  "RemoteStackIndex": 0,
  "ExceptionMethod": "8\nviewFullProcessDetailsToolStripMenuItem_CheckedChanged\nBorderlessGaming, Version=8.3.33015.555, Culture=neutral, PublicKeyToken=null\nBorderlessGaming.Forms.MainWindow\nVoid viewFullProcessDetailsToolStripMenuItem_CheckedChanged(System.Object, System.EventArgs)",
  "HResult": -2147024894,
  "Source": "BorderlessGaming",
  "WatsonBuckets": null,
  "FileNotFound_FileName": "System.Threading.Tasks, Version=2.6.8.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a",
  "FileNotFound_FusionLog": "WRN: Assembly binding logging is turned OFF.\r\nTo enable assembly bind failure logging, set the registry value [HKLM\\Software\\Microsoft\\Fusion!EnableLog] (DWORD) to 1.\r\nNote: There is some performance penalty associated with assembly bind failure logging.\r\nTo turn this feature off, remove the registry value [HKLM\\Software\\Microsoft\\Fusion!EnableLog].\r\n"
}

**Comment by psouza4** [comment]
Reinstall Borderless Gaming.  You're missing all the files included in the
automatic install process.

**Comment by modioperandus** [comment]
I've reinstalled via Steam, same prob, and just reinstalled via the github download and got this.

{
  "ClassName": "System.AggregateException",
  "Message": "A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread.",
  "Data": null,
  "InnerException": {
    "ClassName": "System.IO.FileNotFoundException",
    "Message": "Could not load file or assembly 'System.Threading.Tasks, Version=1.5.11.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.",
    "Data": null,
    "InnerException": null,
    "HelpURL": null,
    "StackTraceString": "   at BorderlessGaming.BorderlessGaming.DoMainWork()\r\n   at System.Threading.Tasks.Task.InnerInvoke()\r\n   at System.Threading.Tasks.Task.Execute()",
    "RemoteStackTraceString": null,
    "RemoteStackIndex": 0,
    "ExceptionMethod": "8\nDoMainWork\nBorderlessGaming, Version=8.3.33015.555, Culture=neutral, PublicKeyToken=null\nBorderlessGaming.BorderlessGaming\nVoid DoMainWork()",
    "HResult": -2147024894,
    "Source": "BorderlessGaming",
    "WatsonBuckets": null,
    "FileNotFound_FileName": "System.Threading.Tasks, Version=1.5.11.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a",
    "FileNotFound_FusionLog": "WRN: Assembly binding logging is turned OFF.\r\nTo enable assembly bind failure logging, set the registry value [HKLM\\Software\\Microsoft\\Fusion!EnableLog] (DWORD) to 1.\r\nNote: There is some performance penalty associated with assembly bind failure logging.\r\nTo turn this feature off, remove the registry value [HKLM\\Software\\Microsoft\\Fusion!EnableLog].\r\n"
  },
  "HelpURL": null,
  "StackTraceString": "   at System.Threading.Tasks.TaskExceptionHolder.Finalize()",
  "RemoteStackTraceString": null,
  "RemoteStackIndex": 0,
  "ExceptionMethod": "8\nFinalize\nmscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089\nSystem.Threading.Tasks.TaskExceptionHolder\nVoid Finalize()",
  "HResult": -2146233088,
  "Source": "mscorlib",
  "WatsonBuckets": null,
  "InnerExceptions": [
    {
      "ClassName": "System.IO.FileNotFoundException",
      "Message": "Could not load file or assembly 'System.Threading.Tasks, Version=1.5.11.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.",
      "Data": null,
      "InnerException": null,
      "HelpURL": null,
      "StackTraceString": "   at BorderlessGaming.BorderlessGaming.DoMainWork()\r\n   at System.Threading.Tasks.Task.InnerInvoke()\r\n   at System.Threading.Tasks.Task.Execute()",
      "RemoteStackTraceString": null,
      "RemoteStackIndex": 0,
      "ExceptionMethod": "8\nDoMainWork\nBorderlessGaming, Version=8.3.33015.555, Culture=neutral, PublicKeyToken=null\nBorderlessGaming.BorderlessGaming\nVoid DoMainWork()",
      "HResult": -2147024894,
      "Source": "BorderlessGaming",
      "WatsonBuckets": null,
      "FileNotFound_FileName": "System.Threading.Tasks, Version=1.5.11.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a",
      "FileNotFound_FusionLog": "WRN: Assembly binding logging is turned OFF.\r\nTo enable assembly bind failure logging, set the registry value [HKLM\\Software\\Microsoft\\Fusion!EnableLog] (DWORD) to 1.\r\nNote: There is some performance penalty associated with assembly bind failure logging.\r\nTo turn this feature off, remove the registry value [HKLM\\Software\\Microsoft\\Fusion!EnableLog].\r\n"
    }
  ]
}

{
  "ClassName": "System.AggregateException",
  "Message": "A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread.",
  "Data": null,
  "InnerException": {
    "ClassName": "System.IO.FileNotFoundException",
    "Message": "Could not load file or assembly 'System.Threading.Tasks, Version=1.5.11.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.",
    "Data": null,
    "InnerException": null,
    "HelpURL": null,
    "StackTraceString": "   at BorderlessGaming.BorderlessGaming.DoMainWork()\r\n   at System.Threading.Tasks.Task.InnerInvoke()\r\n   at System.Threading.Tasks.Task.Execute()",
    "RemoteStackTraceString": null,
    "RemoteStackIndex": 0,
    "ExceptionMethod": "8\nDoMainWork\nBorderlessGaming, Version=8.3.33015.555, Culture=neutral, PublicKeyToken=null\nBorderlessGaming.BorderlessGaming\nVoid DoMainWork()",
    "HResult": -2147024894,
    "Source": "BorderlessGaming",
    "WatsonBuckets": null,
    "FileNotFound_FileName": "System.Threading.Tasks, Version=1.5.11.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a",
    "FileNotFound_FusionLog": "WRN: Assembly binding logging is turned OFF.\r\nTo enable assembly bind failure logging, set the registry value [HKLM\\Software\\Microsoft\\Fusion!EnableLog] (DWORD) to 1.\r\nNote: There is some performance penalty associated with assembly bind failure logging.\r\nTo turn this feature off, remove the registry value [HKLM\\Software\\Microsoft\\Fusion!EnableLog].\r\n"
  },
  "HelpURL": null,
  "StackTraceString": "   at System.Threading.Tasks.TaskExceptionHolder.Finalize()",
  "RemoteStackTraceString": null,
  "RemoteStackIndex": 0,
  "ExceptionMethod": "8\nFinalize\nmscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089\nSystem.Threading.Tasks.TaskExceptionHolder\nVoid Finalize()",
  "HResult": -2146233088,
  "Source": "mscorlib",
  "WatsonBuckets": null,
  "InnerExceptions": [
    {
      "ClassName": "System.IO.FileNotFoundException",
      "Message": "Could not load file or assembly 'System.Threading.Tasks, Version=1.5.11.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.",
      "Data": null,
      "InnerException": null,
      "HelpURL": null,
      "StackTraceString": "   at BorderlessGaming.BorderlessGaming.DoMainWork()\r\n   at System.Threading.Tasks.Task.InnerInvoke()\r\n   at System.Threading.Tasks.Task.Execute()",
      "RemoteStackTraceString": null,
      "RemoteStackIndex": 0,
      "ExceptionMethod": "8\nDoMainWork\nBorderlessGaming, Version=8.3.33015.555, Culture=neutral, PublicKeyToken=null\nBorderlessGaming.BorderlessGaming\nVoid DoMainWork()",
      "HResult": -2147024894,
      "Source": "BorderlessGaming",
      "WatsonBuckets": null,
      "FileNotFound_FileName": "System.Threading.Tasks, Version=1.5.11.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a",
      "FileNotFound_FusionLog": "WRN: Assembly binding logging is turned OFF.\r\nTo enable assembly bind failure logging, set the registry value [HKLM\\Software\\Microsoft\\Fusion!EnableLog] (DWORD) to 1.\r\nNote: There is some performance penalty associated with assembly bind failure logging.\r\nTo turn this feature off, remove the registry value [HKLM\\Software\\Microsoft\\Fusion!EnableLog].\r\n"
    }
  ]
}

{
  "ClassName": "System.AggregateException",
  "Message": "A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread.",
  "Data": null,
  "InnerException": {
    "ClassName": "System.IO.FileNotFoundException",
    "Message": "Could not load file or assembly 'System.Threading.Tasks, Version=1.5.11.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.",
    "Data": null,
    "InnerException": null,
    "HelpURL": null,
    "StackTraceString": "   at BorderlessGaming.BorderlessGaming.DoMainWork()\r\n   at System.Threading.Tasks.Task.InnerInvoke()\r\n   at System.Threading.Tasks.Task.Execute()",
    "RemoteStackTraceString": null,
    "RemoteStackIndex": 0,
    "ExceptionMethod": "8\nDoMainWork\nBorderlessGaming, Version=8.3.33015.555, Culture=neutral, PublicKeyToken=null\nBorderlessGaming.BorderlessGaming\nVoid DoMainWork()",
    "HResult": -2147024894,
    "Source": "BorderlessGaming",
    "WatsonBuckets": null,
    "FileNotFound_FileName": "System.Threading.Tasks, Version=1.5.11.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a",
    "FileNotFound_FusionLog": "WRN: Assembly binding logging is turned OFF.\r\nTo enable assembly bind failure logging, set the registry value [HKLM\\Software\\Microsoft\\Fusion!EnableLog] (DWORD) to 1.\r\nNote: There is some performance penalty associated with assembly bind failure logging.\r\nTo turn this feature off, remove the registry value [HKLM\\Software\\Microsoft\\Fusion!EnableLog].\r\n"
  },
  "HelpURL": null,
  "StackTraceString": "   at System.Threading.Tasks.TaskExceptionHolder.Finalize()",
  "RemoteStackTraceString": null,
  "RemoteStackIndex": 0,
  "ExceptionMethod": "8\nFinalize\nmscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089\nSystem.Threading.Tasks.TaskExceptionHolder\nVoid Finalize()",
  "HResult": -2146233088,
  "Source": "mscorlib",
  "WatsonBuckets": null,
  "InnerExceptions": [
    {
      "ClassName": "System.IO.FileNotFoundException",
      "Message": "Could not load file or assembly 'System.Threading.Tasks, Version=1.5.11.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.",
      "Data": null,
      "InnerException": null,
      "HelpURL": null,
      "StackTraceString": "   at BorderlessGaming.BorderlessGaming.DoMainWork()\r\n   at System.Threading.Tasks.Task.InnerInvoke()\r\n   at System.Threading.Tasks.Task.Execute()",
      "RemoteStackTraceString": null,
      "RemoteStackIndex": 0,
      "ExceptionMethod": "8\nDoMainWork\nBorderlessGaming, Version=8.3.33015.555, Culture=neutral, PublicKeyToken=null\nBorderlessGaming.BorderlessGaming\nVoid DoMainWork()",
      "HResult": -2147024894,
      "Source": "BorderlessGaming",
      "WatsonBuckets": null,
      "FileNotFound_FileName": "System.Threading.Tasks, Version=1.5.11.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a",
      "FileNotFound_FusionLog": "WRN: Assembly binding logging is turned OFF.\r\nTo enable assembly bind failure logging, set the registry value [HKLM\\Software\\Microsoft\\Fusion!EnableLog] (DWORD) to 1.\r\nNote: There is some performance penalty associated with assembly bind failure logging.\r\nTo turn this feature off, remove the registry value [HKLM\\Software\\Microsoft\\Fusion!EnableLog].\r\n"
    }
  ]
}

{
  "ClassName": "System.AggregateException",
  "Message": "A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread.",
  "Data": null,
  "InnerException": {
    "ClassName": "System.IO.FileNotFoundException",
    "Message": "Could not load file or assembly 'System.Threading.Tasks, Version=1.5.11.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.",
    "Data": null,
    "InnerException": null,
    "HelpURL": null,
    "StackTraceString": "   at BorderlessGaming.BorderlessGaming.DoMainWork()\r\n   at System.Threading.Tasks.Task.Execute()",
    "RemoteStackTraceString": null,
    "RemoteStackIndex": 0,
    "ExceptionMethod": "8\nDoMainWork\nBorderlessGaming, Version=8.3.33015.555, Culture=neutral, PublicKeyToken=null\nBorderlessGaming.BorderlessGaming\nVoid DoMainWork()",
    "HResult": -2147024894,
    "Source": "BorderlessGaming",
    "WatsonBuckets": null,
    "FileNotFound_FileName": "System.Threading.Tasks, Version=1.5.11.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a",
    "FileNotFound_FusionLog": "WRN: Assembly binding logging is turned OFF.\r\nTo enable assembly bind failure logging, set the registry value [HKLM\\Software\\Microsoft\\Fusion!EnableLog] (DWORD) to 1.\r\nNote: There is some performance penalty associated with assembly bind failure logging.\r\nTo turn this feature off, remove the registry value [HKLM\\Software\\Microsoft\\Fusion!EnableLog].\r\n"
  },
  "HelpURL": null,
  "StackTraceString": "   at System.Threading.Tasks.TaskExceptionHolder.Finalize()",
  "RemoteStackTraceString": null,
  "RemoteStackIndex": 0,
  "ExceptionMethod": "8\nFinalize\nmscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089\nSystem.Threading.Tasks.TaskExceptionHolder\nVoid Finalize()",
  "HResult": -2146233088,
  "Source": "mscorlib",
  "WatsonBuckets": null,
  "InnerExceptions": [
    {
      "ClassName": "System.IO.FileNotFoundException",
      "Message": "Could not load file or assembly 'System.Threading.Tasks, Version=1.5.11.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.",
      "Data": null,
      "InnerException": null,
      "HelpURL": null,
      "StackTraceString": "   at BorderlessGaming.BorderlessGaming.DoMainWork()\r\n   at System.Threading.Tasks.Task.Execute()",
      "RemoteStackTraceString": null,
      "RemoteStackIndex": 0,
      "ExceptionMethod": "8\nDoMainWork\nBorderlessGaming, Version=8.3.33015.555, Culture=neutral, PublicKeyToken=null\nBorderlessGaming.BorderlessGaming\nVoid DoMainWork()",
      "HResult": -2147024894,
      "Source": "BorderlessGaming",
      "WatsonBuckets": null,
      "FileNotFound_FileName": "System.Threading.Tasks, Version=1.5.11.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a",
      "FileNotFound_FusionLog": "WRN: Assembly binding logging is turned OFF.\r\nTo enable assembly bind failure logging, set the registry value [HKLM\\Software\\Microsoft\\Fusion!EnableLog] (DWORD) to 1.\r\nNote: There is some performance penalty associated with assembly bind failure logging.\r\nTo turn this feature off, remove the registry value [HKLM\\Software\\Microsoft\\Fusion!EnableLog].\r\n"
    }
  ]
}

**Comment by psouza4** [comment]
You may want to check the install path to verify files were written
successfully.  Clearly the program baby find or has no permission to load
its files and since I can't reproduce the problem nor anyone else reporting
an issue, it has to be something odd in your environment.

**Comment by psouza4** [comment]
*program can't find
