### ISSUE TITLE
What is the admin setup for?

### ISSUE THREAD

**Issue by mica** [Codeusa/Borderless-Gaming#213]
I'm not able to find any info. What's the purpose of the separate setup.exe?

**Comment by psouza4** [comment]
It embeds a manifest that requests UAC elevation so that Borderless Gaming is always run-as-administrator.  This gives it more flexibility when handling certain games, however it also means it can't be run at startup in Windows 8, 8.1, and 10.

**Comment by mica** [comment]
Ah, that's why I couldn't get it to run at startup. I'll have to give the standard setup a try. Have you found many games require this admin mode?

**Comment by psouza4** [comment]
Only a few obscure titles -- mostly MMOs with odd anti-cheat systems that also run with elevated permissions.

**Comment by mica** [comment]
Considering the missing startup support (an essential option for an app such as this, imo), it'd be worth making mention of this on the download page. Especially since it's such a fringe case where you'd actually need admin.
