### ISSUE TITLE
update sucks

### ISSUE THREAD

**Issue by k0377** [Codeusa/Borderless-Gaming#214]
Don't get me wrong, but do I really have to update each time manually? Already updated to 8.3 a few days ago, now there is 8.4. It is annoying as hell, to do this each time by hand, not to mention the update message every startup. Isn't there any better, sleek way to update borderless gaming without get my hands dirty? I think I should stick with steam version then...

**Comment by psouza4** [comment]
Turn off update notifications if you're annoyed by two updates since August.  Or like you said: use the Steam version.

**Comment by k0377** [comment]
yeah cool, this is how windows users solve problems! life could be dat ez...
