### ISSUE TITLE
Unable to save favourites on Windows launch

### ISSUE THREAD

**Issue by addrum** [Codeusa/Borderless-Gaming#215]
![image](https://cloud.githubusercontent.com/assets/2855069/11513651/4491c47e-986c-11e5-83a3-7728d015bba7.png)

This is on an administrator account.

**Comment by psouza4** [comment]
Do you possibly have Borderless Gaming running multiple times?

**Comment by addrum** [comment]
I was about to add that it launches itself multiple times on Windows startup too:
![image](https://cloud.githubusercontent.com/assets/2855069/11513693/7f0f66e2-986c-11e5-9f5e-4ff965fa10ac.png)

**Comment by psouza4** [comment]
Sounds like you need to delete the extra shortcuts in your Startup folder.  :)
