### ISSUE TITLE
Thread Exception Caught?  Makes 8.4 and All Previous Versions Unusable 

### ISSUE THREAD

**Issue by Zak0221** [Codeusa/Borderless-Gaming#216]
I simply installed the latest release and it gave me this error.  

"Thread Exception Caught"  

Below is the log file for the error. Note:  This error now persists on all previous versions of the software once having introduced the error into my system.

From the logs-

{
  "ClassName": "System.IO.FileNotFoundException",
  "Message": "Could not load file or assembly 'System.Threading.Tasks, Version=2.6.8.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.",
  "Data": null,
  "InnerException": null,
  "HelpURL": null,
  "StackTraceString": "   at BorderlessGaming.Forms.MainWindow.viewFullProcessDetailsToolStripMenuItem_CheckedChanged(Object sender, EventArgs e)\r\n   at System.Windows.Forms.ToolStripMenuItem.set_CheckState(CheckState value)\r\n   at System.Windows.Forms.ToolStripMenuItem.set_Checked(Boolean value)\r\n   at BorderlessGaming.Forms.MainWindow.MainWindow_Load(Object sender, EventArgs e)\r\n   at System.Windows.Forms.Form.OnLoad(EventArgs e)\r\n   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)\r\n   at System.Windows.Forms.Control.CreateControl()\r\n   at System.Windows.Forms.Control.WmShowWindow(Message& m)\r\n   at System.Windows.Forms.Control.WndProc(Message& m)\r\n   at System.Windows.Forms.Form.WmShowWindow(Message& m)\r\n   at System.Windows.Forms.Form.WndProc(Message& m)\r\n   at BorderlessGaming.Forms.MainWindow.WndProc(Message& m)\r\n   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)",
  "RemoteStackTraceString": null,
  "RemoteStackIndex": 0,
  "ExceptionMethod": "8\nviewFullProcessDetailsToolStripMenuItem_CheckedChanged\nBorderlessGaming, Version=8.3.33015.555, Culture=neutral, PublicKeyToken=null\nBorderlessGaming.Forms.MainWindow\nVoid viewFullProcessDetailsToolStripMenuItem_CheckedChanged(System.Object, System.EventArgs)",
  "HResult": -2147024894,
  "Source": "BorderlessGaming",
  "WatsonBuckets": null,
  "FileNotFound_FileName": "System.Threading.Tasks, Version=2.6.8.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a",
  "FileNotFound_FusionLog": "WRN: Assembly binding logging is turned OFF.\r\nTo enable assembly bind failure logging, set the registry value [HKLM\\Software\\Microsoft\\Fusion!EnableLog] (DWORD) to 1.\r\nNote: There is some performance penalty associated with assembly bind failure logging.\r\nTo turn this feature off, remove the registry value [HKLM\\Software\\Microsoft\\Fusion!EnableLog].\r\n"
}

Please help - this software is a godsend and its unusable thanks to your latest release.

**Comment by psouza4** [comment]
Hi -- this is not the latest release, this is an older 8.3 build.  A newer 8.3 build is available as well as an 8.4 build.  Please install 8.4.

**Comment by psouza4** [comment]
(FYI, this tells me right here you were still using 8.3:  ""ExceptionMethod": "8\nviewFullProcessDetailsToolStripMenuItem_CheckedChanged\nBorderlessGaming, Version=8.3.33015.555, Culture=neutral, ")

**Comment by Zak0221** [comment]
I did install 8.4 I will post again
