### ISSUE TITLE
Just Installed 8.4 ( as per previous bug report ) and same issue persists

### ISSUE THREAD

**Issue by Zak0221** [Codeusa/Borderless-Gaming#217]
Here is error log dump - I just installed 8.4 

{
  "ClassName": "System.IO.FileNotFoundException",
  "Message": "Could not load file or assembly 'System.Threading.Tasks, Version=2.6.8.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.",
  "Data": null,
  "InnerException": null,
  "HelpURL": null,
  "StackTraceString": "   at BorderlessGaming.Forms.MainWindow.viewFullProcessDetailsToolStripMenuItem_CheckedChanged(Object sender, EventArgs e)\r\n   at System.Windows.Forms.ToolStripMenuItem.set_CheckState(CheckState value)\r\n   at System.Windows.Forms.ToolStripMenuItem.set_Checked(Boolean value)\r\n   at BorderlessGaming.Forms.MainWindow.MainWindow_Load(Object sender, EventArgs e)\r\n   at System.Windows.Forms.Form.OnLoad(EventArgs e)\r\n   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)\r\n   at System.Windows.Forms.Control.CreateControl()\r\n   at System.Windows.Forms.Control.WmShowWindow(Message& m)\r\n   at System.Windows.Forms.Control.WndProc(Message& m)\r\n   at System.Windows.Forms.Form.WmShowWindow(Message& m)\r\n   at System.Windows.Forms.Form.WndProc(Message& m)\r\n   at BorderlessGaming.Forms.MainWindow.WndProc(Message& m)\r\n   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)",
  "RemoteStackTraceString": null,
  "RemoteStackIndex": 0,
  "ExceptionMethod": "8\nviewFullProcessDetailsToolStripMenuItem_CheckedChanged\nBorderlessGaming, Version=8.4.33315.1328, Culture=neutral, PublicKeyToken=null\nBorderlessGaming.Forms.MainWindow\nVoid viewFullProcessDetailsToolStripMenuItem_CheckedChanged(System.Object, System.EventArgs)",
  "HResult": -2147024894,
  "Source": "BorderlessGaming",
  "WatsonBuckets": null,
  "FileNotFound_FileName": "System.Threading.Tasks, Version=2.6.8.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a",
  "FileNotFound_FusionLog": "WRN: Assembly binding logging is turned OFF.\r\nTo enable assembly bind failure logging, set the registry value [HKLM\\Software\\Microsoft\\Fusion!EnableLog] (DWORD) to 1.\r\nNote: There is some performance penalty associated with assembly bind failure logging.\r\nTo turn this feature off, remove the registry value [HKLM\\Software\\Microsoft\\Fusion!EnableLog].\r\n"
}

same problem - and this will continue to occur even when I uninstall and install previous versions that were just working literally this morning before I installed 8.4

**Comment by Zak0221** [comment]
No programs will appear in the Borderless Gaming Application and this error will continue to persist even when I uninstall and reinstall other versions after many restarts 

Never had an issue with this software til I installed 8.4 release today.

**Comment by psouza4** [comment]
System.Threading.Tasks is part of the [.NET 4.5 and 4.6 framework from Microsoft](https://www.microsoft.com/en-us/download/details.aspx?id=30653).

Are you perhaps missing this required Windows component?

> "ClassName": "System.IO.FileNotFoundException",
"Message": "Could not load file or assembly 'System.Threading.Tasks, Version=2.6.8.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.",

https://msdn.microsoft.com/en-us/library/system.threading.tasks(v=vs.110).aspx

**Comment by Zak0221** [comment]
What windows component would I be missing ?  like I said I had zero problems with my computer, your software or this error until I installed 8.4

**Comment by psouza4** [comment]
Go back and read my message.

I described the potentially missing component and linked to the download page at Microsoft.  I can't be any clearer than that.

**Comment by Zak0221** [comment]
I see your link now looking at that

**Comment by Zak0221** [comment]
I am running Windows 7 tho

**Comment by Zak0221** [comment]
after installing what you linked - I will try to uninstall and reinstall 8.4

**Comment by Zak0221** [comment]
also I only see a link to the 4.5 Framework would I need the 4.6 one?

**Comment by Zak0221** [comment]
4.5 Framework fixed my issue  - the program installed properly and is working now thank you very much

**Comment by psouza4** [comment]
Glad to hear it!
