### ISSUE TITLE
Non-admin 8.4 setup appears to install admin version

### ISSUE THREAD

**Issue by tornewuff** [Codeusa/Borderless-Gaming#222]
BG 8.4 seems to run as administrator even when installed using the non-admin setup executable. I uninstalled it and used the non-admin 8.3 installer and everything was fine there. Tried a few times including deleting settings, is the non-admin setup being built incorrectly?

**Comment by Acecool** [comment]
And both don't allow saving data ( every relaunch the data needs to be re-entered with errors popping up )

**Comment by mica** [comment]
This must be why run at startup isn't working. Hope you can get it sorted.
