### ISSUE TITLE
BUG: Error saving "favorites" on Admin version running on Admin Account in Admin mode and on Non-Admin version.

### ISSUE THREAD

**Issue by Acecool** [Codeusa/Borderless-Gaming#225]
This error appears when adding a new item to the list or when opening 

Trying to open the "data" folder opens "Libraries".

I initially installed the admin version on an admin account running it as administrator to no avail. I then uninstalled it and tried non-admin version with the same issues.

Apparently the upload didn't work. Here's the image: 
![Error](https://dl.dropboxusercontent.com/u/26074909/Screenshots/BorderlessGaming/Screenshot%202016-01-02%2020.13.45.png)

![Uploading Screenshot 2016-01-02 20.13.45.png…]()
![Uploading Screenshot 2016-01-02 20.13.45.png…]()
![Uploading Screenshot 2016-01-02 20.13.45.png…]()
![Uploading Screenshot 2016-01-02 20.13.45.png…]()

**Comment by Acecool** [comment]
Posted an in-depth Steam Discussion Topic: http://steamcommunity.com/app/388080/discussions/0/451850213953761897/

Unable to save favorites ( No permissions ) despite using admin version on admin account running in admin mode; also tried non-admin version ( currently running )
https://dl.dropboxusercontent.com/u/26074909/Screenshots/BorderlessGaming/Screenshot%202016-01-02%2020.13.45.png

I initially installed the admin version on an admin account running as admin ( and set the app to run as admin ) but the above issue appeared.

I uninstalled the admin version and then installed the non-admin version; the same issue appears.


The registry options exist and are shown here: https://dl.dropboxusercontent.com/u/26074909/Screenshots/BorderlessGaming/registry.reg

The folder: %AppData%\Codeusa Software\Borderless Gaming\ exists with nothing contained within.

I've tried replacing the Newtonsoft.Json.dll with a newer version ( Requiring .NET 4.0 as the current DLL registers ) from https://github.com/JamesNK/Newtonsoft.Json/releases to no avail. I've tried all of the latest ( 11 days old ) dlls with no luck and I've tried the obvious choices ( Portable and 40, non portable 45 and 40 ) of the ones that were available June 2015 to no avail leading me to believe that since it is open-source, some changes were made to the dll and compiled especially for this project instead of creating a bridge to allow for seamless transitions with updated dlls. I also tried the January 2015 DLLs. Other branches tried with no luck such as ( http://json.codeplex.com/downloads/get/1533572# )

No luck. Using other Dlls causes the program to fail completely instead of launching with a custom exception ( which isn't caught by your exception handler ).


Below is some more information regarding steps taken..
----------------------------------------

The data folder opens as "Libraries"? I've searched the registry for keys and values relating to "BorderlessGaming", "Borderless", "Borderless Gaming", etc...

I have .NET ( 4.0, 4.5, etc... ) plus C++ redistributables and redistributables from several other languages ( Java, etc.. )... The error seems to stem from Newtonsoft.Json.dll in "C:\Program Files (x86)\Borderless Gaming"... ( Again, no config file located here )...

I've looked through: https://github.com/Codeusa/Borderless-Gaming/blob/master/Utilities/AppEnvironment.cs ( and the app info folder and file for company name, etc.. ) to determine potential registry key location and folder locations.
There are several possibilities for folder location ( Note: Company is "Codeusa Software" and App is "Borderless Gaming" ):

It looks here first: %AppData%\<Company>\<App>

Then it goes through the motions of checking each of these in order:

Last known file path ( using sub-string from starting-index [ 0 ] to last \ )

Executable-Path ( using sub-string from starting-index [ 0 ] to last \ ) which would be: "C:\Program Files (x86)\Borderless Gaming\BorderlessGaming.exe" sub-stringed to: "C:\Program Files (x86)\Borderless Gaming\" excluding "s. -- This path does exist but instead of using it, it uses libraries...

Current working folder ( which should be "C:\Program Files (x86)\Borderless Gaming" without the last \ )

User Desktop ( Location varies per OS but they're grabbing it from Environment Variables so it'll be accurate despite OS ).

"." which should be the current ( working ) directory.

This should be standardized... Always have an ending slash, or not instead of sometimes yes, sometimes no, sometimes something else... It should only need to be: AppData ... OR application path... ( which would allow the app to function as a portable application if the installer wasn't used [ or if the installer didn't create the path in app data ] instead of allowing it to go on a goose-change to determine a directory )

The Get* Path function is repeated in at least 2 files.

**Comment by Acecool** [comment]
I've also tried sharing the "%AppData%\Codeusa Software\Borderless Gaming" folder, allowing Everyone full access ( In the event the JSON dll accesses files [ if it does this part ] via networking addresses, ie \\<Computer-Name>\$C, etc.. [ although this is highly unlikely, and I haven't looked into the code of that just yet because I haven't found a github branch which actually works as a drop-in leaving me to believe it has been modified ).

I also set the permissions under Security to allow Everyone full control ( both Codeusa Software and Borderless Gaming folders ). No luck reading / saving / creating favorites regardless of running with admin permissions..

**Comment by Acecool** [comment]
Note, also tried versions 8.0 onward with the same combinations with, essentially, the same results

**Comment by Acecool** [comment]
I added "Favorites.json" to my C:\Users\<user>\AppData\Roaming\Codeusa Software\Borderless Gaming folder... I no longer get the error on startup about not being able to read favorites... But, it doesn't read the file. I still get the error when trying to add a program.

So this is an issue of not creating the file and trying to read from too many different folder locations.... I'm going to add the Favorites.json file to each of the folders it reads from until it doesn't error AND reads... Also, I set permissions of the folders and file to everyone without resolving the issue. Running BG in admin mode does nothing.

**Comment by Acecool** [comment]
Adding it to: C:\Program Files (x86)\Borderless Gaming and setting permissions to everyone doesn't change anything.
Keeping it in the above folder and removing from the roaming folder remains the same. Unable to read, displays error on add but removes error on startup .

**Comment by Acecool** [comment]
Adding to my desktop without it being in the exec path, with everyone permissions, shows error on startup, won't read / update... User desktop IS one of the paths that is checked, but it doesn't seem to be falling through to check there.

**Comment by Acecool** [comment]
This is still a major issue...

**Comment by Codeusa** [comment]
Pretty sure this might just be a bug in newton so i'll update the library

**Comment by Acecool** [comment]
It seems it was a Windows 7 x64 Pro issue where the .net framework installation could become "screwed beyond recognition" and uninstalling / reinstalling / using utility to completely uninstall / etc... wouldn't properly remove the files so when you went to install a new version it would claim a newer one is already installed ( but it couldn't find the files )...

When I upgraded to 10 ( Did upgrade on laptop to generate key then fresh install on my primary computer with said key [ which was before the 7 key was working with 10 install ] and everything works as expected )...
