### ISSUE TITLE
Tony Hawk's Pro Skater 2

### ISSUE THREAD

**Issue by Catarax** [Codeusa/Borderless-Gaming#234]
The previous issue was closed because i didn't gave much information.

So when playing Tony Hawk's Pro Skater 2, it's unpossible during the game to do alt+tab and add the  game process to Borderless Gaming. Alt+Tab keys doesn't run at all and i must exit the game to come back to windows. The game is designed like that.

Win+F6 doesn't work also in-game (if it enables borderless gaming).
A feature to add a previous process or creating a favorite by selecting an .exe would be nice.

Thanks!

**Comment by Keith94** [comment]
This would be covered by #167
