### ISSUE TITLE
Can't even start the program...

### ISSUE THREAD

**Issue by Costinux** [Codeusa/Borderless-Gaming#235]
"An Unhandled Exception was Caught and Logged to: C:\Users\"Computer Name"\AppData\Roaming\Codeusa Software\BorderlessGaming\Logs..."
This is the log:

{
  "ClassName": "System.AggregateException",
  "Message": "A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread.",
  "Data": null,
  "InnerException": {
    "ClassName": "System.IO.FileLoadException",
    "Message": "Could not load file or assembly 'System.Threading.Tasks, Version=1.5.11.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)",
    "Data": null,
    "InnerException": null,
    "HelpURL": null,
    "StackTraceString": "   at BorderlessGaming.BorderlessGaming.DoMainWork()\r\n   at System.Threading.Tasks.Task.InnerInvoke()\r\n   at System.Threading.Tasks.Task.Execute()",
    "RemoteStackTraceString": null,
    "RemoteStackIndex": 0,
    "ExceptionMethod": "8\nDoMainWork\nBorderlessGaming, Version=8.4.33315.1328, Culture=neutral, PublicKeyToken=null\nBorderlessGaming.BorderlessGaming\nVoid DoMainWork()",
    "HResult": -2146234304,
    "Source": "BorderlessGaming",
    "WatsonBuckets": null,
    "FileLoad_FileName": "System.Threading.Tasks, Version=1.5.11.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a",
    "FileLoad_FusionLog": "WRN: Assembly binding logging is turned OFF.\r\nTo enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog](DWORD) to 1.\r\nNote: There is some performance penalty associated with assembly bind failure logging.\r\nTo turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].\r\n"
  },
  "HelpURL": null,
  "StackTraceString": "   at System.Threading.Tasks.TaskExceptionHolder.Finalize()",
  "RemoteStackTraceString": null,
  "RemoteStackIndex": 0,
  "ExceptionMethod": "8\nFinalize\nmscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089\nSystem.Threading.Tasks.TaskExceptionHolder\nVoid Finalize()",
  "HResult": -2146233088,
  "Source": "mscorlib",
  "WatsonBuckets": null,
  "InnerExceptions": [
    {
      "ClassName": "System.IO.FileLoadException",
      "Message": "Could not load file or assembly 'System.Threading.Tasks, Version=1.5.11.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)",
      "Data": null,
      "InnerException": null,
      "HelpURL": null,
      "StackTraceString": "   at BorderlessGaming.BorderlessGaming.DoMainWork()\r\n   at System.Threading.Tasks.Task.InnerInvoke()\r\n   at System.Threading.Tasks.Task.Execute()",
      "RemoteStackTraceString": null,
      "RemoteStackIndex": 0,
      "ExceptionMethod": "8\nDoMainWork\nBorderlessGaming, Version=8.4.33315.1328, Culture=neutral, PublicKeyToken=null\nBorderlessGaming.BorderlessGaming\nVoid DoMainWork()",
      "HResult": -2146234304,
      "Source": "BorderlessGaming",
      "WatsonBuckets": null,
      "FileLoad_FileName": "System.Threading.Tasks, Version=1.5.11.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a",
      "FileLoad_FusionLog": "WRN: Assembly binding logging is turned OFF.\r\nTo enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog](DWORD) to 1.\r\nNote: There is some performance penalty associated with assembly bind failure logging.\r\nTo turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].\r\n"
    }
  ]
}

{
  "ClassName": "System.AggregateException",
  "Message": "A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread.",
  "Data": null,
  "InnerException": {
    "ClassName": "System.IO.FileLoadException",
    "Message": "Could not load file or assembly 'System.Threading.Tasks, Version=1.5.11.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)",
    "Data": null,
    "InnerException": null,
    "HelpURL": null,
    "StackTraceString": "   at BorderlessGaming.BorderlessGaming.DoMainWork()\r\n   at System.Threading.Tasks.Task.InnerInvoke()\r\n   at System.Threading.Tasks.Task.Execute()",
    "RemoteStackTraceString": null,
    "RemoteStackIndex": 0,
    "ExceptionMethod": "8\nDoMainWork\nBorderlessGaming, Version=8.4.33315.1328, Culture=neutral, PublicKeyToken=null\nBorderlessGaming.BorderlessGaming\nVoid DoMainWork()",
    "HResult": -2146234304,
    "Source": "BorderlessGaming",
    "WatsonBuckets": null,
    "FileLoad_FileName": "System.Threading.Tasks, Version=1.5.11.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a",
    "FileLoad_FusionLog": "WRN: Assembly binding logging is turned OFF.\r\nTo enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog](DWORD) to 1.\r\nNote: There is some performance penalty associated with assembly bind failure logging.\r\nTo turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].\r\n"
  },
  "HelpURL": null,
  "StackTraceString": "   at System.Threading.Tasks.TaskExceptionHolder.Finalize()",
  "RemoteStackTraceString": null,
  "RemoteStackIndex": 0,
  "ExceptionMethod": "8\nFinalize\nmscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089\nSystem.Threading.Tasks.TaskExceptionHolder\nVoid Finalize()",
  "HResult": -2146233088,
  "Source": "mscorlib",
  "WatsonBuckets": null,
  "InnerExceptions": [
    {
      "ClassName": "System.IO.FileLoadException",
      "Message": "Could not load file or assembly 'System.Threading.Tasks, Version=1.5.11.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)",
      "Data": null,
      "InnerException": null,
      "HelpURL": null,
      "StackTraceString": "   at BorderlessGaming.BorderlessGaming.DoMainWork()\r\n   at System.Threading.Tasks.Task.InnerInvoke()\r\n   at System.Threading.Tasks.Task.Execute()",
      "RemoteStackTraceString": null,
      "RemoteStackIndex": 0,
      "ExceptionMethod": "8\nDoMainWork\nBorderlessGaming, Version=8.4.33315.1328, Culture=neutral, PublicKeyToken=null\nBorderlessGaming.BorderlessGaming\nVoid DoMainWork()",
      "HResult": -2146234304,
      "Source": "BorderlessGaming",
      "WatsonBuckets": null,
      "FileLoad_FileName": "System.Threading.Tasks, Version=1.5.11.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a",
      "FileLoad_FusionLog": "WRN: Assembly binding logging is turned OFF.\r\nTo enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog](DWORD) to 1.\r\nNote: There is some performance penalty associated with assembly bind failure logging.\r\nTo turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].\r\n"
    }
  ]
}

{
  "ClassName": "System.AggregateException",
  "Message": "A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread.",
  "Data": null,
  "InnerException": {
    "ClassName": "System.IO.FileLoadException",
    "Message": "Could not load file or assembly 'System.Threading.Tasks, Version=1.5.11.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)",
    "Data": null,
    "InnerException": null,
    "HelpURL": null,
    "StackTraceString": "   at BorderlessGaming.BorderlessGaming.DoMainWork()\r\n   at System.Threading.Tasks.Task.InnerInvoke()\r\n   at System.Threading.Tasks.Task.Execute()",
    "RemoteStackTraceString": null,
    "RemoteStackIndex": 0,
    "ExceptionMethod": "8\nDoMainWork\nBorderlessGaming, Version=8.4.33315.1328, Culture=neutral, PublicKeyToken=null\nBorderlessGaming.BorderlessGaming\nVoid DoMainWork()",
    "HResult": -2146234304,
    "Source": "BorderlessGaming",
    "WatsonBuckets": null,
    "FileLoad_FileName": "System.Threading.Tasks, Version=1.5.11.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a",
    "FileLoad_FusionLog": "WRN: Assembly binding logging is turned OFF.\r\nTo enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog](DWORD) to 1.\r\nNote: There is some performance penalty associated with assembly bind failure logging.\r\nTo turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].\r\n"
  },
  "HelpURL": null,
  "StackTraceString": "   at System.Threading.Tasks.TaskExceptionHolder.Finalize()",
  "RemoteStackTraceString": null,
  "RemoteStackIndex": 0,
  "ExceptionMethod": "8\nFinalize\nmscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089\nSystem.Threading.Tasks.TaskExceptionHolder\nVoid Finalize()",
  "HResult": -2146233088,
  "Source": "mscorlib",
  "WatsonBuckets": null,
  "InnerExceptions": [
    {
      "ClassName": "System.IO.FileLoadException",
      "Message": "Could not load file or assembly 'System.Threading.Tasks, Version=1.5.11.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)",
      "Data": null,
      "InnerException": null,
      "HelpURL": null,
      "StackTraceString": "   at BorderlessGaming.BorderlessGaming.DoMainWork()\r\n   at System.Threading.Tasks.Task.InnerInvoke()\r\n   at System.Threading.Tasks.Task.Execute()",
      "RemoteStackTraceString": null,
      "RemoteStackIndex": 0,
      "ExceptionMethod": "8\nDoMainWork\nBorderlessGaming, Version=8.4.33315.1328, Culture=neutral, PublicKeyToken=null\nBorderlessGaming.BorderlessGaming\nVoid DoMainWork()",
      "HResult": -2146234304,
      "Source": "BorderlessGaming",
      "WatsonBuckets": null,
      "FileLoad_FileName": "System.Threading.Tasks, Version=1.5.11.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a",
      "FileLoad_FusionLog": "WRN: Assembly binding logging is turned OFF.\r\nTo enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog](DWORD) to 1.\r\nNote: There is some performance penalty associated with assembly bind failure logging.\r\nTo turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].\r\n"
    }
  ]
}

{
  "ClassName": "System.AggregateException",
  "Message": "A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread.",
  "Data": null,
  "InnerException": {
    "ClassName": "System.IO.FileLoadException",
    "Message": "Could not load file or assembly 'System.Threading.Tasks, Version=1.5.11.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)",
    "Data": null,
    "InnerException": null,
    "HelpURL": null,
    "StackTraceString": "   at BorderlessGaming.BorderlessGaming.DoMainWork()\r\n   at System.Threading.Tasks.Task.InnerInvoke()\r\n   at System.Threading.Tasks.Task.Execute()",
    "RemoteStackTraceString": null,
    "RemoteStackIndex": 0,
    "ExceptionMethod": "8\nDoMainWork\nBorderlessGaming, Version=8.4.33315.1328, Culture=neutral, PublicKeyToken=null\nBorderlessGaming.BorderlessGaming\nVoid DoMainWork()",
    "HResult": -2146234304,
    "Source": "BorderlessGaming",
    "WatsonBuckets": null,
    "FileLoad_FileName": "System.Threading.Tasks, Version=1.5.11.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a",
    "FileLoad_FusionLog": "WRN: Assembly binding logging is turned OFF.\r\nTo enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog](DWORD) to 1.\r\nNote: There is some performance penalty associated with assembly bind failure logging.\r\nTo turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].\r\n"
  },
  "HelpURL": null,
  "StackTraceString": "   at System.Threading.Tasks.TaskExceptionHolder.Finalize()",
  "RemoteStackTraceString": null,
  "RemoteStackIndex": 0,
  "ExceptionMethod": "8\nFinalize\nmscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089\nSystem.Threading.Tasks.TaskExceptionHolder\nVoid Finalize()",
  "HResult": -2146233088,
  "Source": "mscorlib",
  "WatsonBuckets": null,
  "InnerExceptions": [
    {
      "ClassName": "System.IO.FileLoadException",
      "Message": "Could not load file or assembly 'System.Threading.Tasks, Version=1.5.11.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)",
      "Data": null,
      "InnerException": null,
      "HelpURL": null,
      "StackTraceString": "   at BorderlessGaming.BorderlessGaming.DoMainWork()\r\n   at System.Threading.Tasks.Task.InnerInvoke()\r\n   at System.Threading.Tasks.Task.Execute()",
      "RemoteStackTraceString": null,
      "RemoteStackIndex": 0,
      "ExceptionMethod": "8\nDoMainWork\nBorderlessGaming, Version=8.4.33315.1328, Culture=neutral, PublicKeyToken=null\nBorderlessGaming.BorderlessGaming\nVoid DoMainWork()",
      "HResult": -2146234304,
      "Source": "BorderlessGaming",
      "WatsonBuckets": null,
      "FileLoad_FileName": "System.Threading.Tasks, Version=1.5.11.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a",
      "FileLoad_FusionLog": "WRN: Assembly binding logging is turned OFF.\r\nTo enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog](DWORD) to 1.\r\nNote: There is some performance penalty associated with assembly bind failure logging.\r\nTo turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].\r\n"
    }
  ]
}

{
  "ClassName": "System.AggregateException",
  "Message": "A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread.",
  "Data": null,
  "InnerException": {
    "ClassName": "System.IO.FileLoadException",
    "Message": "Could not load file or assembly 'System.Threading.Tasks, Version=1.5.11.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)",
    "Data": null,
    "InnerException": null,
    "HelpURL": null,
    "StackTraceString": "   at BorderlessGaming.BorderlessGaming.DoMainWork()\r\n   at System.Threading.Tasks.Task.InnerInvoke()\r\n   at System.Threading.Tasks.Task.Execute()",
    "RemoteStackTraceString": null,
    "RemoteStackIndex": 0,
    "ExceptionMethod": "8\nDoMainWork\nBorderlessGaming, Version=8.4.33315.1328, Culture=neutral, PublicKeyToken=null\nBorderlessGaming.BorderlessGaming\nVoid DoMainWork()",
    "HResult": -2146234304,
    "Source": "BorderlessGaming",
    "WatsonBuckets": null,
    "FileLoad_FileName": "System.Threading.Tasks, Version=1.5.11.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a",
    "FileLoad_FusionLog": "WRN: Assembly binding logging is turned OFF.\r\nTo enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog](DWORD) to 1.\r\nNote: There is some performance penalty associated with assembly bind failure logging.\r\nTo turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].\r\n"
  },
  "HelpURL": null,
  "StackTraceString": "   at System.Threading.Tasks.TaskExceptionHolder.Finalize()",
  "RemoteStackTraceString": null,
  "RemoteStackIndex": 0,
  "ExceptionMethod": "8\nFinalize\nmscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089\nSystem.Threading.Tasks.TaskExceptionHolder\nVoid Finalize()",
  "HResult": -2146233088,
  "Source": "mscorlib",
  "WatsonBuckets": null,
  "InnerExceptions": [
    {
      "ClassName": "System.IO.FileLoadException",
      "Message": "Could not load file or assembly 'System.Threading.Tasks, Version=1.5.11.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)",
      "Data": null,
      "InnerException": null,
      "HelpURL": null,
      "StackTraceString": "   at BorderlessGaming.BorderlessGaming.DoMainWork()\r\n   at System.Threading.Tasks.Task.InnerInvoke()\r\n   at System.Threading.Tasks.Task.Execute()",
      "RemoteStackTraceString": null,
      "RemoteStackIndex": 0,
      "ExceptionMethod": "8\nDoMainWork\nBorderlessGaming, Version=8.4.33315.1328, Culture=neutral, PublicKeyToken=null\nBorderlessGaming.BorderlessGaming\nVoid DoMainWork()",
      "HResult": -2146234304,
      "Source": "BorderlessGaming",
      "WatsonBuckets": null,
      "FileLoad_FileName": "System.Threading.Tasks, Version=1.5.11.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a",
      "FileLoad_FusionLog": "WRN: Assembly binding logging is turned OFF.\r\nTo enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog](DWORD) to 1.\r\nNote: There is some performance penalty associated with assembly bind failure logging.\r\nTo turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].\r\n"
    }
  ]
}

{
  "ClassName": "System.AggregateException",
  "Message": "A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread.",
  "Data": null,
  "InnerException": {
    "ClassName": "System.IO.FileLoadException",
    "Message": "Could not load file or assembly 'System.Threading.Tasks, Version=1.5.11.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)",
    "Data": null,
    "InnerException": null,
    "HelpURL": null,
    "StackTraceString": "   at BorderlessGaming.BorderlessGaming.DoMainWork()\r\n   at System.Threading.Tasks.Task.InnerInvoke()\r\n   at System.Threading.Tasks.Task.Execute()",
    "RemoteStackTraceString": null,
    "RemoteStackIndex": 0,
    "ExceptionMethod": "8\nDoMainWork\nBorderlessGaming, Version=8.4.33315.1328, Culture=neutral, PublicKeyToken=null\nBorderlessGaming.BorderlessGaming\nVoid DoMainWork()",
    "HResult": -2146234304,
    "Source": "BorderlessGaming",
    "WatsonBuckets": null,
    "FileLoad_FileName": "System.Threading.Tasks, Version=1.5.11.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a",
    "FileLoad_FusionLog": "WRN: Assembly binding logging is turned OFF.\r\nTo enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog](DWORD) to 1.\r\nNote: There is some performance penalty associated with assembly bind failure logging.\r\nTo turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].\r\n"
  },
  "HelpURL": null,
  "StackTraceString": "   at System.Threading.Tasks.TaskExceptionHolder.Finalize()",
  "RemoteStackTraceString": null,
  "RemoteStackIndex": 0,
  "ExceptionMethod": "8\nFinalize\nmscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089\nSystem.Threading.Tasks.TaskExceptionHolder\nVoid Finalize()",
  "HResult": -2146233088,
  "Source": "mscorlib",
  "WatsonBuckets": null,
  "InnerExceptions": [
    {
      "ClassName": "System.IO.FileLoadException",
      "Message": "Could not load file or assembly 'System.Threading.Tasks, Version=1.5.11.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)",
      "Data": null,
      "InnerException": null,
      "HelpURL": null,
      "StackTraceString": "   at BorderlessGaming.BorderlessGaming.DoMainWork()\r\n   at System.Threading.Tasks.Task.InnerInvoke()\r\n   at System.Threading.Tasks.Task.Execute()",
      "RemoteStackTraceString": null,
      "RemoteStackIndex": 0,
      "ExceptionMethod": "8\nDoMainWork\nBorderlessGaming, Version=8.4.33315.1328, Culture=neutral, PublicKeyToken=null\nBorderlessGaming.BorderlessGaming\nVoid DoMainWork()",
      "HResult": -2146234304,
      "Source": "BorderlessGaming",
      "WatsonBuckets": null,
      "FileLoad_FileName": "System.Threading.Tasks, Version=1.5.11.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a",
      "FileLoad_FusionLog": "WRN: Assembly binding logging is turned OFF.\r\nTo enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog](DWORD) to 1.\r\nNote: There is some performance penalty associated with assembly bind failure logging.\r\nTo turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].\r\n"
    }
  ]
}

{
  "ClassName": "System.AggregateException",
  "Message": "A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread.",
  "Data": null,
  "InnerException": {
    "ClassName": "System.IO.FileLoadException",
    "Message": "Could not load file or assembly 'System.Threading.Tasks, Version=1.5.11.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)",
    "Data": null,
    "InnerException": null,
    "HelpURL": null,
    "StackTraceString": "   at BorderlessGaming.BorderlessGaming.DoMainWork()\r\n   at System.Threading.Tasks.Task.InnerInvoke()\r\n   at System.Threading.Tasks.Task.Execute()",
    "RemoteStackTraceString": null,
    "RemoteStackIndex": 0,
    "ExceptionMethod": "8\nDoMainWork\nBorderlessGaming, Version=8.4.33315.1328, Culture=neutral, PublicKeyToken=null\nBorderlessGaming.BorderlessGaming\nVoid DoMainWork()",
    "HResult": -2146234304,
    "Source": "BorderlessGaming",
    "WatsonBuckets": null,
    "FileLoad_FileName": "System.Threading.Tasks, Version=1.5.11.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a",
    "FileLoad_FusionLog": "WRN: Assembly binding logging is turned OFF.\r\nTo enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog](DWORD) to 1.\r\nNote: There is some performance penalty associated with assembly bind failure logging.\r\nTo turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].\r\n"
  },
  "HelpURL": null,
  "StackTraceString": "   at System.Threading.Tasks.TaskExceptionHolder.Finalize()",
  "RemoteStackTraceString": null,
  "RemoteStackIndex": 0,
  "ExceptionMethod": "8\nFinalize\nmscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089\nSystem.Threading.Tasks.TaskExceptionHolder\nVoid Finalize()",
  "HResult": -2146233088,
  "Source": "mscorlib",
  "WatsonBuckets": null,
  "InnerExceptions": [
    {
      "ClassName": "System.IO.FileLoadException",
      "Message": "Could not load file or assembly 'System.Threading.Tasks, Version=1.5.11.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)",
      "Data": null,
      "InnerException": null,
      "HelpURL": null,
      "StackTraceString": "   at BorderlessGaming.BorderlessGaming.DoMainWork()\r\n   at System.Threading.Tasks.Task.InnerInvoke()\r\n   at System.Threading.Tasks.Task.Execute()",
      "RemoteStackTraceString": null,
      "RemoteStackIndex": 0,
      "ExceptionMethod": "8\nDoMainWork\nBorderlessGaming, Version=8.4.33315.1328, Culture=neutral, PublicKeyToken=null\nBorderlessGaming.BorderlessGaming\nVoid DoMainWork()",
      "HResult": -2146234304,
      "Source": "BorderlessGaming",
      "WatsonBuckets": null,
      "FileLoad_FileName": "System.Threading.Tasks, Version=1.5.11.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a",
      "FileLoad_FusionLog": "WRN: Assembly binding logging is turned OFF.\r\nTo enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog](DWORD) to 1.\r\nNote: There is some performance penalty associated with assembly bind failure logging.\r\nTo turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].\r\n"
    }
  ]
}

**Comment by campbeb** [comment]
Do you have .NET Framework 4 installed?
