### ISSUE TITLE
The software does not boot with Windows 10

### ISSUE THREAD

**Issue by HenriDebeaurain** [Codeusa/Borderless-Gaming#241]
The software doesn't start at the same time of the OS. I hope you will fix that, thank you
Henri

**Comment by Fattur** [comment]
It sure is shown in the task manager and it should start with windows but it doesn't starts.

![taskmgr](https://cloud.githubusercontent.com/assets/13141259/13908619/0a96052e-ef0f-11e5-82c4-f7c692f4c109.PNG)

**Comment by Fattur** [comment]
For a temporary fix please use this regedit file or config:
https://yadi.sk/d/J_EXPczgqg82m

this file includes a string added to regedit.
HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Run
Create a new string under this you can give the name you want and it's value should be the path of exe file. For default it's:
C:\Program Files (x86)\Borderless Gaming\BorderlessGaming.exe
Add this or simply use the registry file and in boots with windows. but this is temporary fix
