### ISSUE TITLE
Suggestion: Allow monitor selection.

### ISSUE THREAD

**Issue by Luth** [Codeusa/Borderless-Gaming#246]
One of the games I play launches the game in the "middle" of my display (half on one monitor, half on another).  BG makes it fullscreen, but to the wrong monitor.  It'd be nice if I could configure which monitor to fullscreen to, or at least switch the monitor assignment after it's been fullscreened.

**Comment by ZeroMaki** [comment]
if you open and right click it has an option that says "make borderless on" which shows your displays.
