### ISSUE TITLE
Just Cause 3

### ISSUE THREAD

**Issue by FireController1847** [Codeusa/Borderless-Gaming#247]
A while ago, I had made Just Cause 3 border-less. It worked fine the first time I launched it, but afterwards it caused my game to stay between 10-0 FPS, and it ruined the basic interface. Please fix this issue. BTW, Even after closing Border-less Gaming, the game is still border-less.

**Comment by Acecool** [comment]
I've noticed issues too such as the mouse not locking, taskbar showing up, etc... Happens in other games too.
