### ISSUE TITLE
Doesn't Work With Killing Floor

### ISSUE THREAD

**Issue by borderlesskillingbug** [Codeusa/Borderless-Gaming#248]
I've been trying for 2 hours to get this to work with the game Killing Floor, because for some reason that game only has 32-bit colour support.

I can't find a way to manually add the game, with Google or in the application, and it doesn't show up in the list no matter what. Trying to add it using the windows key + f6 shortcut just locks up Borderless Gaming, requiring Task Manager to close it.

The only thing I can find on Google, is a similar issue to mine, that was apparently resolved as of version 7.4, I believe. I just updated and am running version 8.4

When it's frozen, the favourited applications are shown on the right list, but the left list is empty. Whenever my mouse is on anything to do with it, the application or it's tray icon, the cursor is a horizontal rescale icon.

**Comment by 07416** [comment]
duplicate: https://github.com/Codeusa/Borderless-Gaming/issues/93
