### ISSUE TITLE
Unhandled Exception

### ISSUE THREAD

**Issue by tavoelk** [Codeusa/Borderless-Gaming#250]
Hey guys, after setting up my PC again, i have the "Unhandled Exception" issue. http://puu.sh/php7L/b7e92243f8.png
I tried to uninstall the whole programm, tried to run it on a older version, but nothing helps for me. It keeps "Loading" in the lower left corner and gives me the error.
Thank you for your help!
[undhandledException.txt](https://github.com/Codeusa/Borderless-Gaming/files/299262/undhandledException.txt)

**Comment by Codeusa** [comment]
Your output is in German so I can't really read it.

Are you sure System.Threading.Tasks.dll is present

**Comment by tavoelk** [comment]
Sry for that, i cant reach the settings to change the language, Borderless Gaming breaks down before i can change anything.
The dll-file is present.

**Comment by Codeusa** [comment]
see if #225 is your issue

**Comment by tavoelk** [comment]
No, it is not. I do not even come close to the point of saving favorites. I tried the admin and non-admin version, i see no difference in the error.

**Comment by Codeusa** [comment]
"The file or assembly \ "System.Threading.Tasks, Version = 1.5.11.0, Culture = neutral, PublicKeyToken = b03f5f7f11d50a3a \" or one of its dependencies not found. The system can not find the file specified."

Do you have the latest .NET installed?

**Comment by tavoelk** [comment]
Ok, thank you, that was my problem. Win 7 sucks hard if you have to reinstall the complete system. Thank you!

**Comment by Acecool** [comment]
It seems it was a Windows 7 x64 Pro issue where the .net framework installation could become "screwed beyond recognition" and uninstalling / reinstalling / using utility to completely uninstall / etc... wouldn't properly remove the files so when you went to install a new version it would claim a newer one is already installed ( but it couldn't find the files )...

When I upgraded to 10 ( Did upgrade on laptop to generate key then fresh install on my primary computer with said key [ which was before the 7 key was working with 10 install ] and everything works as expected )...
