### ISSUE TITLE
Borderless Gaming crashing all the time (Fixed)

### ISSUE THREAD

**Issue by Babyforce** [Codeusa/Borderless-Gaming#251]
Hello, I have an issue with this software. It was working fine for a while. Then, I re-installed my Windows 7 because the old one was doing weird things. Now, after Microsoft.net 4 installed with Steam (Took forever, shut down Steam in the process and cannot repair the installation), after few seconds of "loading..." at the bottom of the window, it crash by leaving [this message](http://i.imgur.com/8kDRGou.jpg).
So I checked the content of the .Json and [here it is](http://pastebin.com/WV3YsCt8). (Sorry for the French)
The version I use is the latest one "Borderless Gaming 8.4" from Steam.

I don't know if it comes from the dotNET 4 that is corrupted (but i cannot even repair it as the progress bar doesn't increase at all, even after 30mins) or from the software itself (or maybe my Windows but seems weird from a fresh one). I really need to know what cause that and if there is a fix.

Thanks in advance.

**Comment by Babyforce** [comment]
I thought I fixed it but no. I could finally install the dotNET included in the folder of the software but still not working.

**Comment by Babyforce** [comment]
Oh well it has fixed itself with time I don't have a clue why.

**Comment by aryantiwari209** [comment]
facing the same problem. it just freezes

**Comment by MatheusPese** [comment]
same with me
