### ISSUE TITLE
Payday 2 - "error"

### ISSUE THREAD

**Issue by slfight** [Codeusa/Borderless-Gaming#255]
I used to use ShiftWindow for borderless windowed mode and since I've upgraded to Windows 10, I've been redirected here to try it out but Bordless-Gaming 8.4 just says "Payday 2 [error]" and thus cannot make it borderless windowed mode. 
Is this normal? 

Error code [#12216][16CA0000.00000300]

**Comment by Centzilius** [comment]
Does this error still occure to you? I just used Borderless Gaming 9.3 and it works. (PS: You have to enable windowed mode in Payday 2)
