### ISSUE TITLE
When playing SpaceEngine, BG's borderless is no different than fullscreen

### ISSUE THREAD

**Issue by Kelvets** [Codeusa/Borderless-Gaming#256]
I set SpaceEngine (an OpenGL game) to windowed mode then used BG to borderless it. Problem is, it's no different than the game's own fullscreen mode! If I alt+tab when borderless is on, it's no faster than when using the game's fullscreen mode, and I still see the screen flash black. My Lightpack backlights which normally work with the game when windowed (not when fullscreened) also cease to work properly when in borderless, which shouldn't happen if the game was true borderless.

**Comment by Keith94** [comment]
As a workaround, set the game to "No Size Change" from the favorites list, and then adjust the window size from the in-game options.

**Comment by Kelvets** [comment]
That worked, thank you!
