### ISSUE TITLE
Window extending to both screens instead of one for Undertale

### ISSUE THREAD

**Issue by reyrey725** [Codeusa/Borderless-Gaming#258]
I try to use it for Undertale, and when I do, it extends to both my computer screens.  I use the option 'Set Window Size' and it ignores it.  Any suggestions?

**Comment by Keith94** [comment]
There's a workaround... which involves resizing the window using another application, and then only removing borders with Borderless Gaming.

I wrote a short guide here: http://pcgamingwiki.com/wiki/Undertale#Borderless_fullscreen_windowed
