### ISSUE TITLE
KotOR 1 is made full screen instead of windowed borderless

### ISSUE THREAD

**Issue by NTWarrior** [Codeusa/Borderless-Gaming#259]
I've set Star Wars: Knights of the Old Republic to open in windowed mode as per [these config tweaks](http://pcgamingwiki.com/wiki/Star_Wars:_Knights_of_the_Old_Republic#Windowed) and it opens windowed but when I try to make it borderless, it just becomes full screen. And that screen is always my primary monitor even if I've chosen to make it borderless on the secondary one or if I've moved the window to the secondary monitor first.

When KotOR is forced into full screen by BG, it will still minimise when I click on anything in the other window, just as when the game itself is set to run in full screen mode. (This behaviour is the main reason why I looked into running it borderless windowed in the first place).

Both monitors are 1920*1080, and KotOR is set to run at this same resolution (I used UniWS to do this).

**Comment by Keith94** [comment]
Try disable auto-maximize or set no size change from the favorites list.

**Comment by NTWarrior** [comment]
Doing either of those things still leaves me unable to move the game to the secondary monitor, and the mouse cursor alignment is offset a little bit until you load a game but they do stop the game minimising which is great. Thanks.
