### ISSUE TITLE
Add Delay Option

### ISSUE THREAD

**Issue by cheatfreak47** [Codeusa/Borderless-Gaming#262]
Some games behave strangely unless they're given a few seconds on their own before they are forced by this program.

One example is on my computer, Sonic Heroes will display nothing at all when this is applied instantly but if I manually make it borderless after the game has started, it works fine.

For Castle of Illusion, if it makes it borderless fullscreen too fast, it makes the cursor stay "loading" forever, making this blue circle I can't hide anywhere.

Being able to set a delay amount between 1 and 20 seconds would be good, as it would improve compatibility for such programs.

**Comment by Keith94** [comment]
Fixed by #264
