### ISSUE TITLE
Long startup

### ISSUE THREAD

**Issue by Davidj361** [Codeusa/Borderless-Gaming#265]
Borderless Gaming takes more than 2-3 minutes for starting up. It doesn't take as long once the windows finally pops up. I have no idea why it is doing this. Let me know what logs you need to debug this.

**Comment by Davidj361** [comment]
I think the issue might be from checking for updates. You might want to thread that away once the main program is started up and ready.

**Comment by chestfindman** [comment]
Thank you for pointing this out. I have ran into the same issue, several long minutes on every startup.
After disabling update checks it starts at lightning speeds.
Strange that in almost 3 years this hasn't been looked into.
