### ISSUE TITLE
Request: Single-click tray icon to toggle

### ISSUE THREAD

**Issue by Keith94** [Codeusa/Borderless-Gaming#266]
Currently, Borderless Gaming does not allow to "toggle window with single-click" via the tray icon, which is a very important feature for me, found in other applications like qBittorrent, JDownloader, Xpadder etc.

Other useful options to add could be "minimize to taskbar" as well as "hide tray icon if window is visible".

**Comment by mikeloeven** [comment]
+1 and don't forget an option to minimize to tray when you click the X button

**Comment by Keith94** [comment]
@mikeloeven It has that already, called "Close to Tray" under options.
