### ISSUE TITLE
Stuck "Loading"

### ISSUE THREAD

**Issue by wiilover22** [Codeusa/Borderless-Gaming#278]
On occasion when the PC restarts, the application is stuck "Loading", as can be seen in the lower left corner of the app. Force, or normal closing the app and re-opening does nothing.

Using latest version of Borderless Gaming
Windows 7 x64

**Comment by lynxite** [comment]
I have just encountered this issue as well. I'm also on Windows 7 x64. Running BGv9.5.5.

**Comment by nascentt** [comment]
this is still an issue on the steamdeck. i just bought and instaled it today and it just says loading in the status bar the entire time
