### ISSUE TITLE
Star Trek Online BSOD

### ISSUE THREAD

**Issue by flatline4400** [Codeusa/Borderless-Gaming#279]
If Borderless Gaming is running, it causes STO to fault to a BSOD.  I've tested around this a couple times now, and there is a definite conflict.

Win7 x64 up to date.
ATI Radeon 290 running with the latest 16.12.2 drivers.

Only started to happen since STO patched on Jan 12 2017.

**Comment by yarrmateys** [comment]
i have the same problem. every time i forget to turn this off and then later try to boot sto, i get a blue screen immediately.
