### ISSUE TITLE
Games not working

### ISSUE THREAD

**Issue by TestSubject173** [Codeusa/Borderless-Gaming#289]
Sherlock Holmes - The Devil's Daughter
 - Title bar remains

Rain World
 - Game image remains unstretched

For Honor
 - In-game resolution changes into screen resolution (It's a problem because I'm trying to get a less blurry 1080p on my 4K monitor by forcing nearest neighbor scaling method to be applied through this program)

**Comment by Keith94** [comment]
>Sherlock Holmes - The Devil's Daughter

Borderless Gaming has issues with Unreal Engine 3. You could try GeDoSaTo instead: http://pcgamingwiki.com/wiki/Glossary:Borderless_fullscreen_windowed#GeDoSaTo

>Rain World

I tested other methods, but the game completely breaks when forcing resolutions that aren't natively supported. :/
