### ISSUE TITLE
Unreal Engine 3 games are still buggy

### ISSUE THREAD

**Issue by Keith94** [Codeusa/Borderless-Gaming#291]
The release notes of [Borderless Gaming 9.0](https://github.com/Codeusa/Borderless-Gaming/releases/tag/9.0) says that "Unreal Engine games are now supported"

So I quickly tested Blue Estate (UE3 game) with BG 9.0, but the results are really buggy, i.e.:

* the game doesn't cover the whole screen
* taskbar still visible
* black bars displayed on the sides
* borders re-appear after using Alt+Tab, etc.

![2017-04-09_16-22-52](https://cloud.githubusercontent.com/assets/5490615/24841813/b03043ee-1d41-11e7-84f8-253537aa0ec5.jpg)

**Comment by Codeusa** [comment]
Thanks for the report, I only did testing with a handful of games and they all seemed to work. I'll download this title now and see if I can make some more progress.

**Comment by Codeusa** [comment]
For my own reference @Keith94 did this game go borderless at all previously?

**Comment by Keith94** [comment]
If you mean with BG 8.4, then no. I just tested it and the borders and title bar never get removed.

**Comment by KensonPlays** [comment]
Similar issue. Primal Carnage: Extinction uses UE3 as well. Has never had Borderless support, and even after updating and adding it as a favorite, and reloading the game, when attempting to alt-tab, it still hangs and flickers back and forth for a second before minimizing.

**Comment by Keith94** [comment]
@Codeusa Now that the fix has been reverted... are you investigating other options to support Unreal Engine?

**Comment by Codeusa** [comment]
@Keith94 Yeah, looking at writing a hook for directx that just overrides window settings internally.

**Comment by Echoplx** [comment]
GeDoSaTo supports borderless windowed mode perfectly in UE3 games, is there anything in the source code that could help you?

https://github.com/PeterTh/gedosato

**Comment by Codeusa** [comment]
@Echoplx that does what i just said.

**Comment by Keith94** [comment]
Any progress on this issue? 200+ incompatible games could benefit from a fix.

**Comment by Codeusa** [comment]
Can you try this now

**Comment by Keith94** [comment]
I'm unable to compile or purchase the app currently. If you're willing to e-mail me the latest binary, I can provide feedback for you.

**Comment by Codeusa** [comment]
If you email me at andrew@codeusa523.org I will provide you with a Steam key.

**Comment by Keith94** [comment]
OK, I sent you an email.

**Comment by Keith94** [comment]
Anyways I tested 9.3 using the free binary, but I still get a similar bugged result. :(

This is how it behaves (same for Blue Estate and A Story About My Uncle): https://gfycat.com/ImperturbableThreadbareAssassinbug

Also, with GameMaker games (tested Undertale) the window gets resized, then the border removed, however the _internal_ resolution does not become full (i.e. game will be running at 1914x1051 rather than 1920x1080). If the border was removed simultaneously it would not cause this issue, I think.

**Comment by Codeusa** [comment]
Can you try adding it to your favorites?

**Comment by Keith94** [comment]
It's the same result, unfortunately (for both engines). You can see in my screen recording as well.

**Comment by Codeusa** [comment]
Try adding a delay to the favorites, then close the game and restart it.

**Comment by Keith94** [comment]
Tried, but same result for ASAMU (resolution not full, taskbar visible, borders re-appear after 5-10 seconds).
