### ISSUE TITLE
WoW bugs 9.0

### ISSUE THREAD

**Issue by ghost** [Codeusa/Borderless-Gaming#292]
It resizes the window before removing the border for some reason which is bugging WoW (cursor is offset and the UI is stretched), worked fine in the last version which you are for some reason locking us out of forcing us to upgrade to a broken version.

**Comment by Codeusa** [comment]
You're not forced by any means. You just have to click "cancel" or "no" when it ask you to update.

I'll investigate this issue.

**Comment by McCarthee** [comment]
When I press cancel nothing happens, it doesn't open.

**Comment by Codeusa** [comment]
I just verified it works fine. You just simply have to click no when it prompts you there is an update. Its likely minimizing to your tray.

**Comment by McCarthee** [comment]
No it wasn't in my tray. Uninstalled it with Revo Uninstaller and reinstalled now it works.

**Comment by Codeusa** [comment]
Can you show a video of your issue with WoW

**Comment by Mjsud** [comment]
This is also happening with DragonNest. I know its not the same game but it's the same problem (I think)

I made a youtube video demonstrating it. https://youtu.be/bWNCwImdkaE

**Comment by Codeusa** [comment]
I'll be rolling back the changes tomorrow and pushing up a new release

**Comment by Mjsud** [comment]
I just wanted to update this. BG is now working for DragonNest. thanks so much for the fix!
