### ISSUE TITLE
There is something wrong after I update to 9.0:FIFA17

### ISSUE THREAD

**Issue by manunitedgermany** [Codeusa/Borderless-Gaming#293]
I can't maximum my FIFA after I update to 9.0.

**Comment by manunitedgermany** [comment]
ADD, it worked fine in the old version

**Comment by Codeusa** [comment]
I could use some more information

Is this when you try to do it manually or from favorites?

**Comment by manunitedgermany** [comment]
Initially, I added it into my favourites, but finding it can't maximum automatically . Then I tried to start it from the left side,it didn't work on again.

**Comment by manunitedgermany** [comment]
How could I upload the picture,I will show you.

**Comment by manunitedgermany** [comment]
Now I can use it, but I have to start it manually. How to make it maximum automatically as before. I have put FIFA17 to my favorites.
