### ISSUE TITLE
Windows startup

### ISSUE THREAD

**Issue by Enzii** [Codeusa/Borderless-Gaming#299]
Hello,

i would like to report this bug, apperently i have set up so it start up with windows, but why dosen't it do as it suppose to do, proof: http://prntscr.com/f1indi

please help me if you guys know how to fix it or solve that issue.

**Comment by Keith94** [comment]
Installing the non-admin version should fix this. Or, paste the text below into Notepad and save it as .reg file.

>Windows Registry Editor Version 5.00
>
>[HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Run]
>"BorderlessGaming"="C:\\\Program Files (x86)\\\Borderless Gaming\\\BorderlessGaming.exe"

Make sure to change the paths to match yours. Then double-click to import it.

**Comment by Enzii** [comment]
Hey, Thanks for it, the 2nd one did work, i tryed your first suggestion, but only 2nd work, Thanks once again.

**Comment by Keith94** [comment]
Alternatively, Elevated Startup can be used: https://stefansundin.github.io/elevatedstartup/
