### ISSUE TITLE
Failed to initialize Steam API

### ISSUE THREAD

**Issue by Chocodemon** [Codeusa/Borderless-Gaming#306]
I have a fresh Windows 10 install with just Steam. Then I donwloaded Borderless-Gaming and set it to auto start with windows. Now when windows starts I get the warning message that the "Steam API failed to initialize".

The Borderless Gaming App itself is running fine and auto starts without any other problem..

**Comment by Codeusa** [comment]
I'll take a look into this, I think it has to do with Steam not running first.

**Comment by Codeusa** [comment]
Fixed in the latest, pushing update to Steam now.
