### ISSUE TITLE
No installer in "releases", old README

### ISSUE THREAD

**Issue by ivanershov51** [Codeusa/Borderless-Gaming#308]
If I'm not mistaken, the installer was removed from the "releases", but the README installation instructions suggest that we should go to "releases" page.

**Comment by ivanershov51** [comment]
https://steamcommunity.com/games/borderlessgaming/announcements/detail/1265922139757037244
I think that this information should be posted on github too.

**Comment by NYPD** [comment]
Rip

**Comment by Codeusa** [comment]
I've updated the README to include build instruction and links to reflect the change.
