### ISSUE TITLE
Version 9.3 Mouse out of sync.

### ISSUE THREAD

**Issue by Mjsud** [Codeusa/Borderless-Gaming#311]
The mouse is out of sync in the game Dragon Nest on steam. It full screens then stretches the bottom out. The mouse is out of sync within the game.

I can provide screenshots and videos if need be.

**Comment by Codeusa** [comment]
@Mjsud has it always been like this or did it just start happening?

**Comment by Mjsud** [comment]
just started happening today when i got home

**Comment by Codeusa** [comment]
Before starting the game right click on DragonNest in your favorites. Your settings should look like this

![](http://i.imgur.com/FH6eo0H.png)

Once Auto-Maximize is disabled, your mouse should not longer be off.

**Comment by Mjsud** [comment]
You are the man!
