### ISSUE TITLE
steam storefront errors

### ISSUE THREAD

**Issue by cheatfreak47** [Codeusa/Borderless-Gaming#313]
I know this is a humorous issue coming from me given #312

But I noticed that on the Steam Storefront, you have the software listed as "includes source SDK" which is actually false. Source SDK refers to Valve's Source **Engine** SDK, not that the software is open source. 

Additionally you have a third party EULA enabled, even though it opens a non-existent EULA entry. You should probably disable that, or actually make a third party EULA of some kind.

**Comment by Codeusa** [comment]
Fixed. Thank you.
