### ISSUE TITLE
Avast detecting 9.3 admin setup as FileRepMalware.

### ISSUE THREAD

**Issue by ValynEritai** [Codeusa/Borderless-Gaming#315]
Title is descriptive of problem.
Virus Chest screenshot; http://i.imgur.com/z69PLxp.png

VirusTotal fails to detect a problem except under 'Rising', which is hardly a major AV like Avast. https://www.virustotal.com/en/file/29f1986c4578c8a990c9966aafcbf6ea575e4511fb4fa36e8a11a7d7e540faf8/analysis/1496847288/

**Comment by dam09fr** [comment]
Same for me.

**Comment by Codeusa** [comment]
I've taken down the admin setup file until Avast adds it to the whitelist.

**Comment by AndreyLurye** [comment]
I am having this issue for both setup files.  Can anyone confirm if the files are actually clean?

**Comment by ValynEritai** [comment]
Crap, now Avast is picking up the other file...

Something's not agreeing with the heuristics...

**Comment by ValynEritai** [comment]
I've just checked a few other files on Github to make sure it's not a server-side nor MITM issue, and it's not, Very strange though, as running it in Sandboxie reports no ill effects... I'd say Avast is definitely giving us a false positive.

**Comment by Codeusa** [comment]
It could be because these files were digitally signed and now they are not. I am waiting for my new certificate to be approved.

**Comment by dam09fr** [comment]
Something simmilar appened to me a few time before, removing the icon from the installer exe solved the problem with no more explanations from Avast team ...

**Comment by BoxOfFlex** [comment]
wew, taken down because of one antivirus

real considerate :clap:

**Comment by Codeusa** [comment]
@BoxOfFlex the issue here is once one detects it, others start. Anti-viruses are known to share heuristics and they're all terrible.

**Comment by dam09fr** [comment]
You can submit a false positive to Avast here : https://www.avast.com/false-positive-file-form.php
(if not already done)

**Comment by ShayBox** [comment]
Is there anyway to download right now? I Kinda need the program, idc if antivirus says its a virus or not, i know its not

**Comment by Keith94** [comment]
@ShayBox Here's 9.3 from GitHub: https://mega.nz/#!b5I3TLJS!Th83hsbuh5kkrPrfT_SwiC_z_gu7nOROSdnU5tsBKBE

**Comment by anishlr** [comment]
Just a thought. If the setup was taken down, is it possible for older versions of the app to stop detecting updates? Every time I log into my machine, the update window pops up and links me to the GitHub release page where the setup was taken down.

**Comment by dam09fr** [comment]
For next release : "Avast File Whitelisting"
https://www.avast.com/faq.php?article=AVKB229

**Comment by Keith94** [comment]
@Codeusa Any ETA yet?

>I am waiting for my new certificate to be approved.

**Comment by Codeusa** [comment]
Got them today. Getting ready to release a new build.

**Comment by Codeusa** [comment]
New signed binaries are on the Release page

**Comment by Keith94** [comment]
Why were they removed again? Steam sale?

**Comment by dam09fr** [comment]
They are still detect by another module of Avast ...

**Comment by Codeusa** [comment]
![](http://i.imgur.com/RwMJjhD.png) they said they are clean now

**Comment by nbmrjuhneibkr** [comment]
So, where is the release?

**Comment by Codeusa** [comment]
9.4.7 is now on the release page

**Comment by ValynEritai** [comment]
I'm closing this issue now as 9.4.9 has solved the false positive.

**Comment by luchillo17** [comment]
Just got this issue again with the v10 pre-release...
