### ISSUE TITLE
[BUG] Minecraft 1.10.2 is not handled correctly with version 9.4.

### ISSUE THREAD

**Issue by jarquafelmu** [Codeusa/Borderless-Gaming#317]
After the upgrade to version 9.4. Minecraft 1.10.2 in "borderless windowed" mode is no longer handled correctly.

When I launched Minecraft, even though Minecraft was a favorited game and Borderless Gaming was running, it didn't affect it. I had to close and relaunch Borderless Gaming for it to work. Then it went bad.

Minecraft was put into the full-screen mode which defeats the purpose of borderless windowed mode. Disabling full-screen mode with Borderless Gaming running causes a white bar where the title bar used to be to appear and causes a white bar on the right side to show up.

[Issue 1 Screenshot](http://imgur.com/THU3QCP)

To further confuse the issue, The white bars go away if you open the in-game menu.

[Issue 1 Menu](http://imgur.com/tiDR951)

After closing Borderless Gaming the windowed mode of Minecraft is now shifted down so that the bottom is cut off as if Borderless Gaming is still affecting the screen size, even while maximized.

[Issue 2 Screenshot](http://imgur.com/H6Tthtb)

Previous versions of Borderless Gaming handled Minecraft without issue.

**Comment by Keith94** [comment]
Out of curiosity, did you try toggling "Auto-Maximize" on or off via the menu option?

**Comment by Codeusa** [comment]
I'll be pushing an update to fix this (and any other games blundered by the last update) later tomorrow.

**Comment by jarquafelmu** [comment]
Thank you @Codeusa . The hotfix solved the issue.

**Comment by TypicalPretzel** [comment]
I'm still having this issue on the latest version
