### ISSUE TITLE
Blade & Soul is a hit/miss

### ISSUE THREAD

**Issue by KeelzYou** [Codeusa/Borderless-Gaming#318]
When it attempts to put the game into borderless mode it goes back and forth in windowed-mode. There are times it works but I have to fight with it, also when it does work there are times the mouse is slightly off.

**Comment by Dajova** [comment]
Can confirm that it still is a issue. No matter how many times i add and remove the game from the list, it still doesnt work properly.

At best i get like this: https://i.imgur.com/IvF8YFb.jpg
... and yet the border spills out on my other screen. So atm, i'm forced to use the regular fullscreen option.
