### ISSUE TITLE
Unable to compile

### ISSUE THREAD

**Issue by Ruined1** [Codeusa/Borderless-Gaming#327]
Cannot import the following key file: ..\BGKey.pfx. The key file may be password protected. To correct this, try to import the certificate again or manually install the certificate to the Strong Name CSP with the following key container name: VS_KEY_F9591841F0901A2A	BorderlessGaming.Logic			

Keyfile requires a password, password is not available

**Comment by Codeusa** [comment]
Make sure you run VS as administrator, then create your own Strong Key from the Signing menu under the project properties. 

Or just remove the keys entirely.

**Comment by Ruined1** [comment]
@Codeusa Can't access the project properties to change signing because they're locked. Removing the BGKey.pfx only caused more issues. Running as administrator didn't change anything. This is a fresh install of VS 2017 and .NET 4.5.2 dev

Thank you for the assistance, it's appreciated.

http://imgur.com/vqJocMx

**Comment by Ruined1** [comment]
It appears I am missing a core workload I needed with VS, I will tag you again once I resolve that issue if I'm unable to get it to compile.

**Comment by Ruined1** [comment]
Issue resolved. Thanks!

**Comment by NYPD** [comment]
@Ruined1 How did you end up resolving the issue? I have not used VS Studio so i'm a bit lost with all this stuff and terminology.

**Comment by amivit** [comment]
Same problem, also cannot solve.
