### ISSUE TITLE
Non-admin version

### ISSUE THREAD

**Issue by nbmrjuhneibkr** [Codeusa/Borderless-Gaming#333]
Where did it go? Current version from both Steam and GitHub requires administrator rights.

**Comment by BonnyDev** [comment]
From what I can gather this can be changed before build-time in the **app.manifest** file of the BorderlessGaming project in the Solutions explorer.
Replacing line 19
`<requestedExecutionLevel level="highestAvailable" uiAccess="false" />`
with the following
`<requestedExecutionLevel  level="asInvoker" uiAccess="false" />`
might solve your issue, however I do not if this interferes with anything else.

**Comment by Pathduck** [comment]
Any chance we could get a non-admin option or cmdline option for automation when launching games?

**Comment by RaTcHeT302** [comment]
What the hell, why are all the binaries gone?

**Comment by RaTcHeT302** [comment]
So this means that Borderless Gaming is also no longer portable? I always need to install it permanently?

**Comment by justalemon** [comment]
Yes and Yes.

You have to build the software if you want the binaries and/or a portable version.

**Comment by aDigitalPhantom** [comment]
There is no portable options for 9.4.9. It writes the content from languages.zip, and stores other data in `%appdata%\Andrew Sampson\Borderless Gaming`

You don't need to install it, but you need to change that path in the code it.

When comparing the source for 9.3, and 9.4.9. There were separate app manifests for user, and admin. The only change in the user, and admin versions is.

Admin
`<requestedExecutionLevel level="requireAdministrator" uiAccess="false" />`
User
`<requestedExecutionLevel level="asInvoker" uiAccess="false" />`

9.4.9
`<requestedExecutionLevel level="highestAvailable" uiAccess="false" />`

**Comment by Pathduck** [comment]
I own Borderless Gaming on Steam, and I still had to search the web for an older version, to be able to start it from a batch file at the same time as launching the game. I don't want it running in the background at all times, as there are just a few games I need to use this with.

So please add:
- option to launch as non-admin.
- option to have a single instance so I don't need to kill the previous process on batch file launch.

**Comment by Pluckerpluck** [comment]
I too want a non-admin version. Stuff running as administrator messes up global keybinds, so I'd rather it not do that unless absolutely necessary.
