### ISSUE TITLE
"UI Translations are missing from disk."

### ISSUE THREAD

**Issue by mamimamicuzpipi** [Codeusa/Borderless-Gaming#335]
Whenever I try opening whatever version of Borderless Gaming (Release, Debug, from installer) I get this same error(image 1).

I've tried updating the .NET Framework to 4.7 and checking the NuGet Packages and updating them before building.

I also get something that may be an error which could be causing this when building, but that isn't listed as an error(image 2).

Thanks in advance for making such a cool program.

![image](https://user-images.githubusercontent.com/16454983/28237426-41650b08-690d-11e7-9f10-b13fccb49840.png)
![image](https://user-images.githubusercontent.com/16454983/28237445-ddf8edd6-690d-11e7-944a-1ea707ef8a9e.png)

**Comment by Cheet4h** [comment]
Seems that the project doesn't create the "languages" folder and it's content if it's built and not installed. As a workaround, copy the "Languages" folder to "%APPDATA%\Andrew Sampson\Borderless Gaming"

**Comment by mamimamicuzpipi** [comment]
Worked perfectly. Thanks!

**Comment by theVenerable** [comment]
Same problem. Where is the language folder located. and where is app data located?

**Comment by djicode** [comment]
Just copy
./Borderless-Gaming/Languages/languages .zip 
to  
./Borderless-Gaming/BorderlessGaming/languages .zip

In visual studio add existing item to the project, select the languages.zip you just copied to the root of the project folder. Select the languages.zip file object you just added in the Solution Explorer treeview. Below in the properties for the file make sure Build Action is set to Content and Copy to Output is set to Copy always or Copy if newer.

Now when you build or run the application it will automatically unzip the languages to the right location.

**Comment by theVenerable** [comment]
''Just copy
./Borderless-Gaming/Languages/languages .zip
to
./Borderless-Gaming/BorderlessGaming/languages .zip''

Dude, seriously that does not help
I cant find anything like that anywhere i look

though really the fuking devs should sort this issue out themselves.
Tits

**Comment by melodicore** [comment]
I might be late here but you can literally just type the address %appdata% into your explorer window and you will find yourself in the correct folder. It wasn't surrounded with percent symbols without a reason.

**Comment by iDARKWALKER** [comment]
> Just copy
> ./Borderless-Gaming/Languages/languages .zip
> to
> ./Borderless-Gaming/BorderlessGaming/languages .zip
> 
> In visual studio add existing item to the project, select the languages.zip you just copied to the root of the project folder. Select the languages.zip file object you just added in the Solution Explorer treeview. Below in the properties for the file make sure Build Action is set to Content and Copy to Output is set to Copy always or Copy if newer.
> 
> Now when you build or run the application it will automatically unzip the languages to the right location.

GREAT!

**Comment by shodanx2** [comment]
This problem still exists

Copying this 

![image](https://user-images.githubusercontent.com/10621885/186340312-87aec09b-7725-47aa-8081-ed69a1934479.png)

to 

![image](https://user-images.githubusercontent.com/10621885/186340485-daa60e5b-4d9b-43b6-8621-431177907828.png)

still gives this error, and there's no english translation

![image](https://user-images.githubusercontent.com/10621885/186340219-26ba301e-7faa-4cc5-b692-1c20f8d3a209.png)

then the app just dies

**Comment by JesseAye** [comment]
> Just copy ./Borderless-Gaming/Languages/languages .zip to ./Borderless-Gaming/BorderlessGaming/languages .zip
> 
> In visual studio add existing item to the project, select the languages.zip you just copied to the root of the project folder. Select the languages.zip file object you just added in the Solution Explorer treeview. Below in the properties for the file make sure Build Action is set to Content and Copy to Output is set to Copy always or Copy if newer.
> 
> Now when you build or run the application it will automatically unzip the languages to the right location.

Have never used this software before, was running in to this "UI Translations are missing from disk" error on launch. Performed these steps, and worked like a charm. Thank you!

**Comment by CATXYLS** [comment]
If you're seeking a solution, try this method (v10.0-rc1):  
1. Compress the "languages" folder (containing ".lang" files) from the **project root**  
   → Output: "languages.zip" 
2. Copy the ZIP to the **program's root directory**:  
  "Borderless-Gaming-10.0-rc.1\BorderlessGaming\bin\Release\net8.0-windows\win-x64\"
   (i.e., the folder containing the compiled `.exe`)  

not to %AppData%\Roaming\Andrew Sampson\Borderless Gaming.

**Comment by Romarinz** [comment]
> Seems that the project doesn't create the "languages" folder and it's content if it's built and not installed. As a workaround, copy the "Languages" folder to "%APPDATA%\Andrew Sampson\Borderless Gaming"

2025 still works :)
