### ISSUE TITLE
Once free, open source utility now going paid? Are contributors being paid for their work?

### ISSUE THREAD

**Issue by deslymon** [Codeusa/Borderless-Gaming#336]
If I'm ever to consider paying money for something released under OPEN SOURCE LICENSING. then I want to see some proof that you aren't just pocketing this for yourself. This had been claimed to be a permanently free utility, and over the past while has moved from that into accepting "donations" through Steam, then charging if people want updates at all. I have no problem paying for apps, but when other people likely aren't seeing anything for their work, this just comes off greedy at the moment. at least until proven otherwise.

**Comment by Codeusa** [comment]
As far as I know I'm the only primary contributor at this point and the majority of the code base is written by me.

**Comment by deslymon** [comment]
I mean, that's a clever word choice, so sure if you want to stick with that I'll just keep snagging it free. If you decide to honor contributions by people, maybe you'll get some business.
