### ISSUE TITLE
FavoritePorter not working

### ISSUE THREAD

**Issue by karasuhebi** [Codeusa/Borderless-Gaming#339]
Hi there, thanks for making FavoritePorter so we could import our favorites from the old registry key (although I'm not sure why you didn't just build that into the installer tbh) but it doesn't seem to be working anymore. I went from 9.1.33315.1328 to 9.4.9.1328 so my guess is that the installer for 9.4.9 nuked the old registry keys.

Any ideas?

**Comment by Codeusa** [comment]
Favorites were saved to a file on disk, not your registry. This file was Favorites.json.

**Comment by karasuhebi** [comment]
Oh OK, gotcha. Is it in %AppData%\Codeusa Software\Borderless Gaming? The one in there looks like it's been overwritten.

**Comment by Codeusa** [comment]
Move it to %AppData%\Roaming\Andrew Sampson\Borderless Gaming

**Comment by karasuhebi** [comment]
Not sure why I never responded to this but browsing to %AppData% takes you to \AppData\Roaming\ so saying %AppData%\Roaming is not correct.
