### ISSUE TITLE
"UI Translations are missing from disk." on launch

### ISSUE THREAD

**Issue by Auretus** [Codeusa/Borderless-Gaming#349]
Synced latest version from repo today and compiled. Build process finishes with no warnings, but when I go to launch BorderlessGaming.exe from the release branch, I get the error message "UI Translations are missing from disk." Deleting configuration folder from %APPDATA% doesn't help.

Build log follows:
```
1>------ Build started: Project: BorderlessGaming.Logic, Configuration: Release Any CPU ------
1>  BorderlessGaming.Logic -> F:\Source\Repos\Borderless-Gaming\BorderlessGaming.Logic\bin\Release\BorderlessGaming.Logic.dll
2>------ Build started: Project: BorderlessGaming, Configuration: Release Any CPU ------
2>  F:\Source\Repos\Borderless-Gaming\SteamLibs\Facepunch.Steamworks.dll
2>  F:\Source\Repos\Borderless-Gaming\SteamLibs\steam_api.dll
2>  F:\Source\Repos\Borderless-Gaming\SteamLibs\steam_appid.txt
2>          3 file(s) copied.
2>  BorderlessGaming -> F:\Source\Repos\Borderless-Gaming\BorderlessGaming\bin\Release\BorderlessGaming.exe
2>  'iscc' is not recognized as an internal or external command,
2>  operable program or batch file.
========== Build: 2 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
```

**Comment by DominykasPetke** [comment]
Found a workaround:

Just copy all the files from Languages folder to the .exe's folder.

**Comment by Auretus** [comment]
It works, but that feels like something that the build process should handle without manual intervention.

**Comment by aDigitalPhantom** [comment]
It should have something like "copy $(SolutionDir)Languages\Languages.zip $(ProjectDir)$(OutDir)" in the pre or post build stages in build events for BorderlessGaming. It's looking for the zip file that doesn't get copied.

**Comment by froggz19** [comment]
Same issue here...
Installation dir https://i.imgur.com/OiRClBh.png

**Comment by froggz19** [comment]
9.5 fails to extract the lang files in %APPDATA%, 9.4.9 works fine though.

**Comment by Unknow0059** [comment]
The suggestion doesn't work.

**Comment by Dracovian** [comment]
Line 16 in BorderlessGaming.Logic/System/AppEnvironment.cs that is tied to the error message suggests that you have to copy the Languages folder to the folder named "%appdata%\\Andrew Sampson\\Borderless Gaming"

If such a folder doesn't exist then that means you have most likely changed the value of "versionInfo.CompanyName" and as such you must go hunting for that value (either way the folder in question in the %appdata% directory should have a subfolder named "Borderless Gaming" and that's where you want to copy the Languages folder into).
