### ISSUE TITLE
ePSXe get's Tearing when used with BG

### ISSUE THREAD

**Issue by TheRealPrinceVinc** [Codeusa/Borderless-Gaming#351]
I ran some tests today and oddly enough... when I use BG I get screen tearing in cut scenes mostly.

This does not happen if I only use Window Mode.

My question is how can this be? What causes that behaviour?

This is on Win10

**Comment by justalemon** [comment]
I think that the problem is one of these:

* A render problem on ePSXe
* A scale problem on ePSXe
