### ISSUE TITLE
Age of Empires 2 - original screen top left

### ISSUE THREAD

**Issue by Evannex** [Codeusa/Borderless-Gaming#352]
I'm not sure how to word the title for this, basically it correctly shows as borderless, however none of the buttons are clickable where they are, and when hovering over the top left of the screen, the original window and window size show OVER the borderless one. You can only click buttons on the borderless screen by clicking on the "invisible" one on the top left "actual" game screen.

I know this is a very old game, so i'm not even sure if there is anything that can be done to fix this, but I thought it was worth noting anyways. :D
![capture1](https://user-images.githubusercontent.com/15008526/31043990-aa9d05b2-a594-11e7-9b38-c9379a47f227.PNG)
![capture2](https://user-images.githubusercontent.com/15008526/31043991-aa9f7220-a594-11e7-91e7-8825606c2985.png)
![capture3](https://user-images.githubusercontent.com/15008526/31043992-aaa2d5a0-a594-11e7-899c-087e6a4556c9.png)

**Comment by xelizor** [comment]
which resolution are you using? if you select "Set Window size" and then introduce the respective difference value between the game's resolution and your screen's resolution /2 as "X Offset" and then introduce the values respective to the game resolution as Width and Height... it should work... which resolution is your game using?
