### ISSUE TITLE
New Bug

### ISSUE THREAD

**Issue by xMrVizzy** [Codeusa/Borderless-Gaming#355]
In "C:\Users\xmrvizzy\AppData\Roaming\Andrew Sampson\Borderless Gaming\Languages" must include languages in .lang files, but in last steam update it create "C:\Users\xmrvizzy\AppData\Roaming\Andrew Sampson\Borderless Gaming\Languages\Languages" folder with .lang files and programm can't find this files, fix it please!

**Comment by polykoma** [comment]
Same here
I freshly bought your tool and can not install it. Same error. Redownloading and repairing fails.

HELP !

**Comment by Codeusa** [comment]
Fixed.
