### ISSUE TITLE
Failed to extract language pack.

### ISSUE THREAD

**Issue by Ibrahimsalman01** [Codeusa/Borderless-Gaming#356]
[https://gyazo.com/33a054c75919957c699f05ace0d54de1](url)

**Comment by Zweihander-Main** [comment]
Same problem --
`Failed to extract the language pack. Please report this: Access to the path 'C:\Program Files (x86)\Borderless Gaming\Languages.zip' is denied.`

Program was running under a non-admin account on Windows 10 Pro 1709.

The problem only happens until the program is launched using an admin account at which point it works using both a non-admin and admin account for all subsequent launches.
