### ISSUE TITLE
Make game borderless, but not change resolution?

### ISSUE THREAD

**Issue by BloodDragooner** [Codeusa/Borderless-Gaming#357]
Hello, is there a way I can make a game not detect my screen resolution? Such as, PAYDAY 2 or Xonotic, these games automatically switch to the default screen resolution, which affects performance a lot. Thanks!

**Comment by Keith94** [comment]
Try "No Size Change" option from the favorites list.

**Comment by BloodDragooner** [comment]
Maybe I wasn't clear, sorry about that, I want it fullscreen, but if I set it like that, it sets it to my default screen resolution of 1366x768...
