### ISSUE TITLE
How do you completely uninstall Borderless-Gaming?

### ISSUE THREAD

**Issue by ghost** [Codeusa/Borderless-Gaming#365]
I want to completely uninstall Borderless-Gaming, like delete all traces of it from my computer. How do I do that?

**Comment by Pathduck** [comment]
After running the uninstaller, preferably using Geek Uninstaller (https://geekuninstaller.com/), make sure the following directories are removed, if not delete them:
AppData\Roaming\Andrew Sampson\Borderless Gaming
AppData\Roaming\Codeusa Software\Borderless Gaming

Not sure why there's two of them, probably old leftovers?

Also delete the following keys from the registry if not already deleted:
Computer\HKEY_CURRENT_USER\Software\Codeusa Software

Geek Uninstaller should probably do the job for you though.
