### ISSUE TITLE
Unable to compile: Cannot import the following key file: ..\BGKey.pfx; No Signing menu in Project Properties

### ISSUE THREAD

**Issue by marinesciencedude** [Codeusa/Borderless-Gaming#366]
The issue/solution I'm referring to is Issue #327 where it was solved by creating your own Strong Key from the Signing Menu of the Project Properties, which does not seem to show up on my copy of Visual Studio Community 2017.

Any suggestions on how to fix this otherwise?

The full error:
Cannot import the following key file: ..\BGKey.pfx. The key file may be password protected. To correct this, try to import the certificate again or manually install the certificate to the Strong Name CSP with the following key container name: VS_KEY_98A4B441F6FF1F7B
(in both BorderlessGaming and BorderlessGaming.Logic)

**Comment by aDigitalPhantom** [comment]
You need to disable signing, or make a new key.

**Comment by marinesciencedude** [comment]
The problem being I can't find a way to disable signing or make a new key, as the menu in Project Properties is nonexistent for me.

**Comment by aDigitalPhantom** [comment]
You need to edit the project properties for BorderlessGaming.Logic.csproj, and BorderlessGaming.csproj. When you're on that signing tab there is check box to enable/disable signing, and there is a drop down menu with the key name that has an option to create a new key.

**Comment by marinesciencedude** [comment]
Ah Okay, the second option worked for me. Thanks for the help.
