### ISSUE TITLE
The Escapists 2 -- crash; 5 second lag on alt-tabbing

### ISSUE THREAD

**Issue by ghost** [Codeusa/Borderless-Gaming#369]
So since The Escapists 2 doesn't natively support borderless windows, I thought i'd get Borderless Gaming and run it with that, yeah?

However, there are problems. For example, when alt tabbing in/out of The Escapists 2, the my computer (RX 580 / Ryzen R5 1500 / 8 GB RAM) lags horribly / freezes for about 5-10 seconds. Also, the game crashed. Here's the files related to the crash:
[2017-12-28_132702.zip](https://github.com/Codeusa/Borderless-Gaming/files/1591863/2017-12-28_132702.zip)

I'm using the latest version on steam (I wanted to support the dev(s)!)

**Comment by MoreRobustThanYou** [comment]
These problems ARE NOT PRESENT if you choose the DX9 version of The Escapists 2 in steam
