### ISSUE TITLE
Bordless Gaming Won't Work // Constantly Crashes Even After Re-Install + PC Restart

### ISSUE THREAD

**Issue by ImNotSmartSoICantThinkOfAUserName** [Codeusa/Borderless-Gaming#374]
Hi, Borderless gaming worked for me for a couple of weeks and helped me tremendously, but now when ever I go to open it crashes, I have put the crash log picture below, I've already restarted my pc and uninstalled and re-installed 3 times, If you have any fix for this it would be much appreciated

https://gyazo.com/96f9982614be844c13cc04536dbbb4d1

(GitHub doesn't allow text files so I just screenshotted it)

**Comment by Zero3K** [comment]
That bug was taken care of in the latest version. Now it is crashing randomly without writing anything to a log file (for me at least).
