### ISSUE TITLE
License notices missing

### ISSUE THREAD

**Issue by donaldr3** [Codeusa/Borderless-Gaming#375]
It looks like many if not all of the actual files here don't have their GPLv2 headers. Putting the headers in is important, as it ensures that users know that a particular file is under the GPL, even if that file gets separated from the rest of the program. It also makes clear whether they can use the work under a later version of the GPL. You can check out https://www.gnu.org/licenses/gpl-howto.en.html for full instructions on using GNU licenses for your works. Thanks.

**Comment by aDigitalPhantom** [comment]
I don't have much experience with the GPL, but I know you can specify a version. If the license specifies "Version 2" it can not be used with anything else. If the license specifies "Version 2+", or is you can use it with 2 and later.

It's my understanding that you don't need a GPL header, but you are supposed to add a header stating you had made changed to a file, and when it was changed. You just need one copy the license to be with every copy, source and the compiled program.

I'm probably doing something wrong, but the problem I've ran into is the Visual Studio throws errors when some files have comments for that, and doesn't keep a comment like that in many files files.
