### ISSUE TITLE
Uninstalling Borderless gaming

### ISSUE THREAD

**Issue by ZombieSpale** [Codeusa/Borderless-Gaming#385]
Can someone help me uninstall this thing please? I refund it on steam and uninstalled it from steam, but I still have it and can't uninstall or even delete it. I can open it, but I can't use it's features.

**Comment by RAS-2112** [comment]
When you say you can't uninstall it or delete it, do you mean from Control Panel and File Explorer? If so, are you getting an error message?

**Comment by ZombieSpale** [comment]
From both, I am getting message that I can't delete files because I am not
administrator, even if I try as administrator.
