### ISSUE TITLE
Language mix-up

### ISSUE THREAD

**Issue by Masterfireheart** [Codeusa/Borderless-Gaming#386]
Me and a friend have installed 9.5.2 and while everything transferred over from the previous installation, all the text was in Spanish, rather than English. Despite English also being ticked off in the settings like shown. Deutsch makes it English but each restart opens up a new process as well.
![image](https://user-images.githubusercontent.com/6299186/38059466-875b0150-32b4-11e8-92b4-de272443d12f.png)
![image](https://user-images.githubusercontent.com/6299186/38059472-910419b2-32b4-11e8-8df0-828b846b40c2.png)
![image](https://user-images.githubusercontent.com/6299186/38059479-98a6df6a-32b4-11e8-8069-5fd372be52d3.png)
![image](https://user-images.githubusercontent.com/6299186/38059490-a14e97f2-32b4-11e8-92ab-cf7c0f5c031e.png)
![image](https://user-images.githubusercontent.com/6299186/38059495-a499b176-32b4-11e8-838f-67c471116689.png)

**Comment by Masterfireheart** [comment]
okay now 9.5.3 straight up crashes it
![image](https://user-images.githubusercontent.com/6299186/38059684-6bfe7f08-32b5-11e8-85ec-2e52b68f9791.png)

**Comment by Codeusa** [comment]
@Masterfireheart redownload the installer and it should be fixed

**Comment by Codeusa** [comment]
Fixed

**Comment by Masterfireheart** [comment]
forgot about this- issue was indeed fixed
