### ISSUE TITLE
Exception Caught 

### ISSUE THREAD

**Issue by Olegatorr** [Codeusa/Borderless-Gaming#387]
Exception Caught after installint the latest one. Tried installing over last release first, then clear setup, still doesnt work. Log attached.

[UnhandledException_29.03.2018.txt](https://github.com/Codeusa/Borderless-Gaming/files/1859341/UnhandledException_29.03.2018.txt)
------
weird symbols were there as well, it has to do smth w my pc running russian win10, although i keep any usernames/folders in eng to avoid this for happening
Please send help, cant play EFT without it :c

**Comment by Codeusa** [comment]
Redownload the installer from the release page and try again

**Comment by 3tes** [comment]
I have the same problem

[UnhandledException_29.03.2018.txt](https://github.com/Codeusa/Borderless-Gaming/files/1859666/UnhandledException_29.03.2018.txt)

**Comment by Olegatorr** [comment]
> Redownload the installer from the release page and try again
still crashes w same issue and log

**Comment by Optimusik** [comment]
Same here
[UnhandledException_29.03.2018.txt](https://github.com/Codeusa/Borderless-Gaming/files/1859687/UnhandledException_29.03.2018.txt)

**Comment by Codeusa** [comment]
It seems the language file you used is no longer there -- delete the "config.bin" file from the "Andrew Sampson" folder in AppData.

I will push a fix later today.
