### ISSUE TITLE
Random crashes

### ISSUE THREAD

**Issue by Zifoduk** [Codeusa/Borderless-Gaming#388]
Every so often the app just crashes even when not in used(in background). It can happen at start up or like some random number of hours later.
Heres the crash logs i have
[Crash Logs.zip](https://github.com/Codeusa/Borderless-Gaming/files/1862971/Crash.Logs.zip)

Thank you for your help

**Comment by nakami** [comment]
same. all crash dumps look exactly the same for me so i only included one.
it looks different from what @Zifoduk is getting...

[ThreadException_4-2-2018.crash.txt](https://github.com/Codeusa/Borderless-Gaming/files/1868962/ThreadException_4-2-2018.crash.txt)

**Comment by Zifoduk** [comment]
Bump
