### ISSUE TITLE
Crash on start after last update

### ISSUE THREAD

**Issue by kreolDest** [Codeusa/Borderless-Gaming#389]
This is the log, a'm getting after starting BG
gЗначение не может быть неопределенным.
Имя параметра: keyArgumentNullException?   в System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
   в System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   в BorderlessGaming.Logic.Core.LanguageManager.Data(String key) в E:\Dev\Borderless\Borderless-Gaming\BorderlessGaming.Logic\Core\LanguageManager.cs:строка 44
   в BorderlessGaming.Forms.MainWindow.InitializeComponent() в E:\Dev\Borderless\Borderless-Gaming\BorderlessGaming\Forms\MainWindow.Designer.cs:строка 163
   в BorderlessGaming.Forms.MainWindow..ctor() в E:\Dev\Borderless\Borderless-Gaming\BorderlessGaming\Forms\MainWindow.cs:строка 24
   в BorderlessGaming.Program.Main() в E:\Dev\Borderless\Borderless-Gaming\BorderlessGaming\Program.cs:строка 31

**Comment by Codeusa** [comment]
This should be fixed in the latest release
