### ISSUE TITLE
Can not work on a unity game

### ISSUE THREAD

**Issue by eromoe** [Codeusa/Borderless-Gaming#392]
Hello,

I buy this game http://store.steampowered.com/app/648100/_/   today, I'd like run it with windowed.
But it doesn't has window mode default. 
By `alt + enter` , I change it to be windowed. Then borderless it  with resolution 1600*900, but afer some time, it return to fullscreen.  How can I solve  this problem?

**Comment by nccvoyager** [comment]
If the game uses Unity for development, you can run it with:
`-popupwindow -screen-width 1600 -screen-height 900 -screen-fullscreen 0`
This will run the game:
- In borderless windowed mode.
- At your chosen screen resolution. (1600 and 900 can be replaced with any supported resolution.)
- In non-fullscreen mode.
Note that Borderless Gaming may still be desired to center the game window if it does not center automatically.
