### ISSUE TITLE
Borderless Gaming [Issue]

### ISSUE THREAD

**Issue by SomeoneTryingToFixAProblem** [Codeusa/Borderless-Gaming#393]
Hey, so, I've had Borderless-Gaming for a while now with no problems whatsoever, but here recently, I opened up a game and everything was fine, but I needed to get to my desktop for a moment so I removed it from favorites, and once I did that and made the game window through in-game settings, it immediately went back to fullscreen, I've tried removing it multiple times, and refreshing the applications. I don't know if setting it to favorites automatically sets it to make it fullscreen, and there is a manual way to turn it off from fullscreen, but if there is, I couldn't find it, any sort of help would be greatly appreciated if I'm just being dumb.

**Comment by Codeusa** [comment]
Borderless Gaming is running in the tray

**Comment by SomeoneTryingToFixAProblem** [comment]
Yep, I just knew it was something simple like that, that I was overlooking. Thank you!
