### ISSUE TITLE
super size option

### ISSUE THREAD

**Issue by rsnix** [Codeusa/Borderless-Gaming#40]
Hello,

I use the old windowedBorderlessGaming for most games as I have a portrait-landscape-portrait monitor setup.  My total resolution is 4960x1600 and use the application to span it across all 3 screens.   Since Geforce released their new drivers (334.89) the application no longer works correctly thus I have been searching for an alternative.  I came across your application but have tried numerous games with your app to have the game span across all 3 monitors with no success.  Any help would be greatly appreciated.  
Thank you,
Ryan

**Comment by psouza4** [comment]
This appears to be resolved with my unofficial fork version 7.2, although without proper video card support (like Eyefinity), games may appear squashed and not render correctly, such as my tests with Far Cry 3 (even when editing GamerProfile.xml).

For Far Cry 3, disable automatic maximize and manually set the window dimensions (new options) for that favorite.  If it's an issue, you can also disable the Windows taskbar while the game is running (available in version 7.3+).

**Comment by Codeusa** [comment]
@psouza4 do you plan on submitting a pull request with your enhancements?

**Comment by psouza4** [comment]
Hi Andrew, I did already for v7.0 -- then deleted it and submitted one for v7.1.

I didn't feel necessary to flood you while you're on vacation in London, so I haven't retracted v7.1 pull request in favor of v7.2 yet.  And in fact, I'm preparing for a v7.3 today with new options for hiding the mouse cursor and Windows taskbar visibility.

**Comment by Codeusa** [comment]
I've accepted 7.2 and will accwpt 7.3 when I see it appear. Thank you for helping keep the project lively

**Comment by psouza4** [comment]
Happy to contribute!
