### ISSUE TITLE
"Hide Balloon Tips" Doesn't Hide All Balloon Notifications

### ISSUE THREAD

**Issue by GT500org** [Codeusa/Borderless-Gaming#405]
When the "Hide Balloon Tips" option is turned on, Borderless Gaming still displays the "Borderless Gaming is minimized" balloon notification.

While the balloon notification disappears quickly, it isn't needed, as the Borderless Gaming icon is still clearly visible in the Notification Area/System Tray. Since there are many people who are annoyed by notifications (especially when they are not necessary), it would be great if this balloon notification could be suppressed by the "Hide Balloon Tips" option as well.

**Comment by WAZAAAAA0** [comment]
Definitely thirded
