### ISSUE TITLE
Steam version needs updating to version 9.5.5.

### ISSUE THREAD

**Issue by Ryonez** [Codeusa/Borderless-Gaming#420]
Please update the steam version. It's been nagging me for a week now.

**Comment by cheatfreak47** [comment]
+1

**Comment by OMG-Abaddon** [comment]
+1

Codeusa already gave up on the *paid* version?

**Comment by Ryonez** [comment]
I rebooted yesterday, and it asked again, so I'd say yes?

There's talk about how disabling steam integration is causing it to check for updates in the first place, but that shouldn't really matter, Steam should match the current release, especially as you said, it's a paid for version.

**Comment by Ryonez** [comment]
Closing as Steam has been updated to version 9.5.5. Thank you.
