### ISSUE TITLE
Hangs after playing games, present in 9.9.4 and 9.9.5

### ISSUE THREAD

**Issue by Ryonez** [Codeusa/Borderless-Gaming#428]
So while I've been using version 9.9.4, then 9.9.5, I've been plagued with borderless gaming hanging consistently.

After using it with a game, I often find, all of the time, that I go to open another game, and borderless gaming doesn't do it's thing. It's completely unresponsive, and I'm forced to close it in the task manager and restart it for it to work again.

**Comment by shovas** [comment]
+1 Been hanging after playing GTR2 on Win7 64bit since a least this version and the last

**Comment by m-alice** [comment]
Same after "dyinglight" (I am out of system requirements for this game)
CPU: intel i3 3220t
GPU: nvidia gtx660
[config.zip](https://github.com/Codeusa/Borderless-Gaming/files/2754969/config.zip)

**Comment by Deltawastaken** [comment]
Same for me, tested only with Dark Souls III

Windows 10 version 1809

[DxDiag.txt](https://github.com/Codeusa/Borderless-Gaming/files/2805923/DxDiag.txt)

**Comment by Chaython** [comment]
The only diference between those releases is a certifacate. 
Try using a much older version, or use a diferent borderless gaming application that's actually supported.
https://westechsolutions.net/sites/WindowedBorderlessGaming/
The developer actually replies to every question in the steam group page.

**Comment by Ryonez** [comment]
@Chaython 

You haven't read the issue. I've listed two issues that display the problem, not a that was added between them.

Stop trying to advertise another program here. If you were asked for a suggestion by someone, I'd be more understanding. But while I agree the dev is letting us down here, it's downright rude to advertise a product in multiple issues.
