### ISSUE TITLE
Actully release version 9.5.6 on Steam

### ISSUE THREAD

**Issue by Ryonez** [Codeusa/Borderless-Gaming#435]
https://steamcommunity.com/games/borderlessgaming/announcements/detail/1786146242195532562

Can't believe I'm really asking for this for the second time after #420 

Contains fix for #429 

I will be permanently rolling back to version 9.5 as it doesn't contain the issue from #429, or the ad for Rainway. I won't be using the steam edition for the foreseeable future giving the issues I've been having with it for the last 6 months.

**Comment by Stanzilla** [comment]
@Codeusa hello there

**Comment by Chaython** [comment]
If you don't care about open source you can try this freeware: https://westechsolutions.net/sites/WindowedBorderlessGaming/download
I use to use it, this git uses more CPU[1-2% vs 0%], but less ram, westech also has minor dxwnd integration...

**Comment by Codeusa** [comment]
I am currently traveling and I'm not sure why none of the builds released. I will be back at a system that can sign releases this Friday.

**Comment by SkyNinja** [comment]
Is 9.5.6 going to be released outside of Steam?

**Comment by Aidolii** [comment]
"this Friday"

**Comment by Ryonez** [comment]
@Aidolii I assume that means it's still not out?

**Comment by Aidolii** [comment]
@Ryonez Yep

**Comment by cheatfreak47** [comment]
@Codeusa ping
This is still an issue, any idea what's going on?

**Comment by OMG-Abaddon** [comment]
It would be awesome to stop getting errors when I shut down my computer all day long, even more so when I actually paid for the Steam version.
Not sure if this is the update that corrects that problem, but this is even worse than EA at handling problems.

**Comment by Ryonez** [comment]
@OMG-Abaddon

Not sure about the issue you're having, especially without the error message itself.

As stated, I've given up on whatever is happening and dropped back to version 9.5.0 and had none of the problems I was having since. 
Maybe you should give it a go as well: https://github.com/Codeusa/Borderless-Gaming/releases/tag/9.5

**Comment by Cyberavater** [comment]
The Friday which never came!

**Comment by Codeusa** [comment]
Done
