### ISSUE TITLE
Release 9.5.6 on Github

### ISSUE THREAD

**Issue by 07416** [Codeusa/Borderless-Gaming#437]
https://steamcommunity.com/games/borderlessgaming/announcements/detail/1786146242195532562

> Update 9.5.6 fixes a crashing bug happening to people on certain versions of Windows which are suffering from a Windows 10 glitch.
> 
> The update also fixes boot on start for laptops, introduces Portuguese, Japanese and Italian localization, and fixes the German one.
> 
> There are a handful of other misc bug fixes.

**Comment by SkyNinja** [comment]
I don't believe it's even made it to Steam just yet.

**Comment by DerRockWolf** [comment]
> I don't believe it's even made it to Steam just yet.

It is on steam since 11th of march.

And yes it should be here on github!

**Comment by Ryonez** [comment]
Dupe of #435

**Comment by Codeusa** [comment]
Done.
