### ISSUE TITLE
Can't Run Diablo 2 LOD in borderless full screen mode

### ISSUE THREAD

**Issue by DavePost87** [Codeusa/Borderless-Gaming#438]
I just installed BG to run Diablo 2 on full screen, but all it does is push it op in the top left corner in the screen. Is there a way I can fix this?

**Comment by Chaython** [comment]
what is the resolution the game is running at?

**Comment by DavePost87** [comment]
800x600

**Comment by DavePost87** [comment]
Okay, I figured it out! Thanks! :)

**Comment by Ryonez** [comment]
@DavePost87 comeon bud, don't be that guy.

Please explain what you did to fix it for those who may have the same issue in the future.

**Comment by DavePost87** [comment]
Good point Ryonez.
Turns out, I'm an idiot. The games max resolution is 800x600, so I just set my monitor to 800x600.
Chaython's comment made me realize that.

**Comment by Ryonez** [comment]
Thank you. Don't forget, you're able to close the issue!
