### ISSUE TITLE
[Feature Request] Hide regular mouse cursor and create/show a fake one on the expected point

### ISSUE THREAD

**Issue by Cyberavater** [Codeusa/Borderless-Gaming#444]
There are many games where using this software makes mouse cursor show/end up at the wrong point. i.e. The Witcher: Enhanced Edition
Now, it'd be nice if there could be a feature to hide regular mouse cursor and create/show a fake one on the expected point (maybe a little up?) that could be activated by the user depending on the need for it.
Thanks in advance.

**Comment by toastvader** [comment]
yo I'm having trouble with this too
