### ISSUE TITLE
Borderless gaming keeps crashing after 1903 update

### ISSUE THREAD

**Issue by TheBaronJJ** [Codeusa/Borderless-Gaming#445]
I updated my pc to the newest update and keep getting a error and crash, does anyone know how to fix this?

http://prntscr.com/o57xdr

If there's any other info please ask and i'll send it over

**Comment by Ryonez** [comment]
Try reinstalling, and if that doesn't work try dropping back to version 9.5.0/

**Comment by Chaython** [comment]
Use 
https://westechsolutions.net/sites/WindowedBorderlessGaming/
Dev actually supports his work

**Comment by Ryonez** [comment]
@Chaython Feels a little underwhelming. 

The only real issue I have with it atm is that I have to manual trigger it to work on programs. For now this is what I use, but I'm searching for something better.

**Comment by Chaython** [comment]
All will require manual triggering, obviously. It's not like there's an ai to seperate the thousands of games from the millions of software; to automatically make the games windowed then automatically make it borderless. [Lots of apps don't even support borderless, nor windowed]

**Comment by Ryonez** [comment]
You misunderstand. It doesn't trigger automatically after adding the window anytime I run a game.

This is unrelated to the issue at hand however.
