### ISSUE TITLE
CS:GO Ingame 

### ISSUE THREAD

**Issue by IKanoxzd** [Codeusa/Borderless-Gaming#447]
The moment I use the program, everything is fine, but when I join in a Match, the screen becomes full black, and I only see the hud of the game that includes only the map, the bullets, the guns.

**Comment by Chaython** [comment]
CSGO has a native borderless window. Why use this?

**Comment by LOLOLololDSFGgr** [comment]
He is talking about stretched I bought this cause i have two monitors and i love to play csgo on streched but even when trying it still wont work have the exact same issue as him
