### ISSUE TITLE
Baldurs Gate 1 - Extended editiion

### ISSUE THREAD

**Issue by consilium241** [Codeusa/Borderless-Gaming#448]
Hi, bought this for use with baldurs gate 1 but there doesn't seem to be support for it even though it was in a "supported games" list on steam forums.

I have:
1) run borderless gaming outside steam
2) started baldurs
3) baldurs shows up in the borderless gaming app but adding it to favourites or clicking the applicable buttons only switches over to baldurs, which then is still running in fullescreen.

**Comment by Chaython** [comment]
You must run the game as windowed, then use borderless gaming to make it a borderless window
