### ISSUE TITLE
Is there an alive fork we should migrate to?

### ISSUE THREAD

**Issue by Chaython** [Codeusa/Borderless-Gaming#449]
Is there an alive fork we should migrate to? Since Codeusa cashed out, and pulls are not being merged, the newest revision never released...

**Comment by Cyberavater** [comment]
I'm not sure about any forks but <a href="https://store.steampowered.com/app/1022230/Magic_Borderless/">Magic Borderless</a> is the best alternative right this moment. It has better features than Borderless-Gaming and solves most issues related to #444.
But unfortunately, it's not free.

**Comment by Chaython** [comment]
If I wanted proprietary I would go back to west tech solution's https://westechsolutions.net/sites/WindowedBorderlessGaming/download

**Comment by Cyberavater** [comment]
Yes, I've tried that but it doesn't have any solution related #444.

**Comment by Chaython** [comment]
westech replies to every comment on the steam group

**Comment by Cyberavater** [comment]
> WBG can integrate with dxwnd, in dxwnd you can force cursor settings
can also set display resolution should fix the issue

I know, but it should be automatic (default) just as it's in Magic Borderless.

**Comment by Chaython** [comment]
I spend more time modding and patching then I do playing

**Comment by JHR-Behrens** [comment]
Could anyone tell my what the latest release of Borderless Gaming is about? he says it features various bug fixes but... it doesnt. just changes the version 0.0.1 up without anything else afaict. did something went wrong releasing this?^^

**Comment by Chaython** [comment]
I think he is trolling; because so many people have been demanding the update.

**Comment by Codeusa** [comment]
- The update was released. I apologize for having a life outside of this project, I am under no obligations to do anything. 
- The project is stable and does its job. I don't need to do feature-creep. 
- 4 out of 5 of the pull request are irrelevant or pointless. I take time to consider adding new features into an otherwise feature-complete project. 

If you want something, add it yourself. I am not bending over backwards for people being rude and inconsiderate.

**Comment by Chaython** [comment]
How much money have you made from donations and Steam purchases?
300k? 500k?
You feel 5+ month x 2 vacations is what they deserve, for their patronage?

**Comment by JHR-Behrens** [comment]
@Codeusa sorry i didnt mean to sound douchy or something i was just genuinly interested why this update only changes 1 number in 1 file. it looked like something went wrong thats all ^^ 
for me the software is fine as it is aside from a few problems with some specific games i encounter from time to time :)

**Comment by Codeusa** [comment]
> How much money have you made from donations and Steam purchases?
> 300k? 500k?
> You feel 5+ month x 2 vacations is what they deserve, for their patronage?

I am running a startup with 17 full time employees. I have more important things to worry about.

**Comment by Chaython** [comment]
"I am running a startup with 17 full time employees. I have more important things to worry about."
So you're too successful to support your products. I mean it's good for profits. But don't expect people to be happy for you.
What's your start-up working on? The rainway garbage? There's so much software already with similar features. At least when you started borderless gaming there was only a couple borderless gaming utilities.
