### ISSUE TITLE
High processor load

### ISSUE THREAD

**Issue by Wenil925** [Codeusa/Borderless-Gaming#455]
Hi, i have i7 7800x(4.7ghz) and recently my cpu load has increased from 2%-3% , up to 5%-25% and the borderless-gaming itself opens very long.

I tried to reinstall but it did not help

Screenshot: https://i.imgur.com/XyoYdXB.png

**Comment by Chaython** [comment]
Ya this is pretty heavy
Just use a diferent borderless gaming software like westech
https://westechsolutions.net/sites/WindowedBorderlessGaming/
Much lighter; the developer always replies on the steam group
This is dead, the greedy dev sold it on steam pocketing big $ then dropped support immediately
