### ISSUE TITLE
Mute in Background does not unmute when alt+tabbing, app needs to be clicked in the task bar in order to restore sound.

### ISSUE THREAD

**Issue by Cronoadvan** [Codeusa/Borderless-Gaming#467]
I'm currently trying to use the app to play Gemcraft Chasing Shadows and have it mute when the app is not focused. Your solution works except it does not restore the game's sound when alt tabbing back. 

In order to restore sound I need to press the windows key and then manually click the game so the sound is un-muted.

**Comment by BobbyWibowo** [comment]
The preview version 10 in Releases appear to be a lot more reliable on my end in terms of alt-tab muting detection. I have yet to encounter any other oddities despite it being a preview version.
