### ISSUE TITLE
Error Compling in Visual Basic 2019

### ISSUE THREAD

**Issue by carmvette** [Codeusa/Borderless-Gaming#469]
Severity	Code	Description	Project	File	Line	Suppression State
Error		The command "call signtool sign /tr http://timestamp.digicert.com /td sha256 /fd sha256 /as /sha1 3BD5BE571287FE2052F137C44198AE7BAB38B037 "C:\Users\User\source\repos\Borderless-Gaming\BorderlessGaming\bin\Release\BorderlessGaming.exe"
call iscc /Qp "C:\Users\User\source\repos\Borderless-Gaming\\Installers\BorderlessGaming_Standalone_Admin.iss"
call signtool sign /tr http://timestamp.digicert.com /td sha256 /fd sha256 /as /sha1 3BD5BE571287FE2052F137C44198AE7BAB38B037 "C:\Users\User\source\repos\Borderless-Gaming\Installers\BorderlessGaming9.5.6_admin_setup.exe"" exited with code 1.	BorderlessGaming

**Comment by DarrenBelow** [comment]
App signing certificate needs fixing.

**Comment by Unknow0059** [comment]
So no one has been able to build this for an entire year? Impossible.
Surely this has been fixed already.
