### ISSUE TITLE
[Enhancement] Ability to edit favorites

### ISSUE THREAD

**Issue by Chucky2401** [Codeusa/Borderless-Gaming#477]
Hi,
I try your application, and it is very helpful.
I would like to know if it is possible to add the possibility to edit our favorites?
I use it to make Minecraft Borderless in fullscreen. But, I change the version every week with the current update, so I must add to favorites the new window. I can use the process, but I use others app with java I want in windowed mode. So I set with regex. But, if my regex is wrong in the future, I would have to delete my favorite and recreate it with the new regex. I think the ability to edit the regex will be powerful and add a lot of flexibility to your app.
Maybe the possibility to change Window title too.

Regards

**Comment by AgentM12** [comment]
I 100% upvote your idea.

Even the ability to be able to combine checking the binary program + window title/regex would be useful. Then I could select javaw binary + Regex: `^Minecraft \d.*$` to match Minecraft to any version (hypothetically)
