### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by Krafting** [Codeusa/Borderless-Gaming#482]
It would be great to have a tool like this on linux for our games!

**Comment by Calinou** [comment]
Given how this tool is written around Windows-specific APIs, this would probably be better handled by a different tool rewritten from scratch.

Also, many window managers like Xfwm and KWin already offer ways to enable borderless fullscreen. Try pressing <kbd>Alt + F11</kbd> if you use Xfwm. If you use KWin, you can bind the "toggle fullscreen" key in the system shortcuts settings to any key combination you want.

**Comment by zykren** [comment]
On Linux, you can just right-click the window and select full screen. It even works better than borderless-gaming

**Comment by Krafting** [comment]
> On Linux, you can just right-click the window and select full screen. It even works better than borderless-gaming

You should be more precise than that, it depends on your Desktop Environement

**Comment by Daasin** [comment]
> 
> 
> many window managers like Xfwm and KWin already offer ways to enable borderless fullscreen. Try pressing Alt + F11 if you use Xfwm. If you use KWin, you can bind the "toggle fullscreen" key in the system shortcuts settings to any key combination you want.
> 
> This fullscreen can be enforced permanently in KWin by pressing Alt + F3, choosing **More Actions > Configure Special Application Settings…** and enabling fullscreen permanently there. 
 Via Steam though? like Steamdeck customised games could be a usecase for this

**Comment by Calinou** [comment]
> Via Steam though? like Steamdeck customised games could be a usecase for this

The compositor used on SteamOS (Gamescope) already enforces fullscreen and has a very robust FPS cap, so I'd use that instead.
