### ISSUE TITLE
Shogun 2 

### ISSUE THREAD

**Issue by IMBATMAN114** [Codeusa/Borderless-Gaming#483]
hi i have a problem where the cursor was disoriented and stretched so i tried the fix i found on this site where i changed the prefrences but now it just freezes as soon as i activate borderless anyone know a solution ?? these are the changes i made in prefrences 
gfx_fullscreen false;
fix_res false;
fix_window_pos false;

**Comment by boonynator** [comment]
Somewhat similar issue. Used a AHK Script instead. For some reason some of the bottom of the screen gets cut off with Borderless Gaming.
