### ISSUE TITLE
not saving delay setting for specific applications

### ISSUE THREAD

**Issue by hsrizvi** [Codeusa/Borderless-Gaming#484]
When set specific games to delay the borderless window, it doesn't save. it will work this instance, but if I restart the borderless window application or my computer, those specific seem to have the delay reset to off.

**Comment by Ds886** [comment]
It saves the delays in the memory but doesn't show it in the context menu

this [build ](https://github.com/Ds886/Borderless-Gaming-fix-delayed-not-shown-in-context-menu)should fix it

**Comment by hsrizvi** [comment]
I will give this a try, but I don't think it'll work. It isn't just showing it not set to delayed, it isn't set to delay at all. After a restart, the setting reset and launching a game that requires the delay causes a crash.

**Comment by JohnBenson44** [comment]
hello I'm happy to find your program and I would love to be in full support…but delay window border won't keep it setting not even when I take away security rights. Any chance of a fix really quick it should be pretty simple if you design the program everything else holds. I'm happy to be here
