### ISSUE TITLE
Cannot open BG

### ISSUE THREAD

**Issue by IsakHornhaver** [Codeusa/Borderless-Gaming#489]
As the title says, I can't open my Borderless-Gaming. Every time I try, it pops up with "Do you want to allow this app to make changes to your device" I click yes and it still doesn't open. I tried re-installing it and rebooting my pc. I need help fixing it.

**Comment by weiwang11** [comment]
Try running the app as admin

**Comment by IsakHornhaver** [comment]
> Try running the app as admin

I have tried that. Didn't help.

**Comment by weiwang11** [comment]
Is there any anti virus flagging and disabling it?

**Comment by IsakHornhaver** [comment]
No. Not from what I know.

**Comment by IsakHornhaver** [comment]
I am pretty sure it happend after I enabled the setting that made it open minimized on startup. I also tried closing it in task manager, I still cannot make it work.

**Comment by weiwang11** [comment]
Try deleting the config file in this folder: ```%appdata%\Andrew Sampson\Borderless Gaming```

**Comment by IsakHornhaver** [comment]
That fixed the problem. Thank you for your help.
