### ISSUE TITLE
When I click on anything displayed on my second monitor the game on my first closes or minimizes

### ISSUE THREAD

**Issue by Spotie484** [Codeusa/Borderless-Gaming#491]
When I click on anything displayed on my second monitor the game on my first closes or minimizes. I added the game to my favorites, but nothing, is there something that needs to be toggled/configured? I have tried multiple games and this happens with all of them 
Thanks for your time!

**Comment by FabienOnGithub** [comment]
Hello ! I have the exact same problem and I didn't find any solution... Have you found something ?
