### ISSUE TITLE
Osu! game bordeless not working on playing song

### ISSUE THREAD

**Issue by Gregory-Hepicloud** [Codeusa/Borderless-Gaming#493]
Hi bordeless not working if playing song on osu!

osu!  > working but "osu! song name osu"  not working need to add 1 by 1 if want auto but we have 1 000 000 song

can you try to fix this ?

regards.

**Comment by ggtylerr** [comment]
osu! has a built-in borderless setting, why would you want to use BorderlessGaming for it?
