### ISSUE TITLE
Switching window between monitors of differing resolutions

### ISSUE THREAD

**Issue by stevedefazio** [Codeusa/Borderless-Gaming#504]
Hi, I just purchased Borderless Gaming, and I'm happy it solved my "win+shift+arrow keys won't move Fallout 4 between monitors" issue. However, I now have another problem.

I've got Fallout running nicely on my primary monitor (2560x1440). I can switch it to my second monitor (1920x1080) without a problem, but when I then switch it back to the first monitor the resolution is all messed up (I suspect it is keeping the smaller resolution from monitor 2).

Is this an issue others have run into?

**Comment by zykren** [comment]
I have this issue as well, idk what to do
