### ISSUE TITLE
Non-admin build of 9.5.6 available anywhere?

### ISSUE THREAD

**Issue by Pathduck** [Codeusa/Borderless-Gaming#509]
Hi,
does anyone know any fork/build of a non-admin, non-elevating build of the latest BG? I don't have access to compiler tools and wouldn't have an idea how to do it so would really appreciate if anyone's got a build. 

Currently I'm using an old build of 9.4 and it works fine, but assuming 9.5.6 is the last version we'll see it would be great to be able to use it in scripts to launch games without having it go to UAC every time.

**Comment by tygital** [comment]
THIS!

I really like the tool but it is pretty nasty to work with (scpriting and so on) because of the forced Admin elevation.

**Comment by mt025** [comment]
You can always create a shortcut with this path:

 `C:\Windows\System32\cmd.exe /c "set __COMPAT_LAYER=RunAsInvoker && start "" ^"C:\Your\path\to\BorderlessGaming.exe^""`

Look up RunAsInvoker for more info. Its a windows compatability layer setting.

**Comment by Pathduck** [comment]
@mt025 Thanks so much for the tip! 👏 

I had no idea about the `__COMPAT_LAYER` variable, it works fine and I can work that into the cmd scripts to launch games. Brilliant hack!

Would still be nice to have a non-admin build but I can at least work with this :)

**Comment by tygital** [comment]
I had no idea about the __COMPAT_LAYER variable either, it works fine and I already did work that into my AHK scripts. THX man
