### ISSUE TITLE
Cursor displacement bug

### ISSUE THREAD

**Issue by jDawganator** [Codeusa/Borderless-Gaming#512]
The location the cursor points to is not the same as the location the application receives. At the top of the screen, the locations match. Toward the bottom of the screen, there is an increasing vertical displacement. The location I see my cursor point is above where the application thinks I clicked. The difference is up to about 5% of my screen height. 

This was in Windows 10 and affects multiple games.

**Comment by Alacika** [comment]
I have the same problem, for example I can't select menupoint in rFactor2 because of the "displacement" bug.

**Comment by rev3rbjunkie** [comment]
I'm having the same issue, in csgo when have it set to fullscreen the menu items are offset from their clickable area, for example if i try to hit the quit button in the menu, nothing happens, but if I move my cursor about an inch upward I'm able to select it. Would really love a fix for this as it would allow for much more flexibility when streaming.

**Comment by nonplayer** [comment]
I am searching to find this bug as well, now having experienced it in Darkstar One.

**Comment by SwordDeath** [comment]
is this problem not resolved? I also have the same problem while playing the game
