### ISSUE TITLE
Request: Option to keep Window Border

### ISSUE THREAD

**Issue by LazySoda** [Codeusa/Borderless-Gaming#515]
As ironic as it sounds, let me explain.

I started playing Oneshot recently, and it's a game with really weird visual options.
The game can be run in a 640x480 window or in fullscreen, but people online and even the game itself recommend windowed, it seems fullscreen cuts visibility.
The issue with windowed mode is the only size is 640x480, with no way to resize it.

I found out that I can use Borderless-gaming to manually adjust the window size, but this also (naturally) removes the border.
Without the border, I'm unable to move the window around with the mouse.
There is an option to manually position the window, but only via X Y coordinates in the game's profile.

This made me think that an option to not disable the borders would be nice.
I know my situation is likely a niche use case, but I'd wouldn't guess an option like that would be too difficult, and as silly as a "Bordered mode" in Borderless-gaming sounds, I think it'd be a nice utility to have for these stubborn niche cases.

I can't see how to add a label, but it should should be in "enhancements", sorry.

**Comment by FieryMewtwo** [comment]
Wow. That. Is. Amazing.
