### ISSUE TITLE
Game slowdowns

### ISSUE THREAD

**Issue by Crafty-The-Fox** [Codeusa/Borderless-Gaming#517]
Game should be locked at 60 while playing, but is at 53 to 58 FPS.
Cant say the name of the game for reasons, but it is a d3d9 game.
It sometimes even slows it down A LOT (this is rare), making the game zoom back up to speed when it can.

**Comment by AndrewMD5** [comment]
Let me know when you can name the game or explain how this is related to BG.

**Comment by Crafty-The-Fox** [comment]
it's a special kind of game, but i know it is related to BG as i've had multiple reports of it happening. Name of the game is "Spicetools". closing BG fixes the issue. Spicetools is a toolkit to run multiple games, and i've had another person report the same issues with a different game than im running.
