### ISSUE TITLE
UI Translations are missing from disk on pc start up

### ISSUE THREAD

**Issue by lgcrionic** [Codeusa/Borderless-Gaming#519]
whenever I start up my pc that pops up regardless of it being installed or not (currently is uninstalled and it pops up)

**Comment by Dracovian** [comment]
Answered in [#349](https://github.com/Codeusa/Borderless-Gaming/issues/349#issuecomment-765025340)

If that doesn't work then I'll have to look through the code again to figure out what has changed since then.
