### ISSUE TITLE
Alice the madness returns

### ISSUE THREAD

**Issue by apples-auce** [Codeusa/Borderless-Gaming#520]
I noticed while playing Alice: the madness returns that the screen does get bigger however, it keeps jumping to the left side of my screen leaving about an inch exposed on my right. I wasn't too sure on how to fix that

**Comment by bonny1992** [comment]
Sorry to comment on a closed issue @andrewmd5 but how's the status for this game?

On the Xbox version it doesn't really fullscreen it, only maximizes it without removing the borders and it's not centered.
Maybe I'm doing something wrong?
