### ISSUE TITLE
I would like if you guys release some update to make this work

### ISSUE THREAD

**Issue by fchrvncss** [Codeusa/Borderless-Gaming#533]
i'm using an ultrawide monitor (2560x1080) and my intention using this app is to put my game full hd windowed for stream so i can use a space to see the chat and stuff, but the app fill the entire screen with the game. Idk if you can do this but my idea is that you can put an option so we can set a resolution we want the game to be.

**Comment by WilsonNet** [comment]
Thanks for this. I found another solution, just disabling the full screen and selecting setting window size.
Now you just specify the position that you want:
![image](https://user-images.githubusercontent.com/25280488/131263967-603ce4f5-cc80-433f-8361-366088398de9.png)

**Comment by jonhermansen** [comment]
@WilsonNet Yup, that works too. As long as you want the game left-aligned on your screen.

**Comment by fchrvncss** [comment]
thk u guys, really good job w this app :D
