### ISSUE TITLE
My program won't show up in Borderless Gaming after someone spammed random keys on my keyboard. Tried reinstalling the program a few times and I restarted my pc several times. Can anyone help me?

### ISSUE THREAD

**Issue by thingythingy24** [Codeusa/Borderless-Gaming#536]

**Comment by KulaGGin** [comment]
Just a friendly advice: if you want to actually get help by someone, post all information you can: what's your PC specs, system information, what program won't show up in the Borderless Gaming program, post screenshots and maybe even a video. Also post screenshots of all of the settings in Borderless Gaming.
