### ISSUE TITLE
"Use Global Hotkey" toggle causes Borderless Gaming to crash all the time on Windows 11

### ISSUE THREAD

**Issue by zandm7** [Codeusa/Borderless-Gaming#543]
If I have "Use Global Hotkey" turned on in Borderless Gaming, the program will always crash after being used once.

For example, I launch Valorant and use Borderless Gaming to toggle borderless mode (either with the hotkey or thru the GUI). If I then try to use or open Borderless Gaming again, it will be unresponsive and I have to quit and restart it using Task Manager to get it working again.

Disabling "Use Global Hotkey" fixes this issue. Anyone else experiencing this? Is this a bug exclusive to Windows 11?

And can we get this fixed please :) Thanks!

**Comment by Grammernatzi** [comment]
It happens in Windows 10, too, and it's really annoying. Using the program window manually works (I turn off automatic processing since it tends to add CPU usage), but I'd really prefer to use a hotkey.
