### ISSUE TITLE
Batman Arkham Asylum

### ISSUE THREAD

**Issue by CYR4N0** [Codeusa/Borderless-Gaming#55]
While starting Batman Arkham Asylum the game only goes fullscreen once if I close the game and open it again it seems that I need to restart the computer. If I do not restart, the window flashes appears to try to resize/move but ultimately failing leacing the Window bar at top still being displayed and continually attempting every 3 or so seconds. Currently running 6.5

**Comment by psouza4** [comment]
Unfortunately, Unreal Engine v3 games are not supported because the engine persistently and forcibly resets window size, border, and caption properties.  Here's a list of games running the Unreal Engine v3:

https://en.wikipedia.org/wiki/List_of_Unreal_Engine_games#Unreal_Engine_3

**Comment by CYR4N0** [comment]
Thanks for the update!
