### ISSUE TITLE
Why run as admin? It's not necessary.

### ISSUE THREAD

**Issue by twoco** [Codeusa/Borderless-Gaming#561]
Great app, but why run as admin? It also runs as "normal" user without admin privileges. And it works great. I run this app with `__COMPAT_LAYER=RUNASINVOKER` and it works. No admin rights prompt. No need.

![icon-admin](https://user-images.githubusercontent.com/53160891/163890589-89fb7891-cd58-4811-8721-f193e3b719f2.png)

**Comment by DeiDo** [comment]
This works fine as long as the game you're trying to turn borderless **_isn't elevated_**. It's pretty rare nowadays, but I had some games that required running them as admin.

**Comment by twoco** [comment]
For such rare cases you can just right click (explorer context menu) and select "run as administrator" or create a link with admin flag.  

My current workaround is to change the link target to:

```
C:\Windows\System32\cmd.exe /c "set __COMPAT_LAYER=RunAsInvoker && start "" ^"C:\Program Files (x86)\Borderless Gaming\BorderlessGaming.exe^""
```

And select the link icon again from `BorderlessGaming.exe`, otherwise the `cmd.exe` icon is used. It works great, but it's a bit more effort and complicated than the admin flag. 

Btw. you could also just add another explorer context menu entry with the COMPAT_LAYER setting to run as invoker (like the "run as administrator" entry). I investigated to this, because some developers demand admin rights for no reason and appear dubious (for example, the Ubisoft Connect developers are inept at this ... useless admin prompts sucks). This compat layer trick does not work with every program. But anyway... yes some older games required admin rights. I personally haven't had a case of running BorderlessGaming as admin.
