### ISSUE TITLE
Borderless Gaming window freezes and becomes unclickable after few minutes running

### ISSUE THREAD

**Issue by farsdewibs0n** [Codeusa/Borderless-Gaming#562]
This issue has been on my pc for monts already.
The only workaround is killing BG and re-run it

**Comment by VL4DST3R** [comment]
Came here to report the same. I wonder if an older version/fork also has this issue.

**Comment by dcraig327** [comment]
same issue for me

**Comment by lyndonguitar** [comment]
same issue. its working but it displays white screen after awhile in which it crashes as soon as you tinker with. easily solvable by just hard resetting the program though

**Comment by VL4DST3R** [comment]
Has this been fixed @andrewmd5 ?
