### ISSUE TITLE
Disabling Minimize to Tray for Multi Monitor Setups

### ISSUE THREAD

**Issue by Nova77x** [Codeusa/Borderless-Gaming#564]
There doesn't appear to be a way to disable Borderless from burying itself in the tray. Secondary monitors do not have tray access.

When Borderless is running on a second monitor, you want it to stay there on the taskbar. Not bury itself on the main monitor where the game is running, and the tray isn't accessible.

Easily correctable by commenting out the contents of MainWindow_Resize in Forms\MainWindow.cs and recompiling.
But it would be nice to have official support for disabling it.

So many tools default to minimizing to tray without an option to disable it. It's an awful feature for multi-monitor setups.

**Comment by battlegroundspng** [comment]
Many tools default to minimizing to tray without an option to disable it. [Battlegrounds Png](https://www.battlegroundspng.com)
