### ISSUE TITLE
Costs money on steam

### ISSUE THREAD

**Issue by Reycko** [Codeusa/Borderless-Gaming#569]
basically the steam version is a scam

**Comment by ashyerv** [comment]
no

**Comment by orowith2os** [comment]
You can download it for free from the github repo, or compile it yourself from source. It's actually legally required (afaik) to have the source code available, even if at a (small) fee to physically deliver it if you go that route. So no, it's not a scam. It's just another way of getting the tool, that supports the project.

**Comment by Reycko** [comment]
fr ? lmao i can just make a borderless script in autohotkey in 5 minutes i dont get money for that
