### ISSUE TITLE
[Suggestion] Wild card in application names

### ISSUE THREAD

**Issue by kepler-gray** [Codeusa/Borderless-Gaming#580]
Some applications I like to use Borderless Gaming with often change their title. E.g. every time the game Factorio updates (sometimes multiple times a day) it increments its title, it currently reads Factorio [1.1.70]. Because of this, I have to reopen Borderless Gaming and remove the old favorite and readd the new favorite every time the game updates. The ability to use a wildcard in the title, or a way for all windows that partially match a single string to work, would help greatly with this.

**Comment by Deamaed** [comment]
I would echo this, specifically for Flight Simulator 2020.  I use this program for multi monitor support to stretch windows.  MFSF2020 changes its title to whatever version it is, as in the OPs example.

**Comment by AndrewMD5** [comment]
The ReGex feature already supports this.

**Comment by Deamaed** [comment]
> The ReGex feature already supports this.

Thank you for pointing this out!  I didn't even realize this was a feature (and for the OP, when you right click to add to favourite, choose regex and you can edit the title to just the name). At least that is what I am trying with MSFS 2020.

**Comment by krestenlaust** [comment]
I can't find any regex/change name option in the context menu of an item in the favourite panel, am I looking in the wrong place?

**Comment by Deamaed** [comment]
That appears to be the case. I had to remove and then re-add the favourite using window title text (regex).
