### ISSUE TITLE
Games are Capped at 120 fps

### ISSUE THREAD

**Issue by GameBoyCymru** [Codeusa/Borderless-Gaming#591]
Regardless of what game settings I use, games are capped at 120 fps while using Borderless Gaming. If I disable the program, games run far higher.

**Comment by m1daz** [comment]
Similar issue except my goes up to even 140 but no more than that.

**Comment by joshuathomas22** [comment]
> Similar issue except my goes up to even 140 but no more than that.

Are you using version 9.5.6 or the beta?
