### ISSUE TITLE
Project Zomboid at 1080 in a 4K monitor

### ISSUE THREAD

**Issue by LuisGP** [Codeusa/Borderless-Gaming#592]
I want to play this game being rendered at 1080, but using a maximized borderless window. I have several monitors and changing the desktop resolution each time I want to play isn't an option. Using 4K as native resolution results in too small icons.
The current implementation changes the game's resolution to 4K again, not solving the main issue of the small icons.
I think the solution may be a deferred rendering and then upscale the result (as a texture maybe)?

**Comment by Hellscap3d** [comment]
> I want to play this game being rendered at 1080, but using a maximized borderless window. I have several monitors and changing the desktop resolution each time I want to play isn't an option. Using 4K as native resolution results in too small icons. The current implementation changes the game's resolution to 4K again, not solving the main issue of the small icons. I think the solution may be a deferred rendering and then upscale the result (as a texture maybe)?

PZ has builtin borderless. try that instead of this.
