### ISSUE TITLE
"Attempts to restore window to its bordered state" button not working

### ISSUE THREAD

**Issue by largewings** [Codeusa/Borderless-Gaming#600]
I tried to use the steam version of this app so I could use alt tab in the tale of two wastelands mod for falllout. However, I launch the game using Mod Organizer 2, so i set the Mod Organizer 2 window as a favorite using the borderless gaming app, now my mod organizer 2 window is permanently fullscreen, and theres nothing i can do to restore it. any help would be greatly appreciated since this is very annoying

edit: the button does work, i just needed to click it while Mod Organizer was closed, close out of Borderless Gaming, and then re-open Mod Organizer.

**Comment by talking-umbrellas** [comment]
When you say close you mean the application wasn't running or it currently wasn't on screen?
