### ISSUE TITLE
favorites gone after updating to latest version

### ISSUE THREAD

**Issue by adac7786** [Codeusa/Borderless-Gaming#608]
### Requirements

- [ ] This issue doesn't already exist
- [x] This bug is Not related to compatability with a specific game

### Summary

it seems like the settings file got changed with the recent 10.0 update from config.bin to config.config.bopbin and i cant import my old games. if i try to edit the new settings file borderless gaming crashes, if i try to rename the old file it crashes as well.

### Steps to reproduce

1. install new version
2. old favorite no longer recognized
3.

### version

10.0

**Comment by andrewmd5** [comment]
This is expected - 10.1 will migrate automatically
