### ISSUE TITLE
Doesn't work on UWP apps :/

### ISSUE THREAD

**Issue by xmas-dev** [Codeusa/Borderless-Gaming#620]
### Requirements

- [X] This issue doesn't already exist
- [X] This bug is Not related to compatability with a specific game

### Summary

Borderless Gaming does not work on UWP apps like the default Settings app or Minecraft for Win 10 (Bedrock). 
Some UWP apps like Minecraft have a built-in Fullscreen mode but it is terrible to use because the app does a reload every time it loses focus. Hence I have to run these apps in Windowed mode, but this makes their Title bar visible, taking up too much screen space. 
I was hoping Borderless Gaming would be able to hide them but as you can see in the screenshots attached, it seems to make the problem worse as the title bars get even bigger. Features like Set Window Title, Set Window Size, etc... don't work either. 

![Screenshot (2)](https://github.com/Codeusa/Borderless-Gaming/assets/117382404/59861adc-3765-4337-be92-ef35fce09c15)

![Screenshot (3)](https://github.com/Codeusa/Borderless-Gaming/assets/117382404/3a5e8ed1-683d-4a01-9cdc-03f0878d8b73)

### Steps to reproduce

1. Open a UWP app
2. Try applying Borderless Gaming Fullscreen on it

### Technical details

Using Win 11.

### version

9.5.6.1328 and 10.0.0.0

**Comment by ereesman** [comment]
@xmas-dev I apologize in advance for asking an unrelated question but I couldn't help but notice you have a dark-themed window title bar in Windows 11. I have been trying for a while now to figure out how to force all title bars (including windowed games) to respect the system theme but have so far been unsuccessful. I am able to get some apps like Microsoft Edge or Explorer app to respect the theme settings, but game windows especially seem to be White regardless of settings/theme configuration. 

Do you happen to have any tips/tricks along these lines? Thank you in advance!

**Comment by xmas-dev** [comment]
I don't think I did anything special for that. There's this native setting in Windows and it's probably what I used: 
![image](https://github.com/Codeusa/Borderless-Gaming/assets/117382404/048a096f-f40a-4a5d-8a91-c649780cda84)

**Comment by Aetopia** [comment]
> ### Requirements
> 
>     * [x]  This issue doesn't already exist
> 
>     * [x]  This bug is Not related to compatability with a specific game
> 
> 
> ### Summary
> 
> Borderless Gaming does not work on UWP apps like the default Settings app or Minecraft for Win 10 (Bedrock). Some UWP apps like Minecraft have a built-in Fullscreen mode but it is terrible to use because the app does a reload every time it loses focus. Hence I have to run these apps in Windowed mode, but this makes their Title bar visible, taking up too much screen space. I was hoping Borderless Gaming would be able to hide them but as you can see in the screenshots attached, it seems to make the problem worse as the title bars get even bigger. Features like Set Window Title, Set Window Size, etc... don't work either.
> 
> ![Screenshot (2)](https://private-user-images.githubusercontent.com/117382404/268006263-59861adc-3765-4337-be92-ef35fce09c15.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5ODU2NjQsIm5iZiI6MTcwNTk4NTM2NCwicGF0aCI6Ii8xMTczODI0MDQvMjY4MDA2MjYzLTU5ODYxYWRjLTM3NjUtNDMzNy1iZTkyLWVmMzVmY2UwOWMxNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyM1QwNDQ5MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yOGNhMzkzMzE3ZGE2NGE2NDYxM2MwOWE2YjJjNzRmMGQ5ZDkwMzk2MTcwMzk5MDA1MDE5ZTYzNGZmMjlhYWVkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.fws0eaFP5YOjhcGDExH_xpac-D3HqTI-noyugS23830)
> 
> ![Screenshot (3)](https://private-user-images.githubusercontent.com/117382404/268006272-3a5e8ed1-683d-4a01-9cdc-03f0878d8b73.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5ODU2NjQsIm5iZiI6MTcwNTk4NTM2NCwicGF0aCI6Ii8xMTczODI0MDQvMjY4MDA2MjcyLTNhNWU4ZWQxLTY4M2QtNGEwMS05Y2RjLTAzZjA4NzhkOGI3My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyM1QwNDQ5MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMDgzNjA5ZDQ5YWJhOGM5MzEyMGE0N2U0NDVkMWJiODljNzZhZWMxMDAwZWM4OTkyODNkNzUxNTljMzk2Mjc0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.AGmCK1T3BU9GlNQwx0AKcg-u2D7nMvJ-uFDQQb0XoRE)
> ### Steps to reproduce
> 
>     1. Open a UWP app
> 
>     2. Try applying Borderless Gaming Fullscreen on it
> 
> 
> ### Technical details
> 
> Using Win 11.
> ### version
> 
> 9.5.6.1328 and 10.0.0.0

UWP apps automatically suspend when they are minimized or hide themselves when in fullscreen.
UWP apps when fullscreen/borderless windowed don't actually minimize but are cloaked by the shell.
Also UWP core windows are a messed up concept, they don't work the same as desktop app windows.

I have made a program which can prevent UWP apps from being suspended by the system by throwing them into debug mode.
You can check out [AppLifecycleOptOut](https://github.com/aetopia/applifecycleoptout) and a [video demo](https://www.youtube.com/watch?v=uYkHrQEzyUo).
