### ISSUE TITLE
Even though "Mute In Background" is DISABLED, it STILL mutes my game when I click on my external monitor.

### ISSUE THREAD

**Issue by Popedigoz** [Codeusa/Borderless-Gaming#637]
### Requirements

- [X] This issue doesn't already exist
- [X] This bug is Not related to compatability with a specific game

### Summary

Title. When I click back to the game it's fine though.

### Steps to reproduce

Do NOT tick "Mute In Background"?

### Technical details

W11.

### version

10.0.0.0

**Comment by andrewmd5** [comment]
The game itself mutes when out of focus
