### ISSUE TITLE
Favorite windows don't automatically go borderless anymore

### ISSUE THREAD

**Issue by Slooshie1** [Codeusa/Borderless-Gaming#638]
### Requirements

- [X] This issue doesn't already exist
- [X] This bug is Not related to compatability with a specific game

### Summary

When I add any window to the favorites list for automatic conversion to borderless windows, they do not automatically convert. Instead, I have to manually do so. I have tested with multiple games and programs, including Minecraft which used to work fine until I got a recent auto-update

### Steps to reproduce

1. Open game ("Minecraft* 1.20.2 [Title] [Max]" in my case).
2. Select the game window in borderless gaming and click the right arrow to move it to the favorites (automatic) list.
3. After waiting for several seconds, try manually making the window borderless to verify that it works manually but not automatically

### version

9.5.6.1328

**Comment by RB490** [comment]
YES
