### ISSUE TITLE
X3 Terran Conflict / Albion Prelude

### ISSUE THREAD

**Issue by ElHyperion** [Codeusa/Borderless-Gaming#64]
Is anyone able to play these games, while launching them as fullscreen ones? This is almost the only game that I'm having major color problems with. It's windowed mode is unscalable, and doesn't overlap the main windows bar. BorderlessGaming fixes this problem well. However, the game forces it's AA to be disabled, and I cannot even fix it by forcing anti aliasing through my nVidia control panel, that even 32x CSAA is barely recognizable in that game.

So what I'm asking for, is if the program can be made switching the game into borderless windowed, from a fullscreen mode? There is no such option ingame and I cannot even do Alt + Enter. Sadly, I cannot play this game fullscreen, as it's colors are just so washed out and my nVidia control panel colors become ignored in it. All the X3 games by Egosoft are quite similiar, so if one works, the other 2 should aswell

**Comment by psouza4** [comment]
It's not the intent of Borderless Gaming to modify that kind of behavior.  Doing so is likely not even possible (without emulating a video display and causing all kinds of performance issues) and is probably not VAC safe.
