### ISSUE TITLE
crash : close game with alt+f4 

### ISSUE THREAD

**Issue by ddjoker** [Codeusa/Borderless-Gaming#641]
### Requirements

- [X] This issue doesn't already exist
- [ ] This bug is Not related to compatability with a specific game

### Summary

crash : close game with alt+f4 

### Steps to reproduce

- windows 11 
- game -- 原神(genshin impact)  
- permission -- administrator

1. run program  with startup .  
2. add game to favorites 
3. run game and then alt+f4 close it .
4. sometimes the progame will be crash 

### Technical details

```
+   Process with an Id of 14752 is not running.       ArgumentExceptionP     at BorderlessGaming.Logic.Windows.Native.QueryProcessesWithWindows(Action`1 callback, List`1 windowPtrSet) in C:\borderless-gaming\BorderlessGaming\Logic\Windows\Native.cs:line 443
   at BorderlessGaming.Logic.Core.ProcessWatcher.UpdateProcesses()
   at BorderlessGaming.Logic.Core.ProcessWatcher.Watch() in C:\borderless-gaming\BorderlessGaming\Logic\Core\ProcessWatcher.cs:line 59
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object `state)`
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
```

### version

Borderless Gaming 10.0-preview

**Comment by andrewmd5** [comment]
Thank you for the report - can you confirm if this issue still exist in RC.1 which was released last night?

**Comment by ddjoker** [comment]
same  .

**Comment by ddjoker** [comment]
`+   Process with an Id of 20340 is not running.       ArgumentException?     at BorderlessGaming.Logic.Windows.Native.QueryProcessesWithWindows(Action`1 callback, List`1 windowPtrSet) in \\Mac\Home\projects\Borderless-Gaming\BorderlessGaming\Logic\Windows\Native.cs:line 443
   at BorderlessGaming.Logic.Core.ProcessWatcher.UpdateProcesses() in \\Mac\Home\projects\Borderless-Gaming\BorderlessGaming\Logic\Core\ProcessWatcher.cs:line 204
   at BorderlessGaming.Logic.Core.ProcessWatcher.Watch() in \\Mac\Home\projects\Borderless-Gaming\BorderlessGaming\Logic\Core\ProcessWatcher.cs:line 59
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()`

**Comment by andrewmd5** [comment]
> ```
> 
> +   Process with an Id of 20340 is not running.    �   ArgumentException?     at BorderlessGaming.Logic.Windows.Native.QueryProcessesWithWindows(Action`1 callback, List`1 windowPtrSet) in \\Mac\Home\projects\Borderless-Gaming\BorderlessGaming\Logic\Windows\Native.cs:line 443
>    at BorderlessGaming.Logic.Core.ProcessWatcher.UpdateProcesses() in \\Mac\Home\projects\Borderless-Gaming\BorderlessGaming\Logic\Core\ProcessWatcher.cs:line 204
>    at BorderlessGaming.Logic.Core.ProcessWatcher.Watch() in \\Mac\Home\projects\Borderless-Gaming\BorderlessGaming\Logic\Core\ProcessWatcher.cs:line 59
>    at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
>    at System.Threading.ThreadPoolWorkQueue.Dispatch()
>    at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
> ```

Is this on 10.0-RC.1?

**Comment by ddjoker** [comment]
> > ```
> > 
> > +   Process with an Id of 20340 is not running.    �   ArgumentException?     at BorderlessGaming.Logic.Windows.Native.QueryProcessesWithWindows(Action`1 callback, List`1 windowPtrSet) in \\Mac\Home\projects\Borderless-Gaming\BorderlessGaming\Logic\Windows\Native.cs:line 443
> >    at BorderlessGaming.Logic.Core.ProcessWatcher.UpdateProcesses() in \\Mac\Home\projects\Borderless-Gaming\BorderlessGaming\Logic\Core\ProcessWatcher.cs:line 204
> >    at BorderlessGaming.Logic.Core.ProcessWatcher.Watch() in \\Mac\Home\projects\Borderless-Gaming\BorderlessGaming\Logic\Core\ProcessWatcher.cs:line 59
> >    at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
> >    at System.Threading.ThreadPoolWorkQueue.Dispatch()
> >    at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
> > ```
> 
> Is this on 10.0-RC.1?

yes

**Comment by andrewmd5** [comment]
fixed, will be available in the next release.

**Comment by ddjoker** [comment]
tks
