### ISSUE TITLE
Frameless Gaming

### ISSUE THREAD

**Issue by Xii-Nyth** [Codeusa/Borderless-Gaming#649]
### Requirements

- [X] This issue doesn't already exist
- [X] This is only a single feature request (Otherwise create a separate issue)

### Is this proposal related to a problem?

No

### Describe the solution you'd like

Alternate option to use frameless mode which just hides the titlebar and single pixel borders (basically borderless but without the window going over the taskbar)

An alternative solution is using autohotkey for this but that would mean making a separate script for each process, and also using windowspy for things with a changing (such as fps readout or version) or invisible title

**Comment by andrewmd5** [comment]
This can be achieved using the set size / position.

**Comment by Xii-Nyth** [comment]
does this feature exist in 9.5.6 or only the steam version?
