### ISSUE TITLE
crash rc1 windows 10

### ISSUE THREAD

**Issue by sentix001** [Codeusa/Borderless-Gaming#652]
### Requirements

- [X] This issue doesn't already exist
- [X] This bug is Not related to compatability with a specific game

### Summary

[Uploading BorderlessGaming.exe.14248.dmp…]()

### Steps to reproduce

crashed randomly

### version

10.0 rc1

**Comment by sentix001** [comment]
https://file.io/nxh4LePDHXWi

**Comment by sentix001** [comment]
it didnt upload on here

**Comment by andrewmd5** [comment]
Fixed on Steam.
