### ISSUE TITLE
Random crashing when closing programs

### ISSUE THREAD

**Issue by Josh65-2201** [Codeusa/Borderless-Gaming#655]
### Requirements

- [X] This issue doesn't already exist
- [X] This bug is Not related to compatability with a specific game

### Summary

After I close some programs not set into borderless mode, BG will just crash with an unhandled exception. It doesn't happen all the time or with every program

### Steps to reproduce

1. Open a program not set for borderless
2. Close program
3. Crash sometimes happens

### Technical details

[Logs.zip](https://github.com/Codeusa/Borderless-Gaming/files/14696392/Logs.zip)

### version

10 rc1

**Comment by andrewmd5** [comment]
This is fixed on the latest Steam release

**Comment by AgentFire** [comment]
@andrewmd5 this one too? 

[BorderlessGaming.exe.30572.dmp.zip](https://github.com/user-attachments/files/21538800/BorderlessGaming.exe.30572.dmp.zip)

Throws at Process.cs:1652
