### ISSUE TITLE
Dark Mode not working

### ISSUE THREAD

**Issue by zISKo666** [Codeusa/Borderless-Gaming#659]
### Requirements

- [X] This issue doesn't already exist
- [X] This bug is Not related to compatability with a specific game

### Summary

I already bought the dark mode dlc on steam but can't activate it.
Sometimes nothing happend when i try to activate it.
Sometimes it says i have to buy the dlc on steam.

Maybe it depends on the fact that i've disabled the steam integration!?

So i guess this ia just a bug and i have to wait until it is fixed!? ;)

### Steps to reproduce

1. Right click on try icon and activate dark mode
2. Nothing happens or
3. Get a notification that says "Buy the DLC"

### Technical details

Windows 11 (latest update)

### version

lates update on steam10.0.8

**Comment by zISKo666** [comment]
![grafik](https://github.com/Codeusa/Borderless-Gaming/assets/6992216/e127968f-318d-406a-a002-6178a101daa6)

**Comment by PlayerX11294** [comment]
I have the same issue. There is no way to enable dark mode even after purchasing the DLC. I even tried the windows-F7 hotkey, but that only popped up a window that gave me an achievement. Nothing I do can get dark mode to work.

**Comment by andrewmd5** [comment]
Sorry y'all are running into this issue. If you're all on 10.0.8 can you confirm if you've
- Fully closed Borderless Gaming
- Restarted Steam
- Launched Borderless Gaming from Steam

**Comment by andrewmd5** [comment]
> ![grafik](https://private-user-images.githubusercontent.com/6992216/316971504-e127968f-318d-406a-a002-6178a101daa6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1MTQ0MTksIm5iZiI6MTcxMTUxNDExOSwicGF0aCI6Ii82OTkyMjE2LzMxNjk3MTUwNC1lMTI3OTY4Zi0zMThkLTQwNmEtYTAwMi02MTc4YTEwMWRhYTYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjdUMDQzNTE5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Mzc1ZmZhNzhiNTc1NzQ1ZjU4YzU0YzA3YzNlZGE0YTUyMThiZTk2M2Y1ODRkM2JhNjNjZDExZWYzYzM1NGE5OSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.o8MBPoWl8C6NlRGEK6MNviGdi8E6tUe4WPF3FpiXVA0)

Can you open a separate issue for this UI bug and confirm your display / DPI settings?

**Comment by PlayerX11294** [comment]
> Sorry y'all are running into this issue. If you're all on 10.0.8 can you confirm if you've
> 
>     * Fully closed Borderless Gaming
> 
>     * Restarted Steam
> 
>     * Launched Borderless Gaming from Steam
> 
> 
> Also from inside Steam, can you confirm that "dark mode" is installed?
> 
> Right click Borderless Gaming in your library -> Properties - DLC and see if "Dark Mode" is Installed. Steam may not have installed it if BG was running.

I just tried it again today after Steam restarted and suddenly I had an option to enable dark mode. I tested and it's working for me now. Sorry, didn't know I had to restart Steam to get it to work. Thanks!

**Comment by zISKo666** [comment]
After todays update everything is looking fine to me.

Thank you for the fix :)
