### ISSUE TITLE
resizing the screen in pixels no longer works

### ISSUE THREAD

**Issue by Irydius** [Codeusa/Borderless-Gaming#662]
### Requirements

- [ ] This issue doesn't already exist
- [ ] This bug is Not related to compatability with a specific game

### Summary

Since update 10.0.5, the function to resize the screen to a specific pixel no longer works. Instead of doing the action, nothing happens at all; as if it remains in full screen mode. 

This was not a bug that was present in the old versions that I experienced, and I find it relatively annoying.

I hope you go and fix this soon because it's annoying to have to do it in about time.

### Steps to reproduce

1. Select an application to favorite it
2. Go from: No size change to set window size
3. select NO and make your adjustments as you see fit. In the end, you will realize that nothing is happening.

### version

10.0.5

**Comment by andrewmd5** [comment]
Just to confirm - does using the rectangle selector still work for you?

**Comment by Irydius** [comment]
Yes of course it is a function that works. This is my emergency exit in case it doesn't work, but it's a bit annoying to have to do it in a while. Especially in the end, sometimes the app screen isn't completely full at the bottom, when I try to get it right.

**Comment by andrewmd5** [comment]
Just making sure. I’ll debug and report back

Sent via Superhuman iOS ( ***@***.*** )

**Comment by aqqtran** [comment]
I'm also getting this issue. Resizing to specific pixel is completely broken. Have to rely on the rectangle resize which isn't ideal.

**Comment by andrewmd5** [comment]
Fixed: 

https://store.steampowered.com/news/app/388080/view/4167592764429534999
