### ISSUE TITLE
Free builds / installers

### ISSUE THREAD

**Issue by bigfinfrank** [Codeusa/Borderless-Gaming#664]
### Summary

In [the 10.0.0 (Steam) GitHub Release](https://github.com/Codeusa/Borderless-Gaming/releases/tag/10.0-steam), it was stated that "Free builds / installers will be made available in two weeks and this release will be updated. You can find release notes [here](https://store.steampowered.com/news/app/388080/view/6324815007263438108)."

Are there any updates on this front? I purchased BG on Steam to support the project however I prefer to compile from source and as of right now, the binaries don't seem to be matching up when compiled from the net8 branch, presumably because of missing commits.

**Comment by VictorienXP** [comment]
Yes I noticed exactly the same thing and stated that directly to the dev which you can see here their response here: https://steamcommunity.com/app/388080/eventcomments/4293692546850196709?snr=2_9_100000_&ctp=5#c4293692546851325740

I had no further response after that and still no trace of the latest source code so [I made a negative Steam review](https://steamcommunity.com/id/VictorienXP/recommended/388080) which the dev responded with:
> User doesn't understand how Github works - the code is fully available on a draft PR in the "Steam" branch. Stop trying to start witch-hunts.

So yeah the dev is actively lying about the whole thing and accuses me of not understanding GitHub instead.

**Comment by EzioTheDeadPoet** [comment]
> Yes I noticed exactly the same thing and stated that directly to the dev which you can see here their response here: [removed URL]
> 
> I had no further response after that and still no trace of the latest source code so [I made a negative Steam review][URL removed] which the dev responded with:
> 
> > User doesn't understand how Github works - the code is fully available on a draft PR in the "Steam" branch. Stop trying to start witch-hunts.
> 
> So yeah the dev is actively lying about the whole thing and accuses me of not understanding GitHub instead.

1. Not sure where that "Steam" branch should be. There is only a TAG `10.0-steam`, that has git errors.
2. When you build that source code you get the following error:  
  ![image](https://github.com/Codeusa/Borderless-Gaming/assets/52624146/f80c23a5-7563-441a-9f16-e5234472fa68)

**Comment by EzioTheDeadPoet** [comment]
Update: I managed to compile a working `10.0-steam` version.
Not sure if it truly has all the options. But also being able to do that doesn't negate the fact that the latest update post that is now 3weeks old according to GitHub hasn't been updated with the build release.

**Comment by swemoney** [comment]
Can confirm the same with Visual Studio, building alone gives you the UI Translations error but publishing to a folder runs fine. I don't see dark mode in the 10.0-steam tag though so it doesn't look like it's up to speed with the actual Steam release.

**Comment by Kenjugs** [comment]
To get it to run properly, you have to put the Languages.zip file (from the Languages folder) in the same place as the BorderlessGaming.exe that gets built.

**Comment by KawaiiSelbst** [comment]
> To get it to run properly, you have to put the Languages.zip file (from the Languages folder) in the same place as the BorderlessGaming.exe that gets built.

Or just make 
```
dotnet publish
```
in your console, and dotnet make it self

**Comment by andrewmd5** [comment]
Nothing is closed source. I’m just not making builds available anymore because people don’t finically support the project.

And every contributor signed a CLA that supersedes GPL, because boy was that a stupid choice that license for desktop software.

Sent via Superhuman iOS ( ***@***.*** )

**Comment by Alanimdeo** [comment]
![image](https://github.com/Codeusa/Borderless-Gaming/assets/32806763/f8f4ac1d-7d9a-4c32-b7af-984420248bd1)
but no source code disclosure for the latest version lol

**Comment by andrewmd5** [comment]
> > You also might want [to take another look at the license](https://github.com/Codeusa/Borderless-Gaming/blob/3cc4dc6bd580b263287be45981f1e36036daf4eb/LICENSE#L30). An additional agreement to restrict the license is disallowed by the license.
> 
> I don't think we will get source unless someone has the knowledge and funds to work on getting the gpl license enforced.

????

https://snapshots.andrew.im/bg/{version}.zip

**Comment by EzioTheDeadPoet** [comment]
> > > You also might want [to take another look at the license](https://github.com/Codeusa/Borderless-Gaming/blob/3cc4dc6bd580b263287be45981f1e36036daf4eb/LICENSE#L30). An additional agreement to restrict the license is disallowed by the license.
> > 
> > 
> > I don't think we will get source unless someone has the knowledge and funds to work on getting the gpl license enforced.
> 
> ????
> 
> [https://snapshots.andrew.im/bg/{version}.zip](https://snapshots.andrew.im/bg/%7Bversion%7D.zip)
> 
> Anyway this will only work up until v11 since I rewrote the program in Zig

This doesn't even work right now...
![image](https://github.com/user-attachments/assets/4093046d-6d68-4685-aac6-9e3270bb86e9)

I also tried the following versions there to make sure it isn't somehow related to that:
- `10.0.0`
- `10`
- `v10`
- `v10.0.0`
- `10.0.20`
- `v10.0.20`
- `10.0.22`
- `v10.0.22`

It is funny to see such an amazing software being ruined by an active scammer that now also went ahead and also put a paid "clone" (the UI code is different but the underlying compression is the same, at least in the efficiency) of CompactGUI onto Steam.

**Comment by Alanimdeo** [comment]
> > > You also might want [to take another look at the license](https://github.com/Codeusa/Borderless-Gaming/blob/3cc4dc6bd580b263287be45981f1e36036daf4eb/LICENSE#L30). An additional agreement to restrict the license is disallowed by the license.
> > 
> > 
> > I don't think we will get source unless someone has the knowledge and funds to work on getting the gpl license enforced.
> 
> ????
> 
> [https://snapshots.andrew.im/bg/{version}.zip](https://snapshots.andrew.im/bg/%7Bversion%7D.zip)
> 
> Anyway this will only work up until v11 since I rewrote the program in Zig

There is no DNS record for `snapshots.andrew.im` at all, is this even possible?

**Comment by andrewmd5** [comment]
> I suspect the site not working is intentional, everything that's been done so far has pointed to stalling for time, presumably until his mentioned v11 release is done or the community gets sick of trying. He's made it pretty clear he's not interested in open sourcing new versions. I'm not happy with this either, but like DigitalNikki said, unless someone wants to put money into it and tackle it legally, realistically I don't think he's going to give in. But hey! I'd absolutely love to be proven wrong.
> 
> I'm personally pretty sick of this, so I'm going to try to make the best of it and provide some options going forward for the community:
> 
> 1. Actually open source alternatives already exist such as [NoMoreBorder](https://github.com/invcble/NoMoreBorder).
> 2. If you're fine with the older version, you can always use [v10.0-rc1](https://github.com/Codeusa/Borderless-Gaming/releases/tag/10.0-rc.1) which I'd assume is built off the current net8 branch, if not, building from the net8 branch is always an option.
> 3. If you really want dark mode, dnSpy isn't particularly hard to use, I'm sure someone could create a fork of the project and implement his dark mode feature nearly identically, he's using an open source library called [DarkNet](https://github.com/Aldaviva/DarkNet), it's nothing special. I should note that although not necessary legally, to keep everything above board ethically, checking for a license via the steam API is something a fork easily could (and should) do, all you'd need to do is check for ownership of the DLC's AppID. However realistically anyone who wants it would just use smokeapi anyways, I'm sure people are already doing this with the steam version given how controversial the dark mode dlc is, I'm not sure if his DRM is more advanced, but we'll likely never find out, that's the decision he's making (or maybe he'd like to make an open source contribution to the fork!).
> 4. Most games nowadays have _some_ way to activate  borderless windowed mode, [PCGamingWiki](https://www.pcgamingwiki.com/wiki/Home) is a pretty useful resource for finding native ways, a lot of the time a launch option or simple false -> true configuration file edit will do the trick. If not there's often a community mod. Obviously using BG is supposed to _avoid_ needing to do this per-game, but it is still a functional fallback option if nothing else appeals to you and you're not a fan of using closed source apps that monitor your process list.
> 
> With that said, I'm going to be unwatching the issue, feel free to tag me if you have anything to say/ask me, or if the issue gets closed without resolution, I'd be happy to reopen it so people in our position can still easily find it. Or Andrew can pin the issue and then close it as not planned, that's a fair compromise in my eyes as I don't see anyone coming to this repository for any reason aside from this going forward.

Just to clarify, DarkNet just does titlebars, not the UI.

Anyway, I’m seeing a lot of demands from people who contribute nothing to the project either financially or code wise so I’m closing this issue. There will no longer be any free builds and snapshots of the code can be found from the URL above; maybe in the future I’ll resync to github once v11 is complete.

The last version 10 RC build will remain available and has most of the changes for a prebuilt. Or you can buy the program on Steam.

**Comment by adamk33n3r** [comment]
> Nothing is closed source. I’m just not making builds available anymore because people don’t finically support the project.
> 
> And every contributor signed a CLA that supersedes GPL, because boy was that a stupid choice that license for desktop software.

Why are you so greedy? All of a sudden people have to financially support you? Such a weird stance to take. "I put free builds on github but people won't give me money so now I'll take the builds off." ???? What did you expect?
