### ISSUE TITLE
Unhandled Exception when opening steam

### ISSUE THREAD

**Issue by namquang93** [Codeusa/Borderless-Gaming#666]
### Requirements

- [X] This issue doesn't already exist
- [X] This bug is Not related to compatability with a specific game

### Summary

I'm using Moonlight Sunshine to stream my desktop to play games remotely. Whenever I have Borderless Gaming running in the background, I get an error popup from Borderless Gaming with an unhandled exception.

![435810461_2315586191944994_1255202611641411437_n](https://github.com/Codeusa/Borderless-Gaming/assets/5283157/2b9b0b76-93c2-4a30-8c68-97eed49a9aa6)

Here is the exception crash:
```
*   Process with an Id of 9920 is not running.       ArgumentExceptionr     at BorderlessGaming.Logic.Windows.Native.QueryProcessesWithWindows(Action`1 callback, List`1 windowPtrSet) in \\Mac\Home\projects\Borderless-Gaming\BorderlessGaming\Logic\Windows\Native.cs:line 443
   at BorderlessGaming.Logic.Core.ProcessWatcher.UpdateProcesses()
   at BorderlessGaming.Logic.Core.ProcessWatcher.Watch() in \\Mac\Home\projects\Borderless-Gaming\BorderlessGaming\Logic\Core\ProcessWatcher.cs:line 59
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
```

### Steps to reproduce

1. Step Moonlight, Sunshine for game streaming
2. Open Borderless Gaming and let it minimize to system tray
3. From the client, start Steam Big Picture mode for streaming

### version

10.0-rc1

**Comment by andrewmd5** [comment]
10.0-rc1 is out of support. Please use the latest release from Steam as this issue was fixed.
