### ISSUE TITLE
[Game]: Euro Truck Simulator 2 / Steam - BG makes the Properties window of Euro Truck Simulator Borderless

### ISSUE THREAD

**Issue by LukasDotExe** [Codeusa/Borderless-Gaming#667]
### Requirements

- [x] This issue doesn't already exists
- [x] This bug is only related to a single game
- [x] Filled out the title with template

### Summary

As soon as I open the Steam Properties tab of the above mentioned game, BG makes the Steam properties window borderless and upon closing the Steam Properties window, BG makes the Steam Window Borderless

### Steps to reproduce

1. Install Steam version 1709846872
2. Install Euro Truck Simulator 2 experimental_beta - Experimental Public Beta 1.50
3. Install TruckersMP 0.2.5.2.0
4. Install Borderless Gaming 10.0.12.0
5. Add Euro Truck Simulator 2 [Title] to the Favorites
6. Add Euro Truck Simulator 2 Multiplayer [Title] to the Favorites
7. Open Properties window of Euro Truck Simulator 2
8. Observe
9. Close Properies window of Euro Truck Simulator 2
10. Observe

### Technical details

![image](https://github.com/Codeusa/Borderless-Gaming/assets/167638690/808078fd-84d5-483e-82f5-491cf1e05692)

### version

10.0.12.0

**Comment by Josh65-2201** [comment]
Set it to use the executable (Right click it on applications > Add to favorites > by process binary) rather then title.

**Comment by andrewmd5** [comment]
I’ll update to exclude Steam windows (it should be already but I just noticed it’s slipping through in some cases)
