### ISSUE TITLE
[UI/Language] Newline characters (\r\n) appear in confirmation dialogs.

### ISSUE THREAD

**Issue by Ephemeronic** [Codeusa/Borderless-Gaming#669]
### Requirements

- [X] This issue doesn't already exist
- [X] This bug is Not related to compatability with a specific game

### Summary

Newlines aren't being properly parsed from the language resources: the \r\n characters appear as normal text. 
![image](https://github.com/Codeusa/Borderless-Gaming/assets/46547401/b549772a-3272-46d2-831a-9d61c5caa6f2)
Issue exists in both master & net8. Apologies for not just committing a fix, but I'm relatively unfamiliar with Git/Github's processes / etiquette. 

### Steps to reproduce

1. Be using en-US language
2. Click Tools menu
3. Click "Mouse Cursor Visibility"
4. Notice that the formatting is a block of text with \r\n peppered throughout

### Technical details

This can be resolved by checking for the newline characters in LanguageManager.Data() (either in an else block in the null/empty check, or after that if is closed):
`data = data.Replace(@"\r\n", Environment.NewLine);`

![image](https://github.com/Codeusa/Borderless-Gaming/assets/46547401/290e5fc0-08a5-44a0-ab1f-8e2d3ed2312e)

### version

10.0.0.0

**Comment by andrewmd5** [comment]
This is fixed on Steam

**Comment by PavloveVR** [comment]
> This is fixed on Steam

Can you link the commit? That type of fix is supposed to be mirrored here after 2 weeks. 
People are asking about that in #664
