### ISSUE TITLE
If use have dual monitors you might face issues

### ISSUE THREAD

**Issue by Biokidhd** [Codeusa/Borderless-Gaming#67]
I have used this on a few games (Grid Auto-sports is one) and i have found that if you have dual monitors and use this, it will put the game in the middle on both screens. i found a way to fix this you can go to task manager and right click on the game and click maximize and it will go to your first screen. i would like to see if you could implement a fix for this or maybe mention this since other people might face this and might not know how to fix this.

**Comment by psouza4** [comment]
My unofficial fork has a patch that lets you specify a position now.  You may want to try it and see if it resolves this issue with Eyefinity.

**Comment by snv** [comment]
I have my main screen on the right side, so i expect that it will not start at 0x0.
Often games get maximised on the wrong screen.
It would be best if it were possible to choose which device to use, i think.

**Comment by psouza4** [comment]
All of these issues are resolved in recent builds that let you select monitors, draw regions, and specify exact coordinates as desired.
