### ISSUE TITLE
No more free Borderless Gaming?

### ISSUE THREAD

**Issue by JinsimeuroGamsadeurimnida** [Codeusa/Borderless-Gaming#673]
### Summary

So I have to buy it on Steam now to get the latest version? No more free versions here with new builds?

"Free builds / installers will be made available in two weeks and this release will be updated. You can find release notes here."

That was March, 19th so I'm assuming that the free version is dead now?

**Comment by stevened7246** [comment]
> ### Summary
> So I have to buy it on Steam now to get the latest version? No more free versions here with new builds?
> 
> "Free builds / installers will be made available in two weeks and this release will be updated. You can find release notes here."
> 
> That was March, 19th so I'm assuming that the free version is dead now?

You can compile it yourself, no programming knowledge is required

**Comment by JinsimeuroGamsadeurimnida** [comment]
It was actually very easy to compile/build it! Thank you and good luck with sales on Steam
