### ISSUE TITLE
Dayz Standalone,Nether Resolution problem and Not borderlining problem

### ISSUE THREAD

**Issue by SexyBigMaMa** [Codeusa/Borderless-Gaming#68]
Well in Dayz Standalone it works although it makes the resolution 75% (1440x810) and thats it i mean its borderless but its kinda annoying that i can see pixelated u know.. and i have another issue with a game called "Nether" on steam.. It just does not make it borderless it makes it 3/4 full like not borderless it like makes it windowed/borderless kinda idk i will put down a image of what happens.

Here is the problem in Nether:

I run it in windowed I do the thing but it just does not make it borderless for some reason.

![this is what it does when i try to make it borderless](https://cloud.githubusercontent.com/assets/8084280/3490307/d2cbd510-0568-11e4-82d1-397bf8f4dda2.png)

Here is the problem in DayZ Standalone:

This is the resolution i get and i cant change it:
![image](https://cloud.githubusercontent.com/assets/8084280/3490311/27e90a36-0569-11e4-84d9-626fcd26fa73.png)

This is what happens when i try to change it:

![image](https://cloud.githubusercontent.com/assets/8084280/3490316/333f7488-0569-11e4-9bf2-1e208b600e09.png)
After i press it:

![image](https://cloud.githubusercontent.com/assets/8084280/3490320/5bb24a12-0569-11e4-9365-76447fff9c82.png)

It doesn't actually make the resolution it just redoes it back to 1440x810:

![image](https://cloud.githubusercontent.com/assets/8084280/3490323/783d5ea6-0569-11e4-9dce-2ed38712026a.png)

Thats it thats all i got with my issues in games non the less nothing else The Forest is working fine uhmm GTA is working fine and others as well.

**Comment by Codeusa** [comment]
Fixed

**Comment by mert1337** [comment]
how you fixed it? i still have this damn problem -.-

**Comment by SexyBigMaMa** [comment]
me too... not fixed

**Comment by mert1337** [comment]
uff damn :(
