### ISSUE TITLE
Risk of Rain

### ISSUE THREAD

**Issue by HeyItsJono** [Codeusa/Borderless-Gaming#79]
This program works great for the likes of Joylancer and many other games but it seems to have an odd incompatability with the game "Risk of Rain" in that, when you try to make the game borderless, it flashes white once the button is pressed (or every so often if it's put in the favourites list) and then is moved "to the top" as the active window, appearing above the task bar, which is fine, except the borders are still on the game. Would there be any way to go about fixing this? I understand asking for help for one specific game is a bit silly but I'm thinking if this bug happens to this game it could possibly happen to others as well.

**Comment by psouza4** [comment]
This appears to be resolved with my unofficial fork version 7.2, although your Windows resolution needs to match one of the options provided in the Risk of Rain video settings.  Ex: 1920x1080 is fine by 1920x1200 is not.  You'll get border removal, but it'll force the window to be 1920x1080 (max) and you'll have parts of your Desktop appearing at the top and bottom of the game.  This is an issue with Risk of Rain, not Borderless Gaming, unfortunately.

**Comment by bitingsock** [comment]
I'd like to reopen this issue. I'm using bg 8.2 and risk of rain 1.2.8 and it is not working right. Was your fix ever merged into the main branch?
