### ISSUE TITLE
Mabinogi won't borderless

### ISSUE THREAD

**Issue by Lilrock** [Codeusa/Borderless-Gaming#82]
Hello, Could you put Mabinogi (Free MMO) as a borderless game please :)

**Comment by vurtic** [comment]
Something in 7.5 seems to have broken fullscreening Mabinogi. You can download version 6.5 and Mabinogi should be fullscreen borderless properly.

**Comment by psouza4** [comment]
You'll have to be more specific about what the exact issue with 7.5 is using that game.

**Comment by vurtic** [comment]
I'm not sure what the problem is, and don't exactly know how to go about investigating. Clicking "Make Borderless" doesn't do anything. Otherwise, just using 6.5 will work.

**Comment by psouza4** [comment]
Does Borderless Gaming affect the process at all?

Have you tried adding it by both the process name as well as the window title (window title is the default)?

**Comment by vurtic** [comment]
Both don't do anything. Tried using the button on the center, right clicking and selecting all of my monitors, super size, and they also don't do anything. I've also tried a combination of the favorite options with no effect. Tried fullscreening a different application, and that other application became fullscreen borderless.

**Comment by psouza4** [comment]
vurtic, try new version 7.6 and see if that resolves your issue?

**Comment by vurtic** [comment]
7.6 does not fix it. When adding to the favorite's list via window title name, the name is blank (looks like " [Max]"). Using the process binary name still does not work. The process name and window title are different (process: Client.exe, window title: Mabinogi). Also, in 6.5, right clicking and choosing Make Borderless on... > any of the windows does not work either. Perhaps that will additionally help pinpoint the issue.

**Comment by vurtic** [comment]
Another thing that may or may not be helpful: after clicking on the application name, it will deselect itself after a few seconds. This does not happen for the other applications.

**Comment by psouza4** [comment]
vurtic, run Borderless Gaming as an Administrator,

Mabinogi's hackshield elevates the game process, which means only elevated applications can modify the window styles.  Borderless Gaming no longer runs as Administrator anymore to prevent issues with automatic updates and running at startup.

**Comment by vurtic** [comment]
That was it! Thanks for helping out
