### ISSUE TITLE
'Update available' dialog for 6.5

### ISSUE THREAD

**Issue by AngryNil** [Codeusa/Borderless-Gaming#92]
I've noticed over the past few days that I get an 'Update available' pop-up dialog when launching 6.5. Clicking 'OK' brings me to the release page for 6.5. I've tried re-downloading and replacing the files, but it doesn't seem to help.

**Comment by psouza4** [comment]
You'll have to download the update from my fork until Andrew is back in town to publish a build

**Comment by Codeusa** [comment]
Set it back tp 6.5 until im back state side.

**Comment by AngryNil** [comment]
Awesome, thanks guys.
