### ISSUE TITLE
GetWindowLong function has been superseded.

### ISSUE THREAD

**Issue by CoenraadS** [Codeusa/Borderless-Gaming#96]
Per MSDN:

>If you are retrieving a pointer or a handle, this function has been superseded by the GetWindowLongPtr function. (Pointers and handles are 32 bits on 32-bit Windows and 64 bits on 64-bit Windows.) To write code that is compatible with both 32-bit and 64-bit versions of Windows, use GetWindowLongPtr.

**Comment by psouza4** [comment]
Borderless Gaming versions 7.4 and newer already use GetWindowLongPtr.  Not sure what code you're adjusting, but you may have an old repository.

**Comment by CoenraadS** [comment]
This was the latest commit, and I don't see any references to GetWindowLongPtr.

**Comment by psouza4** [comment]
There are some issues with the master repo, it looks like, as there are different copies of /WindowsApi and /WindowsAPI (which were merged in 7.3).  We need to have Andrew clean it up.

**Comment by psouza4** [comment]
The current version has this code:

```
  [DllImport("user32.dll", EntryPoint = "GetWindowLong", SetLastError = true)]
        private static extern WindowStyleFlags GetWindowLong32(IntPtr hWnd, WindowLongIndex nIndex);

        [DllImport("user32.dll", EntryPoint = "GetWindowLongPtr", SetLastError = true)]
        private static extern WindowStyleFlags GetWindowLong64(IntPtr hWnd, WindowLongIndex nIndex);

        /// <summary>
        // This static method is required because legacy OSes do not support SetWindowLongPtr 
        /// </summary>
        public static WindowStyleFlags GetWindowLong(IntPtr hWnd, WindowLongIndex nIndex)
        {
            if (IntPtr.Size == 8)
                return Native.GetWindowLong64(hWnd, nIndex);

            return Native.GetWindowLong32(hWnd, nIndex);
        }
```

**Comment by CoenraadS** [comment]
Alright, pretty much the same thing. Feel free to close this issue if it isn't necessary.

**Comment by psouza4** [comment]
Appreciate the assist nonetheless :D

**Comment by psouza4** [comment]
Just so you know that you weren't crazy: the latest official repo didn't have the GetWindowLongPtr switch like it should have.  I pushed 7.7 yesterday, which was merged, and should include it proper now.  Repo still needs some cleaning but you weren't wrong: it was legitimately missing!
