### ISSUE TITLE
Can't Close from Tray

### ISSUE THREAD

**Issue by wxMichael** [Codeusa/Borderless-Gaming#99]
If the option to close to tray is enabled, it is impossible to actually exit Borderless Gaming 7.7, even from the system tray.

**Comment by gutsanglory** [comment]
Just downloaded version 7.7 installed on windows 7, same think..have to kill it with the task manager.

**Comment by psouza4** [comment]
Working fine here.  Are you using options to hide the Windows taskbar or mouse cursor?  Both of those features will temporarily prevent application exit.

**Comment by gutsanglory** [comment]
If I just minimize the app…I can close it, but if I choose to close to tray…I can no longer close it.

No I don’t use taskbar or mouse hide.

 

 

Thx,

**Comment by wxMichael** [comment]
The only options checked are 'Start Minimized to Tray' and 'Close to Tray.'
Without 'Close to Tray' enabled, I can close it from the X at the top-right or from the tray icon menu while it's minimized to the tray.

I'm on Windows 8.1 x64, in case that affects it.

**Comment by psouza4** [comment]
I found a bug that could be responsible for this behavior under the right circumstances.  Let me patch it up and submit a pull request to get it live.

In the meanwhile, please turn off "Close to Tray" as a workaround until version 7.8 becomes available.

**Comment by gutsanglory** [comment]
Thx !

**Comment by psouza4** [comment]
Okay, changes made and pull request submitted.  If you want to preview version 7.8 before it hits official, you can here:

https://github.com/psouza4/Borderless-Gaming/releases/tag/7.8

Make sure you install the admin version if you want automatic elevation (like it was previously in version 6.5).

**Comment by wxMichael** [comment]
It's working great now; thanks for the quick fix.

**Comment by psouza4** [comment]
Glad to hear it!

**Comment by gutsanglory** [comment]
Yup...confirmed...all good.
THX.

**Comment by Orangestar12** [comment]
Thanks for fixing this one, thought I was going crazy and then noticed it in the release changelog.
